obsidianmd/obsidian-releases

- community-themes.json
> Added Christmas theme

- community-themes.json
I added my Obsidian Atom theme!
Here's the screenshot I included, not sure if it would be cleaner to include only the dark/light one though. I couldn't get a GIF to look nice.
❤️
> Add Atom theme

- community-themes.json
> Added Obsidianite theme

- community-plugins.json
I'll rename my repo as soon as this is accepted.
Thank you.
> Rename table editor plugin

- community-plugins.json
...again... Third time's the charm?
> Added Editor Syntax Highlight plugin

- community-plugins.json
> A pull request to add the Review plugin. Thanks!

- community-plugins.json
👋
https://github.com/FHachez/obsidian-convert-url-to-iframe
> Add convert url to iframe plugin

- community-plugins.json
This plugin allows inserting text context search results on the active note, the plugin is based on the plugin mrj-text-expand-witb-text of MrJackphil.
> Add Search++ plugin

- community-plugins.json
Sorry for the inconvenience :)
> Trying again, Better Word Count Plugin

- community-plugins.json
> Adding the Workbench plugin

- community-plugins.json
Update community-plugins.json to include css-snippets plugin
> Add css-snippets plugin

- community-plugins.json
Hi! This is an initial iteration just to start working on it. I had a few hiccups with tagging, so version 0.0.2 is the same as v0.0.1
> Add obsidian-link-indexer

- community-plugins.json
Hope I did it right in one go this time...
> A simple new plugin

- community-plugins.json
Hi @lishid, I think a fresh pull request is a good idea. Here it goes, hope it works this time :)
> Adds highlight extractor

- community-plugins.json
My first obsidian plugin, hopefully I did it near enough to correctly to work.
> Add obsidian-dangling-links plugin

- community-plugins.json
Hi @lishid,
I'd like to submit my Dangerzone Writing plugin (See https://forum.obsidian.md/t/dangerzone-flowstate-like-plugin-prototype/8776) for details with this PR.
Let me know if this is okay!
Thank you, 
Alexis
> Adds Dangerzone Plugin

- community-plugins.json
"Add Codemirror's matchbrackets.js" plugin added
> "Add Codemirror's matchbrackets.js" plugin

- community-plugins.json
Hi Obsidian creators, 
The following makes use of the current switcher to allow you to search for a insert emojis.
Let me know if you need any other changes before it can be accepted
> Add obsidian-emoji-toolbar

- community-plugins.json
Added my simple fullscreen plugin to community plugins.
> Added fullscreen plugin  to plugins list

- community-plugins.json
Hi, I've just created a very basic integration with Zotero. Added here. Thanks devs for all the hard work!
> Add Citations plugin

- community-plugins.json
Hey,
Please approve my [Plugin](https://github.com/urishiraval/obsidian-apple-reminders-plugin) for the Obsidian Folio.
Warm Regards,
A Huge Fan of your Team's Work.
> Add Apple Reminders Plugin

- community-plugins.json
See: https://github.com/mgmeyers/obsidian-contextual-typography
> Add Contextual Typography plugin

- community-plugins.json
Repo: https://github.com/HEmile/semantic-markdown-converter
EDIT: Tested on macOS Catalina 10.15.7 and Windows 10
> Add Neo4j Graph View plugin

- community-plugins.json
Hi @lishid! 
I've put this PDF to Markdown generator together and think the community would enjoy using it.
Please have a look and if you find anything during QA, please let me and I'll go and fix it. 
Thank you so much, 
Alexis
> Adding PDF to Markdown plugin

- community-plugins.json
https://github.com/nadavspi/obsidian-relative-line-numbers
> Add relative line numbers plugin

- community-css-themes.json
- community-plugins.json
- community-themes.json
Signed-off-by: Radek Kozak <radoslaw.kozak@gmail.com>
> Add Discordian theme

- community-plugins.json
Hi there,
I've created a minimalistic reminder in the status bar for how long the vault is open.
All the best,
Felix
> add youhavebeenstaring plugin

- community-plugins.json
https://github.com/avirut/obsidian-metatemplates
> Add obsidian-metatemplates

- community-plugins.json
https://github.com/avirut/obsidian-query2table
> Add obsidian-query2table

- community-plugins.json
Simple plugin that adds context menu items to search based on note title.
> Add "Search on Internet"

- community-plugins.json
Icons Plugin: Use icons in your notes.
https://github.com/visini/obsidian-icons-plugin
> Add visini/obsidian-icons-plugin

- community-plugins.json
> Vantage v1.0.0

- community-plugins.json
@lishid this is the new pull-request which is properly formatted
> Adding Obsidian Query Language plugin

- community-plugins.json
As you wished I renamed it. I took your suggestion but changed shortcut to assistant. What do you think?
> Added my new plugin, renamed version V2

- community-plugins.json
Adds the obsidian dataview plugin.
> Add obsidian-dataview

- community-plugins.json
https://github.com/liamcain/obsidian-periodic-notes
> Add Periodic Notes plugin

- community-plugins.json
This PR is a continuation of https://github.com/obsidianmd/obsidian-releases/pull/155.
> Add Various Complements

- community-plugins.json
New plugin for tracking daily word count
> Adding daily stats plugin

- community-plugins.json
See: https://github.com/jplattel/open-note-to-window-title :)
> Add the current open note to the window title

- community-css-themes.json
- community-themes.json
I'd like to add my theme to the community themes.
> Add ITS Theme

- community-plugins.json
This plugin allows you to encrypt portions of your notes allowing you to store sensitive details along with other information.
> Add Meld Encrypt plugin

- community-plugins.json
- Open (and edit) CSV files right from Obsidian!
- Auto-saving
- Per-file setting for including headers (persisted in local storage)
- Markdown editing an preview for each individual cell (internal links aren't working correctly, yet)
- Sort the data by clicking on a column name
- Filter by column values
- Freeze columns
- Insert new columns/rows
> Initial release of csv-obsidian!

- community-plugins.json
A plugin to export Markdown notes to Mochi cards
> mochi cards exporter plugin

- community-plugins.json
Let's see how many things I am doing wrong.
> Submit `obsidian-chessboard`

- community-plugins.json
https://github.com/pjeby/pane-relief
> Add "Pane Relief" plugin

- community-plugins.json
https://www.github.com/ryanjamurphy/DEVONlink-obsidian
> Add the DEVONlink plugin

- community-css-themes.json
https://github.com/hungsu/vileplume-obsidian
> Add Vileplume to community themes

- community-plugins.json
[alx-plugins/table-extended](https://github.com/alx-plugins/table-extended)
> Add table-extended

- community-plugins.json
https://github.com/st3v3nmw/obsidian-spaced-repetition
> Add Spaced Repetition Plugin

- community-plugins.json
https://github.com/mgmeyers/obsidian-kanban
> Adds obsidian-kanban

- community-plugins.json
https://github.com/tgrosinger/ledger-obsidian
- Also tested on Android
> Add tgrosinger/ledger-obsidian

- community-plugins.json
This PR is simply updating the description of an existing plugin ([obsidian-kindle-plugin][1]) in the community store.
[1]: https://github.com/hadynz/obsidian-kindle-plugin
> Update obsidian-kindle-plugin description

- community-css-themes.json
> Remove removed 'clean-theme' and fix Solarized screenshot path.

- community-css-themes.json
https://github.com/izumin5210/obsidian-iceberg
> Add theme Iceberg

- community-plugins.json
Goodbye old friend. Now your watch has ended...
> Remove swipe-navigation plugin

- community-plugins.json
https://github.com/OfficerHalf/obsidian-collapse-all
> Add obsidian-collapse-all plugin

- community-css-themes.json
https://github.com/bencodezen/obsidian-night-owl-theme
> Add Night Owl theme

- community-css-themes.json
An Obsidian.md theme with a stark contrast between dark mode and light mode, much like the Yin and Yang symbol ☯️.
https://github.com/chetachiezikeuzor/Yin-and-Yang-Theme
> Add Yin and Yang Theme

- community-css-themes.json
(https://github.com/shaggyfeng/obsidian-Golden-Topaz-theme)
> Add Golden Topaz theme

- community-css-themes.json
https://github.com/eleanorkonik/-palatinate
- [!] If you're not using the `master` branch (legacy), please indicate
I'm using main. 
> Add Palatinate Theme

- community-plugins.json
https://github.com/ozntel/file-tree-alternative
> File Tree Alternative Plugin

- community-plugins.json
https://github.com/SkepticMystic/adjacency-matrix-maker
- Only on Windows
> Submit adjacency-matrix-maker

- community-css-themes.json
[Github](https://github.com/Wittionary/mammoth-obsidian-theme)
- [x ] Your repo contains all required files (please *do not* add them to our `obsidian-releases` repo)
- [x ] `obsidian.css`
- [ x] The screenshot file you pointed to
- [ x] You have indicated which modes (dark, light, or both) are compatible with your theme
- [ x] If you're not using the `master` branch (legacy), please indicate
> Added 'Mammoth' theme

- community-css-themes.json
> Fix Darkyan theme

- community-plugins.json
https://github.com/George-debug/obsidian-timeline
> Add Timeline to community plugins

- community-css-themes.json
https://github.com/MrGlitchByte/obsidian_everforest
> Added Everforest.css to community list

- community-css-themes.json
https://github.com/ZaherAlMajed/Illusion-Theme.md
> Adding Illusion Theme

- community-plugins.json
https://github.com/valentine195/obsidian-leaflet-plugin
> Update Obsidian Leaflet description

- community-css-themes.json
https://github.com/tylernguyen/obsidian-horizon
> Add Horizon Theme

- community-css-themes.json
- [ x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
- [x ] `obsidian.css`
- [x ] The screenshot file
- [x ] I have indicated which modes (dark, light, or both) are compatible with my theme
- [ x] I have added a license in the LICENSE file
- [x ] If my repo is not using the `master` branch (legacy), please indicate
- [x ] I have tested this on Windows, macOS, and Linux _(if applicable)_
> Update community-css-themes.json Add Tokyo Night Theme

- community-plugins.json
https://github.com/Creling/obsidian-image-uploader
- tested on Windows
> Add obsidian-image-uploader

- community-plugins.json
https://github.com/kurakart/garble-text
> add garble-text plugin

- community-plugins.json
(made edit to plugin ID)
Link to my plugin: https://github.com/chetachiezikeuzor/cMenu-Plugin
> Add cMenu Plugin

- community-css-themes.json
Link to my theme:  https://github.com/bennyxguo/Obsidian-Obsidianite
- [x ] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo)
- [x ] `obsidian.css`
- [x ] The screenshot file
- [x ] I have indicated which modes (dark, light, or both) are compatible with my theme
- [x ] I have added a license in the LICENSE file
- [x ] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.
> Updated Obsidianite theme repo url and author name.

- community-css-themes.json
Link to my theme: https://github.com/kinmury/GoldenCoffeeTheme
> Add Golden Coffee Theme

- community-plugins.json
Link to my plugin: https://github.com/OwnJoke/obsidian-budget-wysiwyg
> Add Budget WYSIWYG

- community-plugins.json
Link to my plugin: https://github.com/readwiseio/obsidian-readwise/
> Add Readwise Official plugin

- community-plugins.json
https://github.com/phibr0/obsidian-customizable-sidebar
> Add the Customizable Sidebar Plugin

- community-css-themes.json
Link to my theme: https://github.com/Chrismettal/Obsidian-Behave-dark
> Add "Behave dark" theme

- community-plugins.json
Link to my plugin: https://github.com/mcndt/obsidian-toggl-integration
> Add obsidian-toggl-integration

- community-plugins.json
Link to my plugin: https://github.com/phibr0/obsidian-macros
> Add Macro Plugin

- community-css-themes.json
Obsidian Windows 98 Edition
Link to my theme: https://github.com/SMUsamaShah/Obsidian-Win98-Edition
> Windows 98 UI Makeover

- community-plugins.json
This  is a simple update to the name of the plugin. Thank you
> Updating plugin name

- community-plugins.json
Link to my plugin: https://github.com/platers/obsidian-linter
> Add obsidian-linter plugin

- community-css-themes.json
Link to my theme: https://github.com/chrisgrieser/shimmering-focus
> Added Shimmering Focus Theme

- community-plugins.json
This plugin provides customization options for CodeMirror 5 such as:
- Consistent syntax highlighting between editor & preview
- Fully customizable syntax highlighting themes
- Dynamic cursor height
- A new selection style that avoids the pitfalls of the default CM selection
- Maintain the active-line class on selection even when selecting multiple lines or using multiple cursors
Link to my plugin: https://github.com/nothingislost/obsidian-codemirror-options
> Add CodeMirror Options Plugin

- community-plugins.json
https://github.com/zapthedingbat/drawio-obsidian
> Add drawio-obsidian plugin

- community-plugins.json
Link to my plugin: https://github.com/yuanotes/obsidian-vim-im-switch-plugin
> feat: add plugin obsidian-vim-im-switch-plugin

- community-plugins.json
Link to my plugin: https://github.com/Dyldog/luhman-obsidian-plugin
> Add Luhman plugin

- community-plugins.json
Link to my plugin: https://github.com/elias-sundqvist/obsidian-annotator
> Add Annotator Plugin

- community-plugins.json
Link to my plugin: https://github.com/samlewis0602/obsidian-custom-js
> Add customJS plugin

- community-plugins.json
Link to my plugin: https://github.com/ShockThunder/RandomStructuralDiary
Release Checklist
> Add random structural diary plugin

- community-plugins.json
Link to my plugin: https://github.com/TfTHacker/obsidian42-jump-to-date
> Obsidian42 - Jump-to-Date

- community-plugins.json
Link to my plugin: https://github.com/FlorianWoelki/obsidian-icon-folder
> Add obsidian-icon-folder

- community-plugins.json
Link to my plugin: https://github.com/skipadu/obsidian-ghost-fade-focus
> Add ghost-fade-focus plugin.

- community-plugins.json
Link to my plugin: https://github.com/tillahoffmann/obsidian-jupyter
> Add jupyter plugin.

- community-plugins.json
The new name and description make it easier to understand the purpose of this plugin.
> Update obsidian-file-link name and description

- .github/PULL_REQUEST_TEMPLATE/theme.md
- community-css-themes.json
Link to my theme:  https://github.com/lazercaveman/obsidian-firefly-theme
> added firefly theme

- community-plugins.json
Changing the description of the plugin
> Image in Editor Description

- community-plugins.json
I recently changed my GitHub username, and so am updating repository paths here.
> Updated repository paths

- community-plugins.json
https://github.com/egradman/scales-chords
> Add "Scales and Chords" plugin

- community-plugins.json
This is a hotfix on the repo name.
> hotfix for the repo path

- community-plugins.json
Link to my plugin: https://github.com/kometenstaub/metadata-extractor
> add metadata extractor

- community-plugins.json
This is my first obsidian plugin, I tested it for 5 month in my local obsidian and waited to before releasing. Feel free to give me any feedback !
Link to my plugin: https://github.com/beaussan/update-time-on-edit-obsidian
> Add update-time-on-edit-obsidian plugin

- community-plugins.json
Link to my plugin: https://github.com/kometenstaub/obsidian-linked-data-vocabularies
> add linked data vocabularies

- community-plugins.json
Just a more concise description.
> Change description of Linter plugin

- community-css-themes.json
Link to my theme: https://github.com/zacharyc/purple-owl-theme
> Adding the theme code for purple owl

- community-css-themes.json
Link to my theme: https://github.com/gracejoseph1236/obsidian-emerald
> Add Emerald theme

- community-css-themes.json
Link to my theme: https://github.com/tomzorz/Sodalite
> added Sodalite theme

- community-plugins.json
Link to my plugin: https://github.com/vrtmrz/obsidian-livesync/
> added obsidian-livesync

- community-css-themes.json
> Slytherin Theme.

- community-css-themes.json
Link to my theme: https://github.com/gracejoseph1236/obsidian-carnelian
> Add Carnelian theme

- community-css-themes.json
Link to my theme: https://github.com/selfire1/obsidian-you-theme
> Add Obsidian You theme

- community-css-themes.json
Link to my theme: https://github.com/ebullient/obsidian-theme-ebullientworks
> ebullientworks -- a new theme

- community-css-themes.json
Link to my theme:  https://github.com/firinael/obsidian-friendly-theme
> Update community-css-themes.json -- add Friendly theme

- community-css-themes.json
Link to my theme: https://github.com/AndreasStandar/Obsidian-Theme---Purple-Aurora
> Add Purple Aurora theme

- community-css-themes.json
Link to my theme: https://github.com/ceciliamay/obsidianmd-theme-primary
> Add Primary theme

- community-css-themes.json
Link to my theme: https://github.com/zcysxy/Obsidian-Terminal-Theme
> Add Obsidian Terminal Theme

- community-css-themes.json
Link to my theme:  https://github.com/Emrie-Candera/Bubble-Space-Theme
> Add Bubble Space Theme

- community-plugins.json
Link to my plugin: https://github.com/timhor/obsidian-sentence-navigator
> Add Sentence Navigator plugin

- community-plugins.json
to sync the description for the plugin
for tidy up the codes and update readme to tell the users about api using
https://github.com/obsidianmd/obsidian-releases/pull/631#issuecomment-968416628 
https://github.com/tim-hub/obsidian-bible-reference.git
> updating an existing Community Plugin description

- community-plugins.json
Link to my plugin: [Customizable Page Header](https://github.com/kometenstaub/customizable-page-header-buttons)
> add customizable page header plugin

- .github/PULL_REQUEST_TEMPLATE/plugin.md
When submitting, I noticed a few minor things with the PR template for plugins that were outdated / could be made more clear.
> PR Template minor improvements

- community-plugins.json
Link to my plugin: https://github.com/OfficerHalf/obsidian-auto-class
> add Auto Class plugin

- community-plugins.json
Update community-plugins.json with cloudinary uploader
Link to my plugin: https://github.com/jordanhandy/obsidian-cloudinary-uploader
- [ x ] My GitHub release contains all required files
- [ x ] `main.js`
- [ x ] `manifest.json`
- [ x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ x ] README clearly describes the plugins purpose and provides clear usage instructions.
- [ x ] I have added a license in the LICENSE file.
> Update community-plugins.json with cloudinary uploader

- community-plugins.json
thanks @joethei ([reference](https://discord.com/channels/686053708261228577/840286264964022302/917711206238797876))
> Fix pluginID of Theme Design Utilities Plugin

- community-css-themes.json
Link to my theme: https://github.com/Thiews/Obsidian-Harmonic
> add Harmonic theme

- community-plugins.json
Link to my plugin: https://github.com/kometenstaub/linked-data-helper
> add linked data helper

- community-plugins.json
Link to my plugin: https://github.com/kometenstaub/obsidian-linked-data-vocabularies
> add linked-data-vocabularies

- community-plugins.json
(I am not submitting a new plugin, but modifying an existing plugin.)
> update description for an already submitted plugin

- community-plugins.json
Link to my plugin: https://github.com/Gru80/obsidian-regex-replace
> added obsidian-regex-replace

- community-css-themes.json
Link to my theme: https://github.com/dlccyes/obsidian-nebula/
> Add Nebula Theme

- community-css-themes.json
Link to my theme: https://github.com/AidanGlickman/obsidian-nord-enhanced
> Add obsidian-nord-enhanced theme

- community-plugins.json
Link to my plugin: https://github.com/QAMichaelPeng/obsidian-graphviz
> Add obsidian-graphviz plugin

- community-css-themes.json
Link to my theme: https://github.com/bLaCkwEw/Dracula-Slim
> Add Dracula Slim theme

- community-plugins.json
Link to my plugin: https://github.com/lanice/obsidian-rant/
> Add Rant-Lang plugin

- community-plugins.json
Link to my plugin: https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys
> Submit "Smarter Markdown Hotkeys" plugin

- community-css-themes.json
Link to my theme: https://github.com/jaysan0/obsidian-sandstorm
> Update community-css-themes.json -- add Sandstorm theme

- community-css-themes.json
On behalf of @nickmilo
Link to my theme: https://github.com/nickmilo/LYT-Mode
> Add LYT Mode theme

- community-plugins.json
The plugin has been renamed to reflect the new custom statblock layouts.
> Update name and description of TTRPG Statblocks

- community-plugins.json
Link to my plugin: https://github.com/nothingislost/obsidian-dynamic-highlights
> Add Dynamic Highlights Plugin

- community-plugins.json
Link to my plugin: https://github.com/ebullient/obsidian-snippetor
> Snippetor: Create and tweak common snippets

- community-plugins.json
Link to my plugin: https://github.com/fyears/weather-fetcher
> add plugin: weather-fetcher

- community-plugins.json
Link to my plugin: https://github.com/ericbiewener/obsidian-lock-screen-plugin
> add lock screen plugin

- community-css-themes.json
> Add Carpe Noctem Theme

- community-css-themes.json
https://github.com/mbeckrich/obsidian
> Add Catppuccin theme

- community-plugins.json
Link to my plugin: https://github.com/ganesshkumar/obsidian-excel-to-markdown-table
> obsidian-excel-to-markdown-table: updating description

- community-css-themes.json
Link to my theme:  https://github.com/learnerfvs/Sparkling-Wisdom-obsidian-theme-
> Add Sparkling Wisdom theme

- community-css-themes.json
Link to my theme: https://github.com/tingmelvin/willemstad-x
> Add Willemstad theme

- community-plugins.json
Link to my plugin: https://github.com/Sanqui/obsidian-persistent-graph
- I'm accessing `Workspace.activeLeaf` directly because I don't know a better way to query for an active graph view.
> Add persistent-graph plugin

- community-plugins.json
Link to my plugin: https://github.com/valentine195/obsidian-settings-search
> Add Settings Search plugin

- community-plugins.json
Link to my plugin: https://github.com/chrisgrieser/obsidian-footnote-indicator
> Add Footnote & Citation Indicator

- community-plugins.json
> Change name of 'JSON Importer' to include CSV

- community-css-themes.json
Link to my theme: https://github.com/caro401/royal-velvet
> Add Royal Velvet theme

- community-plugins.json
> Add big calendar

- .github/workflows/plugin-stat.yml
- update-stats.js
@liamcain @argenos If you have time to give some advice!
Goal of the workflow is to update plugin stats and commit back to the repo every day with a nodejs script.
> GitHub action for updating plugin stats

- community-plugins.json
> Change plugin mantainer's name to `Boninall`

- community-plugins.json
I updated the description of the plugin.
> Update File Cleaner description

- community-plugins.json
The repo was moved to an organization
> change repo of an submitted plugin remotely-save

- community-css-themes.json
Repo URL
Link to my theme: https://github.com/sahilpatel09/Aqua-obsidian
Theme checklist:
If my repo is not using the master branch, please indicate in community-themes.json with "branch": "main".
> Add Aqua theme

- community-plugins.json
> Update name of Image Window plugin

- community-plugins.json
Link to my plugin: https://github.com/mgmeyers/obsidian-zotero-desktop-connector
> Adds Zotero Desktop Connector Plugin

- community-plugins.json
The plugin is dead, long live the plugin!
> Remove intentation guides plugin

- community-css-themes.json
pointed out by @claremacrae:
https://discord.com/channels/686053708261228577/931552763467411487/960286278102970389
> Remove Illusion Theme since repo unavailable

- community-css-themes.json
https://github.com/xRyul/ObsidianMD_Dracula_x_LYT
- [ ✔] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [✔] `obsidian.css`
- [✔ ] The screenshot file.
- [✔ ] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [ ✔] I have added a license in the LICENSE file.
- [✔ ] My project respects and is compatible with the original license of any code from other themes that I'm using.
- [✔ ] If my repo is not using the `master` branch, please indicate in `community-themes.json` with `"branch": "main"`.
> Add Dracula + LYT theme

- community-plugins.json
I hope this makes it a bit easier for people to find this plugin.
> Update description of Completr

- community-css-themes.json
[Everblush](https://github.com/Everblush) Everblush is an Independent Theme and Dark theme made for productive work experience.
> Adding Everblush Theme

- community-css-themes.json
https://github.com/aitaDev/Violet-Evening-for-Obsidian
> Add aitaDev's Theme

- .github/workflows/validate-plugin-entry.yml
This is an updated version of #608 which should hopefully fix the permission issues we've seen in testing.
> feat: Add plugin entry validation

- community-css-themes.json
https://github.com/roberts-code/obsidian-theme-modern-dark
> Add Modern Dark theme

- community-css-themes.json
Link to my theme:  https://github.com/learnerfvs/WiseLight
> Add WiseLight Theme

- community-plugins.json
Migrating repo name, since the given one seems to not allow downloading.
> migrating repo

- community-css-themes.json
Link to my theme: https://github.com/MajorEnkidu/red-solitude-obsidian-theme
> Add Red Solitude theme

- community-css-themes.json
Link to my theme: https://github.com/mulfok/obsidian-viridian
> Add Viridian theme

- community-css-themes.json
> Add Kanagawa Theme

- community-css-themes.json
Link to my theme: https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow
> Add Mado Miniflow Theme

- community-plugins.json
I renamed my account, so to avoid GitHub's redirection I modified entry
> Change author and link of Local Quotes

- community-plugins.json
Just wanted to update the repository (link) of the obsidian-markbase plugin.
> Update repo (link) of obsidian-markbase

- community-plugins.json
I changed my github userid for personal reasons, so I will also modify the plugin link.
- Heading Shifter : https://github.com/obsidianmd/obsidian-releases/pull/1090
> Change usedid(url) `k4a-dev` to `k4a-l`

- community-plugins.json
[https://github.com/9r0x/obsidian-dashing-cursor](https://github.com/9r0x/obsidian-dashing-cursor)
> Dashing cursor plugin

- community-plugins.json
Link to my plugin: https://github.com/artisticat1/obsidian-tikzjax
> add Obsidian TikZJax

- community-plugins.json
Link to my plugin: https://github.com/Ellpeck/ObsidianSimpleTimeTracker
> Add Super Simple Time Tracker plugin

- community-plugins.json
> Remove embedded note title plugin

- community-plugins.json
This PR updates the description of Latex Suite to help make it more discoverable (after requests from users)
> update description of Latex Suite

- community-css-themes.json
GitHub theme now has light mode support
> Update GitHub theme

- community-css-themes.json
https://github.com/hydescarf/Obsidian-Theme-Mado-11
https://github.com/hydescarf/Obsidian-Theme-Mado-Miniflow
> Update both Mado 11 & Mado Miniflow themes

- community-plugins.json
Changes Made:
- Updated Linter plugin description which allows for the Linter plugin to be more searchable for those looking for the functionality that the Linter provides.
Link to my plugin: https://github.com/platers/obsidian-linter
Please let me know if I need to change the format of this or go ahead and add some more information for you guys.
> Update Linter Plugin Description

- community-css-themes.json
Link to my theme: https://github.com/zamsyt/obsidian-ion
> Add "ion" theme

- community-css-themes.json
Link to my theme: https://github.com/efemkay/obsidian-listive-theme
> Add Listive theme to repo

- community-css-themes.json
Link to my theme: https://github.com/dragonwocky/obsidian-material-ocean
> Add Material Ocean theme

- community-css-themes.json
Link to my theme:  https://github.com/MajorEnkidu/red-solitude-obsidian-theme
> Migrated my theme "Red Solitude" to obsidian version 1.x.x

- community-plugins.json
Link to my plugin: https://github.com/scambier/obsidian-omnisearch
> Update the description for Omnisearch

- community-plugins.json
Link to my plugin: https://github.com/AlexW00/obsidian-3d-graph
> Add "3D Graph" plugin

- community-plugins.json
I just wanna change the description a little bit, as the plugin now has more customization features
> Plugin description changes

- community-plugins.json
Link to my plugin: [OpenGate](https://github.com/nguyenvanduocit/obisdian-open-gate)
> Add plugin OpenGate

- community-plugins.json
added donation url, updated description and author name
> Add donation url for Todoist Completed Tasks plugin + some changes

- community-plugins.json
Link to my plugin: https://github.com/ryangomba/obsidian-todo-sort
> Add "Todo sort" plugin

- community-plugins.json
Link to my plugin: https://github.com/lhansford/obsidian-checklist-reset
> Add Checklist Reset plugin

- community-css-themes.json
> Remove California Coast theme

- community-css-themes.json
Link to my theme: https://github.com/zalenza/Abecedarium-theme
> Add Abecedarium theme

- community-css-themes.json
https://github.com/AnubisNekhet/AnuPpuccin
> Add AnuPpuccin theme

- community-plugins.json
Link to my plugin: https://github.com/slpbx/obsidian-plugin
> New plugin: Hints Flow

- community-css-themes.json
Change name/id Shiba Uni to Shiba Inu.
> Shiba Inu Theme 

- community-plugins.json
Update of `ava` plugin name and description
> fix: update ava description

- community-css-themes.json
Link to my theme: https://github.com/Bluemoondragon07/chime-theme/tree/main
> Add 🔔 Chime Theme

- community-plugins.json
> chore: update plugin description

- community-css-themes.json
Link to my theme: https://github.com/clbn/dracula-gemini
> Add Dracula Gemini theme

- community-css-themes.json
Link to my theme: https://github.com/minheeyoon/Dawn/tree/main
> Add Dawn Theme

- community-css-themes.json
Link to my theme: https://github.com/NicolasGHS/Rezin-theme
> Add Rezin theme

- community-css-themes.json
I had a typo and it couldn't be downloaded
Link to my theme: https://github.com/NicolasGHS/Rezin-theme
> Updated Rezin name

- community-plugins.json
Link to my plugin: https://github.com/jjmaldonis/obsidian-audio-notes
> Update description for Obsidian Audio Notes

- community-plugins.json
Link to my plugin: https://github.com/wei2912/obsidian-latex
> Update community-plugins.json - Update Extended MathJax repo

- community-plugins.json
> TTRPG Statblocks -> Fantasy Statblocks

- community-css-themes.json
Dekurai theme
https://github.com/sergey900553/obsidian_dekurai_theme
> Add Dekurai theme

- community-css-themes.json
Link to my theme:  https://github.com/mProjectsCode/obsidian-lemons-theme
> Add Lemons Theme

- community-plugins.json
Link to my plugin: https://github.com/omnivore-app/obsidian-omnivore
> Add Omnivore plugin

- community-plugins.json
> Update surfing information

- community-css-themes.json
Link to my theme: https://github.com/subframe7536/obsidian-theme-maple
> Add Maple Theme

- community-css-themes.json
[Relevant commit](https://github.com/dlccyes/obsidian-nebula/commit/dbbf8891287e12416f6059f0e61355fd3d48a3e4)
> Update Nebula theme: comply with 1.0 and remove legacy label

- community-plugins.json
So people searching for plugins interacting with starred files will find the plugin. 
Reference: https://discord.com/channels/686053708261228577/714234422379151400/1079863812678766683
> Grappling Hook Description: Added reference to starred files

- community-css-themes.json
Updated the screenshot image and added the light mode
> Added Aura Theme Light Mode

- community-css-themes.json
> Add the theme "Elegance"

- community-css-themes.json
Link to my theme: https://github.com/tcmmichaelb139/obsidian-tokyonight
> Add Tokyo Night Theme

- community-plugins.json
Updating the description for the `GPT` plugin to be more descriptive.
> Update GPT plugin description

- community-plugins.json
This is to reflect the new features added since the first release.
Link to my plugin: https://github.com/wenlzhang/obsidian-task-marker
> Update Task Marker descriptions

- community-css-themes.json
Link to my theme: https://github.com/mrowa44/obsidian-ia-writer
> Add iA Writer theme

- community-plugins.json
- [x ]  macOS
- [x ]  Linux
- [x ]  iOS _(if applicable)_
- [x ] `styles.css` _(optional)_
- [x ] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common …
> close similar tabs: more explicative description

- community-plugins.json
The updated description better reflects the feature set and technology used.
Thank you,
Brian
> Updating description of Smart Connections

- community-css-themes.json
Link to my theme: https://github.com/FireIsGood/obsidian-everforest-enchanted
> Add Everforest Enchanted theme

- community-plugins.json
Modify the plugin description shown in the plugin community
> Modify description

- community-plugins.json
Link to my plugin: https://github.com/kuchejak/obsidian-bible-linker-plugin
> Update Bible-linker plugin description

- community-css-themes.json
> Add Sparkling Night

- community-plugins.json
Change the desc of float-search to other desc
> doc: update plugin desc

- community-plugins.json
- [ x]  macOS
- [ x]  Linux
- [ x]  iOS _(if applicable)_
- [ x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common …
> updated description after adding more options

- community-css-themes.json
Link to my theme: https://github.com/Bluemoondragon07/Obsidian-Serenity
> Add Serenity Theme

- community-plugins.json
- [ x]  Windows
- [x ]  macOS
- [x ]  Linux
- [x ]  iOS _(if applicable)_
- [x ] `styles.css` _(optional)_
- [ x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common …
> description edited

- community-plugins.json
Link to my plugin: https://github.com/Vinzent03/find-unlinked-files
> rename plugin find-unlinked-files

- community-plugins.json
Homepage's feature set has massively expanded since I initially submitted it, so update its description to reflect that. Also, my original description had a typo.
> Update Homepage description

- community-plugins.json
- [x ]  macOS
- [ x]  Linux
- [x ]  iOS _(if applicable)_
- [x ] `styles.css` _(optional)_
- [x ] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common …
> vault-name-status-bar plugin

- community-plugins.json
> Move Javalent plugins to new Javalent GH org

- community-plugins.json
A small PR to update plugins description
> chore: update Whisper desc

- community-css-themes.json
https://github.com/whereiswhere/iB-Writer
> Add iB Writer theme

- community-plugins.json
Link to my plugin: https://github.com/turulix/obsidian-folder-index
> Updating Plugin Description for obsidian-folder-index

- community-plugins.json
Link to my plugin: https://github.com/rizerphe/obsidian-companion
> Update companion description

- community-css-themes.json
Link to my theme: https://github.com/oqipoDev/Buena-Vista-Theme
> Add Buena Vista Theme

- community-css-themes.json
Link to my theme: https://github.com/Thiews/obsidian-simplicity
> add "simplicity" theme

- community-css-themes.json
Link to my theme: https://github.com/thegixo/YueObsidian
> Add Yue Theme

- community-css-themes.json
https://github.com/sq1000000/NeuBorder
> The workflow validation thing might have to be reset. I accidentally didn't upload any contents to `theme.css` and `manifest.json`, which broke it. This should be fixed now.
> Add NeuBorder Theme

- community-css-themes.json
Simple Google-inspired theme.
Link to my theme: https://github.com/Bluemoondragon07/Obsidian-Bolt
> Add Obsidian Bolt theme

- community-css-themes.json
Link to my theme: https://github.com/Bluemoondragon07/Obsidian-Origin
> Add Origin Theme

- community-css-themes.json
Link to my theme: https://github.com/zaklezaja/obsidian-oozy
> Add Oozy theme

- community-plugins.json
The khoj project is being moved into the khoj-ai organization. 
This PR is for updating the URL from which to fetch the Khoj Obsidian plugin
Link to my plugin: https://github.com/debanjum/khoj
> Update Khoj Plugin URL and Description

- community-plugins.json
> Add blur plugin

- community-plugins.json
Link to my plugin: https://github.com/hamsterbase/obsidian-hamsterbase
> Add plugin:  hamsterbase

- community-plugins.json
> Update plugin description

- community-plugins.json
Link to my plugin: https://github.com/seethroughdev/obsidian-recipe-grabber
> add "recipe-grabber" plugin

- community-css-themes.json
Link to my theme : https://github.com/mfdev-coder/obsidian-feather
> Add Feather Theme

- community-plugins.json
Link to my plugin: https://github.com/exoascension/vault-chat
- [n/a]  Android _(if applicable)_
- [n/a]  iOS _(if applicable)_
> Add Vault Chat plugin

- community-plugins.json
Just updated the name to reflect the fact that the plugin supports GPT-3 and now GPT-4.
Link to my plugin: https://github.com/micahke/obsidian-gpt3-notes
> Updated obsidian-gpt3-notes plugin info

- community-plugins.json
I have rebranded again to DataLoom. This one is permanent :)
https://github.com/trey-wallis/obsidian-dataloom
> Rename to DataLoom

- community-css-themes.json
> Add Comfort Dark theme

- community-plugins.json
Just need a better plugin description with all the new features :)
> Better plugin description

- community-plugins.json
I made some changes to my username, so repository changed its reference too.
> Update github repo for local-quotes

- community-css-themes.json
Link to my theme: [Neo theme](https://github.com/lab-do/obsidian-neo)
> Add Neo theme

- community-css-themes.json
Ad Legacy Flag to existing theme
> Add Legacy flag for Obsidian You

- community-css-themes.json
> Update Cardstock to non-legacy

- community-plugins.json
Link to my plugin: https://github.com/mgmeyers/obsidian-easy-bake
> Add Easy Bake plugin

- community-plugins.json
> Update Colored Tags plugin info

- community-plugins.json
Add Nested tags graph plugin
Link to my plugin: https://github.com/drPilman/obsidian-graph-nested-tags
> Add Nested tags graph plugin

- community-css-themes.json
Link to my theme: https://github.com/fatiger92/obsidian_venom_theme
> Add Venom theme

- community-css-themes.json
Link to my theme: https://github.com/rmvdesign/autotape-theme
> Add Autotape theme

- community-css-themes.json
Correct my screenshot file name
> Update Nebula theme

- community-plugins.json
Link to my plugin: https://github.com/dbrockman/obsidian-change-case
> Add Change Case Plugin

- community-css-themes.json
Link to my theme: https://github.com/benf2004/Obsidian-LaTeX-Theme/
> Add theme LaTeX

- community-css-themes.json
Link to my theme: <https://github.com/dbarenholz/halcyon-obsidian>
> Add theme halcyon

- community-css-themes.json
Link to my theme: https://github.com/GuiMar10/monochroYOU
Ready to go 🥳
> Add theme monochroYOU

- community-css-themes.json
Link to my theme: https://github.com/kepano/flexoki-obsidian
> Add theme Flexoki

- community-plugins.json
> Update Checkbox Reorder Plugin

- community-plugins.json
Update the description for "Share Note" plugin.
> Update description for Share Note plugin

- community-css-themes.json
https://github.com/prradox/obsidian-releases
https://github.com/prradox/green-nightmare
> Add theme: Green Nightmare

- community-css-themes.json
Link to my theme: https://www.github.com/GeorgeAzma/Transient
> Add theme: Transient

- community-css-themes.json
https://github.com/isaacfreeman/kakano-obsidian-theme
> Add theme: Kakano

- community-plugins.json
As the title says, I'm just updating the description string for my plugin: Obligator.
I didn't notice it updating when changing the description in my manifest, so I figured this is how to update the description in the browser?
Thank you.
> Update the description string for Obligator

- community-css-themes.json
https://github.com/EddieTheEd/Prussian-Blue
> Add theme: Prussian Blue

- community-plugins.json
Link to my plugin: https://github.com/MrAnyx/obsidian-note-batcher
> Add plugin: Note Batcher

- community-css-themes.json
Add Heboric theme
Link to my theme: https://github.com/nhrrs/heboric-obsidian
> Add theme: Heboric

- community-plugins.json
> Add plugin: Show Whitespace

- community-plugins.json
Link to my plugin: https://github.com/cloud-atlas-ai/obsidian-ics
> Move ICS to its new home

- community-css-themes.json
**Type:** [Community Theme](?template=theme.md)
**Repo URL:** https://github.com/vhbelvadi/obsidian-carbon
**Theme checklist**
> * [x]  My repo contains all required files (please _do not_ add them to this `obsidian-releases` repo).
>   
>   * [x]  `theme.css`
>   * [x]  The screenshot file (recommended size is 512px by 288px for fast loading).
> * [x]  I have indicated which modes (dark, light, or both) are compatible with my theme.
> * [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
> * [x]  I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
> * [x]  I have added a …
> Add theme: Carbon

- community-css-themes.json
Link to my theme: https://github.com/bitSchleuder/obsidian-monokai-theme
- [x ] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [x ] `theme.css`
- [x ] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [x ] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [ x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [x ] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [x ] I have added a license in the LICENSE file.
- [x ] My project respects and is …
> Add theme: Monokai

- community-plugins.json
Cleaning up plugin descriptions following [description guidelines](https://docs.obsidian.md/Plugins/Releasing/Submission+requirements+for+plugins).
- Add a period at the end of descriptions
- Simplify language
- Remove terms like "in Obsidian" or "this plugin"
> Clean up descriptions

- community-plugins.json
Simplify descriptions by removing terms like "Allows user to"
> More concise descriptions

- community-plugins.json
Hi, with the new name requirements I took the opportunity to also update my plugin's description.
> Update Meta Bind description

- community-plugins.json
added Steam sync feature description since it was added recently.
https://github.com/CMorooney/obsidian-game-search-plugin
> updates description for Game Search plugin

- community-css-themes.json
Link to my theme: https://github.com/rivea0/obsidian-prime
> Add theme: Prime

- community-plugins.json
Updated the name of my plugin, Share to flomo
> Update plugin name 

- community-css-themes.json
Link to my theme: [Improved Potato](https://github.com/DMeurer/improved-potato)
> Add theme: Improved Potato

- community-css-themes.json
Link to my theme: https://github.com/slavamak/obsidian-neovim
> Add theme: Neovim

- community-css-themes.json
new light theme
https://github.com/isax785/obsidian-sparkling-day
> Add theme: Sparkling Day

- community-plugins.json
I transferred the repository to another Github account I own.
> Update plugin: github username change

- community-plugins.json
smart-second-brain plugin moved repo location to and organization for better issue and feature tracking
> Changed smart-second-brain repo location + removed annoying indents

- community-css-themes.json
https://github.com/isax785/obsidian-soloing
> Add theme: Soloing

- community-plugins.json
Hi, I want to rename the Obsidian Memos plugin.
> Rename Plugin - Update community-plugins.json

- community-plugins.json
- [ x]  Windows
- [ x]  macOS
- [ x]  Linux
- [ x]  Android _(if applicable)_
- [ x]  iOS _(if applicable)_
- [ x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [ x] I have …
> Update of my plugins descriptions

- community-css-themes.json
Link to my theme: https://github.com/contrapasso3/Reshi
> Add theme: Reshi

- community-plugins.json
Description to index-checker plugin was updated to highlight Canvas index support added in previous update.
It will be beneficial for users who search for index maintaining plugin that supports Canvas files as indexes.
> Update index-checker plugin description

- community-plugins.json
Link to my plugin: https://github.com/mmiksaa/obsidian-protected-note
> description update

- community-css-themes.json
Link to my theme: https://github.com/clearlysid/apex
> Add theme: Apex

- community-css-themes.json
https://github.com/eldritch-theme/eldritch-obsidian
- [ X] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [ X] `manifest.json`
- [X ] `theme.css`
- [X ] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [X ] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [X ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [X ] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [X ] I have added a license in the LICENSE file.
- [X ] My project respects and is …
> Add theme: Eldritch

- community-plugins.json
> Update lifeos plugin repo

- community-plugins.json
Link to my plugin: https://github.com/Wapply/obsidian-autoplay-and-loop
> Add plugin: Autoplay & Loop

- community-css-themes.json
Link to my theme:  https://github.com/AwesomeDog/obsidian-soothe
> Add theme: Soothe

- community-plugins.json
Submitting note-toolbar for approval.
Link to my plugin: https://github.com/chrisgurney/obsidian-note-toolbar/
> Add plugin: Note Toolbar

- community-plugins.json
I changed the author name. Apologies for frequent changes.
> Update plugin author name: formatto-format

- community-plugins.json
Fixed a typo in pull request #3341.
> Fix name typo: formatto-format

- community-plugins.json
Link to my plugin: https://github.com/cloud-atlas-ai/obsidian-client/
> Add plugin: Cloud Atlas

- community-plugins.json
Link to my plugin: https://github.com/inhumantsar/slurp
> Add plugin: Slurp

- community-plugins.json
Link to my plugin: https://github.com/ryanhalliday/obsidian-reverse-prompter/
> Add plugin: Reverse Prompter

- community-plugins.json
Link to my plugin: https://github.com/Benature/obsidian-automation
> Add plugin: Automation

- community-plugins.json
Link to my plugin: https://github.com/Acylation/obsidian-click-clack
> Add plugin: Click Clack

- community-plugins.json
Link to my plugin: https://github.com/dromse/obsidian-grind-manager
> Add plugin: Grind Manager

- community-plugins.json
Link to my plugin: https://github.com/grover572/obsidian-Dictionary-translator
> Add plugin: Dictionary translator

- community-plugins.json
Link to my plugin: https://github.com/zhouhua/obsidian-vconsole
> Add plugin: vConsole

- community-plugins.json
Link to my plugin: https://github.com/cloud-atlas-ai/obsidian-am
> Add plugin: Amazing Marvin Integration

- community-plugins.json
Link to my plugin: https://github.com/lorens-osman-dev/cluster
> Add plugin: Cluster

- community-plugins.json
Link to my plugin: https://github.com/aaachen/IMDb-Obsidian/tree/main
> Add plugin: IMDb

- community-plugins.json
Please update the plugin description for **Gistr** as the functionality has changed since it was originally submitted.
> Update plugin: Gistr

- community-plugins.json
Link to my plugin: https://github.com/Erl-koenig/obsidian-dailyPrompt
> Add plugin: Daily Prompt

- community-plugins.json
Link to my plugin: https://github.com/RavenHogWarts/obsidian-custom-sidebar-icons
> Add plugin: Custom Sidebar Icons

- community-plugins.json
Link to my plugin: https://github.com/muratagawa/update-time-updater
> Add plugin: Update Time Updater

- community-plugins.json
Link to my plugin: https://github.com/taichimaeda/markpilot
> Add plugin: Markpilot

- community-css-themes.json
Link to my theme:  https://github.com/eliz-abeth/sandover
- [ x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [ x] `theme.css`
- [ x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [ x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [ x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [ x] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
> Add theme: Sandover

- community-css-themes.json
Link to my theme: [https://github.com/Ch0live/dunite](https://github.com/Ch0live/dunite)
> Add theme: Dunite

- community-plugins.json
> Add plugin: Hierarchical Outgoing Links

- community-plugins.json
Link to my plugin: https://github.com/andrewheekin/obsidian-create-note-list
> Add plugin: Create List of Notes

- community-plugins.json
Link to my plugin: https://github.com/fontsource/obsidian-fontsource
> Add plugin: Fontsource

- community-css-themes.json
Link to my theme: https://github.com/loveminimal/obsidian-theme-virgo
> Add theme: Virgo

- community-plugins.json
Link to my plugin: https://github.com/yy4382/obsidian-static-site-export
> Add plugin: Static Site MD Exporter

- community-plugins.json
Link to my plugin: https://github.com/Lisandra-dev/obsidian-enhanced-copy
> Add plugin: Enhanced Copy

- community-plugins.json
Link to my plugin: https://github.com/daledesilva/obsidian_ink
> Add plugin: Ink

- community-plugins.json
Link to my plugin: https://github.com/TfTHacker/obsidian-ai-templater
> Add plugin: AI for Templater

- community-plugins.json
Link to my plugin: https://github.com/a-nano-dust/dust-obsidian-calendar
> Add plugin: Dust Calendar

- community-plugins.json
> chore: Update plugin ownership, author name and description.

- community-plugins.json
https://github.com/privet-kitty/obsidian-blogger/
> Add plugin: Google Blogger

- community-plugins.json
Link to my plugin: https://github.com/CinquinAndy/notes-to-strapi-export-article-ai
( follow this ticket : https://github.com/obsidianmd/obsidian-releases/pull/3281 ) 
I recreate the PR because the bot doesn't detect correctly my repository & release, (because i changed the name of these)
> Add plugin: Strapi Exporter AI

- community-plugins.json
Link to my plugin: https://github.com/OneCalmCloud/obsidian-mindmap
> Add plugin: Mindmap

- community-plugins.json
> Add plugin: Outline Converter

- community-plugins.json
Link to my plugin: https://github.com/dgudim/obsidian-universal-renderer
> Add plugin: Universal renderer

- community-plugins.json
Link to my plugin: https://github.com/sfr0xyz/obsidian-bitcoin-block-stamp
> Add plugin: Bitcoin Block Stamp

- community-plugins.json
Link to my plugin: https://github.com/ebullient/obsidian-slides-extended
> Add plugin: Slides Extended

- community-plugins.json
Link to my plugin: https://github.com/Xmoncoco/my_anime_list_text_exporter
> Add plugin: my anime list text exporter

- community-plugins.json
Link to my plugin: https://github.com/yamfeel/coco-askai
This is a closed-source Obsidian plugin.
Provide a simplified multi-window AI interaction method.
obsidian developer can check the project code.
> Add plugin: CoCo AskAI

- community-plugins.json
https://github.com/GengAd/obsidian-personal-os
> Add plugin: Personal OS

- README.md
- community-plugins.json
Link to my plugin: https://github.com/odayou/task-processing-extension
> Add plugin: TimeSaver

- community-plugins.json
Link to my plugin: https://github.com/stephendolan/obsidian-calendar-event-sync
> Add plugin: Calendar Event Sync

- community-plugins.json
Link to my plugin: https://github.com/KraXen72/obsidian-painter
> Add plugin: Painter

- community-plugins.json
Update the description to better reflect the current state of the plugin
> Update Smart Connections description in community-plugins.json

- community-plugins.json
Link to my plugin: https://github.com/jeetsukumaran/obsidian-bearings
> Update plugin description: Bearings

- community-plugins.json
Link to my plugin: https://github.com/lavaforge/obsidian-lava-vtt-uploader
> Add plugin: Lava VTT Uploader

- community-plugins.json
Link to my plugin: https://github.com/alexandrerbb/obsidian-outline-tasklist-plugin
> Add plugin: Outline to task list

- community-css-themes.json
Link to my theme: https://github.com/humandecoded/Trace-Labs-Obsidian-Theme
- [ x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [ x] `theme.css`
- [ x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [ x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [ x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [ x] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [ x] My project respects and is …
> Add theme: Trace Labs

- community-plugins.json
Link to my plugin: https://github.com/systemsculpt/obsidian-systemsculpt-ai
> Add plugin: SystemSculpt AI

- community-plugins.json
> Add plugin: Simple Citations

- community-plugins.json
Link to my plugin: https://github.com/homu-konamilk/obsidian-custom-new-file-name/tree/main
> Add plugin: Custom new file name

- community-plugins.json
Link to my plugin: https://github.com/Donovan-Ye/obsidian-ai-writer-plugin
> Add plugin: ai-writer

- community-plugins.json
Link to my plugin: https://github.com/AndyReifman/LinkMagic
> Add plugin: LinkMagic

- community-plugins.json
Link to my plugin: https://github.com/o02c/obsidian-tab-navigator/tree/main
> Add plugin: Tab Navigator

- community-plugins.json
In PR #3421 there was a merge error.
This is now resolved in this PR.
Hope it's fine that I make this PR :)
> Fix: Merge error from previously merged PR

- community-plugins.json
Link to my plugin: https://github.com/marcdonald/obsidian-day-one-importer
> Add plugin: Day One Importer

- community-css-themes.json
Link to my theme: [https://github.com/antoKeinanen/obsidian-sanctum-reborn](https://github.com/antoKeinanen/obsidian-sanctum-reborn)
> Add theme: Sanctum reborn

- community-plugins.json
- Update the descriptiton to be closed source.
> Update plugin description: Obsidian-Memos

- community-plugins.json
Link to my plugin: https://github.com/arenasys/obsidian-ai-chat
> Add plugin: AI Chat

- community-plugins.json
Link to my plugin: https://github.com/manimohans/obsidian-local-llm-helper
> Add plugin: Local LLM Helper

- community-plugins.json
Link to my plugin: https://github.com/luhaifeng666/obsidian-text2audio
> Add plugin: Text2Audio

- community-plugins.json
Link to my plugin: https://github.com/geeknees/obsidian-ruby-wasm-plugin
> Add plugin: ruby.wasm

- README.md
- community-plugins.json
Link to my plugin: https://github.com/alincoop/obsidian-tinychart/
> Add plugin: TinyChart

- community-plugins.json
Link to my plugin: https://github.com/yasd251/checkbox-sounds-plugin
- I have tested the plugin on
- My GitHub release contains all required files
> Add plugin: Checkbox Sounds

- community-css-themes.json
Link to my theme: https://github.com/ryanjrman/Spectrum-Blue/tree/master
> Add theme: Spectrum Blue

- community-css-themes.json
Link to my theme: https://github.com/SemiCirkle/Midnight-obsidian-theme
> Add theme: Midnight

- community-css-themes.json
Submitting Theme for review
Link to my theme:
> Add theme: Cobalt Peacock

- community-css-themes.json
Link to my theme: https://github.com/lorens-osman-dev/Lorens-Obsidian-Theme
> Add theme: Lorens

- community-css-themes.json
Link to my theme: https://github.com/NoahBoos/RiftTheme
> Add theme: Rift

- community-plugins.json
Link to my plugin: https://github.com/Kay607/obsidian-canvasblocks
> Add plugin: Canvas Blocks

- community-plugins.json
Link to my plugin: https://github.com/jacobtread/obsidian-timekeep
> Add plugin: Timekeep

- community-plugins.json
https://github.com/ConnorEspino/ObsidianSelectWord
> Add plugin: Select word

- community-plugins.json
Link to my plugin: https://github.com/zigholding/obsidian-notechain-plugin
> Add plugin: Note Chain

- community-plugins.json
Link to my plugin: https://github.com/andrewheekin/obsidian-folder-periodic-notes
> Add plugin: Folder Periodic Notes

- community-plugins.json
Added S3agle plugin
Link to my plugin: https://github.com/turnercore/s3agle
> Add plugin: S3agle

- community-plugins.json
Link to my plugin: [https://github.com/mark-when/obsidian-plugin](https://github.com/mark-when/obsidian-plugin)
> Add plugin: Markwhen

- community-plugins.json
New plugin that enables panning around the canvas using WASD or similar. Desktop only.
Link to my plugin: https://github.com/nathonius/obsidian-canvas-pan
> Add plugin: Canvas Keyboard Pan

- community-plugins.json
Link to my plugin: https://github.com/AdityaKhowalGithub/weekly-review-notes-linker
> Add plugin: Weekly Review notes linker

- community-plugins.json
Link to my plugin: https://github.com/CHex0K/advanced-canvas-filter
> Add plugin: Advanced Сanvas Filter

- community-plugins.json
Link to my plugin: https://github.com/slonoed/obsidian-future-dates
> Add plugin: Future Dates

- community-plugins.json
Link to my plugin: https://github.com/akopdev/obsidian-bibtex-manager
> Add plugin: BibTeX Manager

- community-css-themes.json
Link to my theme:  https://github.com/BlossomTheme/Obsidian
> Add theme: Blossom

- community-plugins.json
Link to my plugin: https://github.com/levi-ivel/MostUsed
> Add plugin: MostUsed

- community-plugins.json
https://github.com/trey-wallis/obsidian-vault-explorer
> Add plugin: Vault Explorer

- community-plugins.json
request to add new plugin - "Cusor Jump"
Link to my plugin: https://github.com/LifeFi/obsidian-jump
> Add plugin: Cursor Jump

- community-plugins.json
Link to my plugin: https://github.com/vkostyanetsky/ObsidianTimesheet
> Add plugin: Timesheet

- community-plugins.json
Link to my plugin: https://github.com/triangular-sneaky/obsidian-list-outline-helper
> Add plugin: List Outline Helper

- community-plugins.json
Link to my plugin: https://github.com/Rooyca/query-json
> Add plugin: Query JSON

- community-plugins.json
Link to my plugin: https://github.com/mysticcoders/voicenotes-sync
> Add plugin: Voicenotes Sync

- community-css-themes.json
https://github.com/bhappen/obsidian-space
> Add theme: Space

- community-plugins.json
Link to my plugin: https://github.com/carnetdethese/obsidian-legifrance-integration
> Add plugin: Légifrance Intégration

- community-plugins.json
Link to my plugin: https://github.com/Pierrad/obsidian-github-copilot/tree/1.0.0
> Add plugin: Github Copilot

- community-plugins.json
Link to my plugin: https://github.com/YoniA/toggle-rtl-obsidian-plugin
> Add plugin: Toggle RTL mode

- community-plugins.json
Link to my plugin: https://github.com/dsebastien/obsidian-update-time
> Add plugin: Update Time

- community-plugins.json
Link to my plugin: https://github.com/alexkurowski/solo-toolkit
> Add plugin: Solo RPG Toolkit

- community-plugins.json
Link to my plugin: https://github.com/moeyua/obsidian-heti
> Add plugin: heti

- community-plugins.json
Link to my plugin: https://github.com/stashpad/obsidian-to-stashpad
> Add plugin: Stashpad Docs

- community-plugins.json
Hi, 
I'm the owner of Solve which has been approved for over 6 months. I was wondering if I'd be able to update the description with the submitted as it better represents the plugin. Is that possible?
> Update Plugin Description: Solve

- community-plugins.json
Rename FROM `Interactivity` TO `Interactivity: Calculations and Scripts`.
> Renamed Interactivity plugin for clarity

- community-plugins.json
I changed back my username from lisandra-dev to Mara-Li, so I changed the url from community.
> [Author] Update author name and URL

- community-plugins.json
Update iCal's description to include proper name of calendar format.
> Minor copy change

- community-plugins.json
I just updated my GitHub username to `decaf-dev`. I have updated the metadata for the 4 plugins that I own and develop. Please let me know if you have any questions.
New url:
https://github.com/decaf-dev
> GitHub username change

- community-plugins.json
Not creating a new plugin, just a simple rename of an existing one.
Will be paired with changes to the repo and a plan to notify users of any breaking changes.
> Rename Reason -> Enzyme

- community-plugins.json
Link to my plugin: https://github.com/nhannht/obsidian-smart-gantt
> Add plugin: Smart Gantt

- community-plugins.json
Link to my plugin: https://github.com/SntTGR/obsidian-tw-task-wiki
> Add plugin: TaskWarrior Task Wiki

- community-plugins.json
Link to my plugin: https://github.com/Tej-Sharma/notes2tweets-obsidian
> Add plugin: Notes 2 Tweets

- community-plugins.json
https://github.com/dominiclet/obsidian-note-definitions
> Add plugin: Note Definitions

- community-css-themes.json
Link to my theme: https://github.com/CyanVoxel/vauxhall-obsidian
> Add theme: Vauxhall

- community-plugins.json
https://github.com/drbap/laser-beam-for-obsidian
> Add plugin: Laser beam

- community-plugins.json
Link to my plugin: https://github.com/tmcw/obsidian-freeform
> Add plugin: Freeform

- community-plugins.json
Link to my plugin: https://github.com/jeetsukumaran/obsidian-focus-tracker
> Add plugin: Focus Tracker

- community-plugins.json
---
Repo URL
---
Link to my plugin: https://github.com/wish5115/obsidian-ii-quicker
Release Checklist
---
> Add plugin: ii

- community-css-themes.json
Link to my theme: https://github.com/nulglyph/Allium/tree/main
> Add theme: Allium

- community-plugins.json
Link to my plugin: https://github.com/n21rl/stablock-sidekick
> Add plugin: Statblock Sidekick

- community-plugins.json
Link to my plugin: https://github.com/udus122/checkbox-time-tracker/tree/main
> Add plugin: Checkbox Time Tracker

- community-plugins.json
https://github.com/MKSherbini/obsidian-noor
> Add plugin: Noor

- community-plugins.json
Link to my plugin: https://github.com/ras0q/obsidian-graph-banner
> Add plugin: Graph Banner

- community-plugins.json
Link to my plugin: https://github.com/RyoJerryYu/obsidian-memos-sync
> Add plugin: Memos Sync

- community-plugins.json
Link to my plugin: https://github.com/Sheeplet1/obsidian-pin-enhancer
-  [x] Windows
-  [x] macOS
-  [x] Linux
-  [ ] Android (_if applicable_)
-  [ ] iOS (_if applicable_)
> Add plugin: Pin Enhancer

- community-plugins.json
This is a closed-source plugin. I will invite you into private repo soon.
Link to my plugin: https://github.com/Quorafind/Obsidian-Templify
> Add plugin: Templify

- community-plugins.json
I've granted access to the full repository source code, and written up a detailed walkthrough for the Obsidian team reviewers. Please let me know if there's anything else required for the review process.
Link to my plugin: https://github.com/jemstelos/ayanite (placeholder)
> Add plugin: Ayanite

- community-plugins.json
https://github.com/Developer-Mike/obsidian-docxer
> Add plugin: Docxer

- community-plugins.json
> Add plugin: The Queue

- community-plugins.json
> Add plugin: Folder by tags distributor

- community-plugins.json
Link to my plugin: https://github.com/zhouhua/obsidian-power-mode
> Add plugin: POWER MODE

- community-plugins.json
Link to my plugin: https://github.com/ahmed3developer/rapid-ai
> Add plugin: Rapid AI

- community-plugins.json
> Add plugin: ClickUp sync

- community-plugins.json
Link to my plugin: https://github.com/xhuajin/obsidian-tabs
> Add plugin: Tabs

- community-css-themes.json
Link to my theme: https://github.com/Elhary/obsidian-Pale
> Add theme: Pale - 淡

- community-plugins.json
Link to my plugin: https://github.com/BambusControl/obsidian-substitutions
> Add plugin: Substitutions

- community-plugins.json
Link to my plugin: https://github.com/taskscape/InfostackerPlugin
> Add plugin: Infostacker Note Publish

- community-plugins.json
Link to my plugin: https://github.com/arumie/obsidian-simple-prompt-plugin
> Add plugin: Simple Prompt

- community-plugins.json
Link to my plugin: https://github.com/Mara-Li/obsidian-explorer-hidder/
> Add plugin: Explorer Hider

- community-plugins.json
Link to my plugin: https://github.com/arumie/obsidian-medium-importer-plugin
> Add plugin: Medium Importer

- community-plugins.json
Link to my plugin: https://github.com/Mossy1022/Smart-Connections-Graph-View
> Add plugin: Smart Connections Visualizer

- community-plugins.json
Link to my plugin: https://github.com/GoodbyeNJN/obsidian-plugin-prettier
> Add plugin: Prettier

- community-plugins.json
> Add plugin: Pinned Notes

- community-plugins.json
Link to my plugin: https://github.com/maybe-hello-world/midi-logger
> Add plugin: MIDI Logger

- community-plugins.json
Link to my plugin: https://github.com/acidghost/obsidian-checklist-progress
> Add plugin: Checklist Progress

- community-css-themes.json
Link to my theme: https://github.com/anareaty/creme-brulee-obsidian-theme
> Add theme: Creme brulee

- community-css-themes.json
Link to my theme: https://github.com/scottgriv/Dark-Castle-Obsidian
> Add theme: Dark Castle

- community-plugins.json
Hi,
I want to make a re-branding of name, description and repo for my plugin `Grind Manager`.
> Update name, description and repo: Grind Manager

- community-plugins.json
**Actually I am updating the description, but it seems that no appropriate template to select.**
Link to my plugin: <https://github.com/remotely-save/remotely-save>
> Update the description of the submitted plugin Remotely Save

- community-css-themes.json
Link to my theme: [RetroNotes](https://github.com/sr-campelo/retronotes)
> Add theme: RetroNotes

- community-plugins.json
Link to my plugin: https://github.com/BWurster/obsidian-ai-expander
> Add plugin: Explain Selection With AI

- community-plugins.json
Link to my plugin: https://github.com/juliavdkris/obsidian-toggle-dark-mode
(edit to trigger recheck, because I misread and didn't add required files as "binaries" in release)
> Add plugin: Toggle Dark Mode

- community-plugins.json
> Add plugin: Plugins Annotations

- community-plugins.json
Link to my plugin: https://github.com/TaylorJadin/close-window-when-empty
> Add plugin: Close Window When Empty

- community-plugins.json
Link to my plugin: https://github.com/TarsLab/obsidian-tars
> Add plugin: Tars

- community-plugins.json
Link to my plugin: https://github.com/chitwan27/lineArrange
> Add plugin: Line Arrange

- community-plugins.json
https://github.com/Quorafind/Obsidian-Search-In-Canvas
> Add plugin: Search In Canvas

- community-plugins.json
Link to my plugin: [Watched Metadata Plugin](https://github.com/NailAhmed/Watched-Metadata.git)
> Add plugin: Watched-Metadata

- community-plugins.json
Link to my plugin: https://github.com/chrskerr/task-list-kanban
> Add plugin: Task List Kanban

- community-plugins.json
- [x ]  Linux
- [x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [x ] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [x ] I have added a license in the LICENSE file.
- [x ] My project …
> Add plugin: Interactive Code Blocks

- community-plugins.json
Submitting a new plugin with the ID "you-and-your-research".
Link to my plugin: https://github.com/neozhang/you-and-your-research
> Add plugin: You and Your Research

- community-plugins.json
Link to my plugin: https://github.com/patrickchiang/obsidian-dialogue-mode
> Add plugin: Dialogue Mode

- community-plugins.json
Link to my plugin: [obsidian-smart-move-text](https://github.com/Ankush-Chander/obsidian-smart-move-text)
> Add plugin: Smart Text Mover

- community-plugins.json
Link to my plugin: https://github.com/jlweston/obsidian-note-proximity-plugin
> Add plugin: Lookalike

- community-plugins.json
> Add plugin: Header Adjuster

- community-plugins.json
Link to my plugin: https://github.com/BjarneRentz/obsidian-gemini-generator
> Add plugin: Gemini Generator

- community-plugins.json
Link to my plugin: https://github.com/Quorafind/Obsidian-Node-Auto-Resize
> Add plugin: Node Auto Resize

- community-css-themes.json
Link to my theme: https://github.com/BossElijah/bossidian
> Add theme: Bossidian

- community-css-themes.json
> Add theme: Evergreen-Shadow

- community-css-themes.json
> Add theme: Velvet-Moon

- community-css-themes.json
> Add theme: Midnight-Fjord

- community-css-themes.json
> Add theme: Mint-Breeze

- community-css-themes.json
> Add theme: Lavender-Mist

- community-css-themes.json
> Add theme: Northern-Sky

- community-plugins.json
Link to my plugin: https://github.com/h-sphere/sql-seal
> Add plugin: SQLSeal

- community-plugins.json
Link to my plugin: https://github.com/jacobtread/obsidian-spoilers
> Add plugin: Spoilers

- community-plugins.json
> Add plugin: doing

- community-plugins.json
> Add plugin: Daily Note Structure

- community-plugins.json
Link to my plugin: https://github.com/name/obsidian-rpg
> Add plugin: RPG Stat Tracker

- community-plugins.json
Link to my plugin: https://github.com/Mossy1022/smart-transcriptions
- [ X] I have tested the plugin on
> Add plugin: Smart Memos

- community-plugins.json
Link to my plugin: https://github.com/AmmarCodes/obsidian-quran-helper-plugin
> Add plugin: Quran Helper

- community-plugins.json
Link to my plugin: https://github.com/chenshutian9610/obsidian-pagescroll-plugin
> Add plugin: Page Scroll

- community-plugins.json
Link to my plugin: <https://github.com/remotely-save/remotely-save>
> Update the description of the submitted plugin (again)

- community-plugins.json
Link to my plugin: [https://github.com/daledesilva/obsidian_ink](https://github.com/daledesilva/obsidian_ink)
> Update to plugin description

- community-css-themes.json
> Add theme: Seamless View

- community-plugins.json
Latest versions have more unique features. It's better to reflect them in the description so the users can find the plugin for their needs easier
> Update description for `Fix Require Modules`

- community-plugins.json
Link to my plugin:  https://github.com/sunbooshi/note-to-mp
> Add plugin: Note to MP

- community-plugins.json
Link to my plugin: https://github.com/jonjampen/obsidian-xournalpp
> Add plugin: Xournal++

- community-plugins.json
Link to my plugin: https://github.com/dsebastien/obsidian-dataview-serializer
> Add plugin: Dataview Serializer

- community-plugins.json
Link to my plugin: https://github.com/Superschnizel/obisdian-fast-text-color
> Add plugin: Fast Text Color

- community-plugins.json
Link to my plugin: https://github.com/taskscape/ObsidianUniqueFileName
> Add plugin: Guid Renamer

- community-plugins.json
Link to my plugin: https://github.com/lighthousedino/obsidian-front-matter-timestamps
> Add plugin: Front Matter Timestamps

- community-plugins.json
Link to my plugin: https://github.com/wholetomy/obsidian-e-daiary
> Add plugin: e-Daiary

- community-plugins.json
Link to my plugin: https://github.com/udus122/dataview-publisher 
> Add plugin: Dataview Publisher

- community-plugins.json
https://github.com/catvatar/Obsidian-NSFW-Plugin
> Add plugin: NSFW filter

- community-plugins.json
> Add plugin: Edit in Neovim

- community-plugins.json
Link to my plugin: https://github.com/jaewonE/checkbox-styling-helper
> Add plugin: Checkbox styling helper

- community-css-themes.json
https://github.com/primary-theme/obsidian
> Add Theme: Primary

- community-plugins.json
Link to my plugin: https://github.com/vschroeter/obsidian-virtual-linker
> Add plugin: Virtual Linker / Glossary

- community-plugins.json
https://github.com/javierarce/arena-manager
> Add plugin: Are.na Manager

- community-plugins.json
Link to my plugin: https://github.com/nicosomb/obsidian-shrink-pinned-tabs
> Add plugin: Shrink pinned tabs

- community-plugins.json
Link to my plugin: https://github.com/HandcartCactus/obsidian-remove-newlines
> Add plugin: Remove Newlines

- community-plugins.json
Link to my plugin: https://github.com/Ankush-Chander/obsidian-entity-linker
> Add plugin: Entity Linker

- community-plugins.json
Link to my plugin: https://github.com/cpbotha/obsidian-ai-chat-as-md
- [-] I have tested the plugin on
> Add plugin: AI Chat as Markdown

- community-plugins.json
- [ X] I have tested the plugin on
- [ X]  Linux
- [ X] `main.js`
- [ X] `manifest.json`
- [ X] `styles.css` _(optional)_
- [X ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ X] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ X] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [ X] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [ X] …
> Add plugin: Sidebar Resizer

- community-plugins.json
Link to my plugin: https://github.com/mnaoumov/obsidian-refresh-preview
> Add plugin: Refresh Preview

- community-css-themes.json
Link to my theme: https://github.com/solm0/Agate
> Add theme: Agate

- community-css-themes.json
Link to my theme: https://github.com/GnRlLeclerc/Vanilla-Theme-Palettes
> Add theme: Vanilla Palettes

- community-plugins.json
Link to my plugin: https://github.com/connorpark24/refresher-plugin
> Add plugin: Notes Refresher

- community-plugins.json
> Add plugin: DocBase (Unofficial)

- community-plugins.json
https://github.com/jvsteiner/obsidian-latex-render
> Add plugin: Latex Render

- community-plugins.json
Link to my plugin: https://github.com/nicoletanyt/obsidian-plugin-graphs
> Add plugin: Plot Vectors and Graphs

- community-plugins.json
Link to my plugin: https://github.com/xhyabunny/nyanbar
> Add plugin: NyanBar

- community-css-themes.json
https://github.com/chenbihao/obsidian-theme-dark-clarity
> Add theme: Dark Clarity

- community-css-themes.json
Link to my theme: https://github.com/exloseur3d/nier-theme/tree/main
> Add theme: Nier

- community-plugins.json
> Add plugin: mpv links

- community-plugins.json
Iron Vault is a TTRPG Virtual Tabletop plugin for the Ironsworn/Starforged family of games.
Link to my plugin: https://github.com/iron-vault-plugin/iron-vault
> Add plugin: Iron Vault

- community-plugins.json
Link to my plugin: [nextcloud-link-fixer](https://github.com/KFreon/nextcloud-link-fixer)
> Add plugin: Nextcloud Link Fixer

- community-css-themes.json
Request review for new theme "Pxld". 
https://github.com/Lina674/Pxld-Obsidian-Theme
> Add theme: Pxld

- community-plugins.json
Link to my plugin: https://github.com/Eloliuyx/everyday-classical-music-plugin
This initial release works for apple macOS.
> Add plugin: Everyday Classical Music

- community-plugins.json
Link to my plugin: https://github.com/Heiss/obsidian-vikunja-plugin/releases
> Add plugin: Vikunja Sync

- community-plugins.json
Link to my plugin: https://github.com/chasebank87/unofficial-fabric-plugin
> Add plugin: Unofficial Fabric Integration

- community-plugins.json
Adding a new plugin!
https://github.com/jcollingj/caret
> Add plugin: Caret

- community-plugins.json
Link to my plugin:https://github.com/xiaotianhu/obsidian-messager
> Add plugin: Messager

- community-plugins.json
> Add plugin: Giphy

- community-plugins.json
> Add plugin: Journal Folder

- community-plugins.json
Link to my plugin: https://github.com/dldisud/obsidian-pia-viewer
> Add plugin: Pia viewer

- community-plugins.json
Link to my plugin: bhavers/obsidian-ca
- [X ] I have tested the plugin on
- [X ]  macOS
- [X ] My GitHub release contains all required files
- [X ] `main.js`
- [X ] `manifest.json`
- [X ] `styles.css` _(optional)_
- [X ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X ] I have added a license in the LICENSE file.
- [X ] My project respects and is …
> Add plugin: Cognitive Architect Sync

- community-plugins.json
Link to my plugin: https://github.com/Swaggeroo/obsidian-ai-image-analyzer
> Add plugin: AI image analyzer

- community-plugins.json
Link to my plugin: https://github.com/gr0grig/obsidian-virt-folder
> Add plugin: VirtFolder

- community-plugins.json
Link to my plugin: https://github.com/imfenghuang/obsidian-magic-move
I have given proper attribution to these other projects in my README.md.
> Add plugin: Magic Move

- community-css-themes.json
> Add theme: Muted-Blue

- community-plugins.json
https://github.com/ichichikin/obsidian-plugin-interactivity
> Updated the description for Interactivity plugin

- community-css-themes.json
Link to my theme:  https://github.com/Spekulucius/obsidian-brainhack
> Add theme: Brainhack

- community-plugins.json
Link to my plugin: https://github.com/Ssentiago/openapi-renderer
> Add plugin: OpenAPI Renderer

- community-plugins.json
Link to my plugin: https://github.com/kctekn/obsidian-TagsRoutes
> Add plugin: Tags Routes

- community-plugins.json
Link to my plugin: https://github.com/FlorianWoelki/obsidian-better-recall
> Add plugin: Better Recall

- community-plugins.json
Link to my plugin: https://github.com/singh-inder/obsidian-images-to-gist
> Add plugin: Images to Gist

- community-plugins.json
Link to my plugin: https://github.com/shsethi/obsidian-rollover-weekly-todos
> Add plugin: Rollover Weekly Todo

- community-plugins.json
> Correct misspelled Github repo name

- community-plugins.json
Update the description of existing plugin image-upload-toolkit.
> Update the desc of plugin image-upload-toolkit

- community-css-themes.json
> Add theme: nobb

- community-css-themes.json
\* Changed image size
Link to my theme:
> Add theme: Vanilla AMOLED Color

- community-plugins.json
Link to my plugin: https://github.com/ai-chen2050/obsidian-youtube-downloader
> Add plugin: YouTube downloader

- community-plugins.json
Link to my plugin:https://github.com/Kanaries/photes-io-obsidian-plugin
> Add plugin: Image to notes by Photes.IO

- community-plugins.json
Link to my plugin: https://github.com/augustin7698/note-2-tag-generator
> Add plugin: Note 2 Tag Generator

- community-plugins.json
Link to my plugin: https://github.com/eebmagic/post-medium-draft
> Add plugin: Post Medium Draft

- community-plugins.json
Link to my plugin: https://github.com/eust-w/obsidian-image-auto-upload
> Add plugin: Fast Image Auto Uploader

- community-plugins.json
Link to my plugin: https://github.com/DarioCasciato/obsidian-auto-folder-collapse
> Add plugin: Auto Folder Collapse

- community-plugins.json
https://github.com/drbap/dashboard-navigator-for-obsidian
> Add plugin: Dashboard navigator

- community-plugins.json
Link to my plugin: https://github.com/itsonlyjames/obsidian-quick-open
> Add plugin: Quick Open

- community-plugins.json
Link to my plugin: https://github.com/joshuawootonn/rich-text-editor-shortcuts
> Add plugin: Rich Text Editor Shortcuts

- community-plugins.json
> Add plugin: Recent Tab Switcher

- community-plugins.json
Link to my plugin: https://github.com/zhenlohuang/obsidian-hexo-publisher
> Add plugin: Hexo Publisher

- community-css-themes.json
Link to my theme: https://github.com/ricedev10/Abate-theme
> Add theme: Abate

- community-css-themes.json
Link to my theme: https://github.com/taronull/ayu-obsidian
> Add theme: Ayu Light & Mirage

- community-plugins.json
Link to my plugin: https://github.com/noam-sc/obsidian-enhanced-symbols-prettifier
This is my first plugin release, don't hesitate to provide feedback or suggestions for improvements.
> Add plugin: Enhanced Symbols Prettifier

- community-plugins.json
Add Smart Templates
Link to my plugin: https://github.com/brianpetro/obsidian-smart-templates
> Add plugin: Smart Templates

- community-plugins.json
Link to my plugin: https://github.com/h-sphere/obsidian-canvas-picture-in-picture
> Add plugin: Canvas Picture in Picture

- community-plugins.json
https://github.com/madpin/super-duper-audio-recorder
> Add plugin: Super Duper Audio Recorder

- community-plugins.json
Link to my plugin: https://github.com/oxdc/obsidian-vertical-tabs
> Add plugin: Vertical Tabs

- community-plugins.json
Link to my plugin: https://github.com/Max-Schulten/truth-table-plus
> Add plugin: Truth Table+

- community-plugins.json
Link to my plugin: https://github.com/tankh99/learnie-plugin/
> Add plugin: Learnie

- community-plugins.json
Link to my plugin: https://github.com/BungaRazvan/confluence-link
> Add plugin: Confluence Link

- community-plugins.json
https://github.com/No-Instructions/Relay
> Add plugin: Relay

- community-plugins.json
> Update tags-routes plugin description

- community-css-themes.json
Link to my theme: https://github.com/Elevict/Shade-Sanctuary/tree/main
> Add theme: Shade Sanctuary

- community-css-themes.json
Link to my theme: https://github.com/Seniblue/Underwater
> Add theme: Underwater

- community-plugins.json
> Update the description of plugin: Vertical Tabs

- community-plugins.json
The plugin's repo is [here](https://github.com/elijah-potter/harper-obsidian-plugin),
but the actual code resides in [here](https://github.com/elijah-potter/harper).
> Add plugin: Harper

- community-plugins.json
Link to my plugin: https://github.com/zzunebye/obsidian-google-liked-video
> Add plugin: Geulo

- community-plugins.json
Link to my plugin:  https://github.com/ketd/obsidian-sync-DB-OS
> Add plugin: sync-db-os

- community-plugins.json
> Add plugin: Daily Statistics

- community-plugins.json
Link to my plugin: https://github.com/GRA0007/obsidian-css-inlay-colors
> Add plugin: CSS Inlay Colors

- community-plugins.json
> Add plugin: GTP Preview

- community-plugins.json
Link to my plugin: https://github.com/Rudtrack/structured-tree
> Add plugin: Structured Tree

- community-plugins.json
https://github.com/Shusako/arcane-obfuscate
> Add plugin: Arcane Obfuscate

- community-plugins.json
Link to my plugin: https://github.com/stuporfly/ObsidianTodoistProjects
> Add plugin: Todoist Project sync

- community-plugins.json
Link to my plugin: [link](https://github.com/StructByLightning/obsidian-recursive-copy)
> Add plugin: Recursive Copy

- community-plugins.json
Link to my plugin: https://github.com/OlegWock/obsidian-emera
> Add plugin: Emera

- community-plugins.json
> [UPDATE] Rename Plugin Quick Open to Quick Select

- community-plugins.json
Link to my plugin: [https://github.com/jxpeng98/obsidian-to-NotionNext](https://github.com/jxpeng98/obsidian-to-NotionNext)
Update the plugin description since it can support more types of notion databases.
> Update: share-to-notionnext description

- community-plugins.json
Link to my plugin: [Line Arrange](https://www.github.com/chitwan27/lineArrange)
> Update description of my plugin: Line Arrange.

- community-plugins.json
Updates the description of the "Are.na Manager" plugin so it can be found in https://obsidian.md/plugins?search=Arena
> Updates the description of my plugin so it can be more easily found

- community-css-themes.json
Link to my theme: https://github.com/c-sooyoung/kiwi-mono-obsidian-theme
> Add theme: Kiwi Mono

- community-plugins.json
Update peerdraft plugin description to include new features.
https://github.com/peerdraft/obsidian-plugin
> Update peerdraft plugin description to include new features

- community-plugins.json
Link to my plugin: https://github.com/aaaaayushh/ai-latex-generator/
> Add plugin: AI LaTeX Generator

- community-plugins.json
Link to my plugin: https://github.com/tejas-hosamani/obsidian-plugin-text-to-speech
> Add plugin: Listen Up!

- community-plugins.json
Link to my plugin: https://github.com/ggauravr/obsidian-serendipity-plugin/
> Add plugin: Serendipity

- community-plugins.json
Link to my plugin: [Link](https://github.com/TravisLinkey/note-reviewer)
> Add plugin: Note Reviewer

- community-plugins.json
Link to my plugin: https://github.com/h-sphere/obsidian-mahjong-renderer
> Add plugin: Mahjong Renderer

- community-plugins.json
Link to my plugin: https://github.com/James-Yu/external-file-card
> Add plugin: External File Card

- community-plugins.json
> Add plugin: Vitepress Publisher

- community-plugins.json
> Add plugin: Suggest Notes

- community-plugins.json
Link to my plugin: https://github.com/hjamet/Canvas-Explorer
> Add plugin: Canvas Explorer

- community-plugins.json
> Add plugin: Snippets Manager

- community-plugins.json
Link to my plugin: https://github.com/Erallie/css-inserter
> Add plugin: CSS Inserter

- community-plugins.json
Link to my plugin: https://github.com/HamzaBenyazid/obsidian-live-variables
> Add plugin: Live Variables

- community-plugins.json
Link to my plugin: https://github.com/jordanhandy/obsidian-imgbb-uploader
> Add plugin: ImgBB Uploader
