community-plugins.json
A plug-in to allow easy insertion and renaming of latex environments in math blocks.
=> Add Latex Environments plugin

community-plugins.json
This plugin adds basic functionally for converting obsidian files to TeX format.
=> Add Export To Tex plugin

community-plugins.json
Adds an Extended MathJax plugin which has a fixed global preamble as well as support for additional mathjax packages (for now `mdchem` and `bussproofs`). I'm reserving the name `obsidian-latex` because I'm working on an additional feature which would allow actually calling latex for math rendering instead of mathjax in a future release.
=> Add Extended MathJax plugin

community-plugins.json
Deprecating in favour of `obsidian-latex`
=> Remove obsidian-latex-preamble-plugin

community-plugins.json
[Temple](https://github.com/garyng/obsidian-temple) is a templating plugin that uses nunjucks under the hood. Serves as a more extensible alternative to https://github.com/SilentVoid13/Templater.
=> Add temple plugin

community-plugins.json
Hi @lishid!
I'm super excited about this plugin and would love to share it with the community. 
Since we spoke about using Obsidian's PDFJS – In this case here, that won't be possible because I had to create a really customized version of PDFJS in order to retrieve the annotation text. I'm using my fork from `https://github.com/akaalias/pdfjs-dist` to get it done. 
Question here: How can I import it so it doesn't overload Obsidian's PDFJS? 
Currently I'm doing: 
``` 
import pdfjsCustom from "node_modules/pdfjs-dist/build/pdf";
import worker from "node_modules/pdfjs-dist/build/pdf.worker.entry";
... 
pdfjsCustom.GlobalWorkerOptions.workerSrc = worker;
...
var loadingTask = pdfjsCustom.getDocument(arrayBuffer);
...
```
I've also re-used your suggestion on file-handling from before:
```
let …
```
=> Adds PDF Highlights plugin

community-plugins.json
I'd like to change the name of the repo of Neo4j Graph View from `semantic-markdown-converter` to `obsidian-neo4j-graph-view`. 
The old name isn't representative of the contents of the repo anymore (the Python library called semantic-markdown-converter will be deprecated in the next version). 
Will everything keep working if the repo is changed like this? (Ie, all installations and stats are kept, just the link changes?)
The repo will be renamed when/if the PR is accepted, so people can still install it until that happens.
=> Change repo of Neo4j Graph View

community-plugins.json
Adds https://github.com/MichalBures/obsidian-file-path-to-uri plugin.
=> Add File path to URI plugin

community-plugins.json
Adds https://github.com/beet/page-headings-obsidian-plugin
I like to create new pages by first inserting a link into the parent page like `[[My child page]]`, and then clicking on the link to create it. I then have to manually insert a heading matching the filename like `# My child page`.
With this plugin enabled, a `file-open` callback constructs a heading any time a blank file is opened, either from having just created it from a link, or it already existing, and inserts it into the page so it's one less thing to do.
=> Add page heading from links plugin

community-plugins.json
I forgot to adjust the id for the plugin. I apologize for the oversight. 
See https://github.com/obsidianmd/obsidian-releases/pull/122
Thank you in advance!
=> Fix id for visini/obsidian-icons-plugin

community-plugins.json
https://github.com/liamcain/obsidian-things-logbook
This plugin will periodically fetch tasks from the [Things 3](https://culturedcode.com/things/) SQLite DB and insert them into their own section within your daily notes.
Note: The plugin is macOS-only (and requires Things to be installed) so I do an initial upfront check in `onload` for the platform.
=> Add Things logbook plugin

community-plugins.json
I don't know it it is the best way to acces the starred files, but it works.
(https://github.com/Vinzent03/obsidian-shortcuts-for-starred-files)
=> add "Shortcuts for starred files" plugin.

community-plugins.json
Plugin for keeping the filename and first heading of a file in sync https://github.com/dvcrn/obsidian-filename-heading-sync
=> Add filename-heading-sync plugin

community-plugins.json
https://github.com/denisoed/obsidian-orthography
* Search for spelling errors in the text
* Displaying options for correcting word mistakes
* Correct a word mistake in one click
=> Add obsidian-orthography plugin

community-plugins.json
The plugin isn't currently not working in the latest build (I can't even get it to run...). I don't have time right now to fix the issue, it will have to wait at least another 2-3 weeks. I'd rather remove it from the list until then so it doesn't affect anyone. Sorry for the trouble.
=> Removes YAML front matter template plugin

community-plugins.json
Hi @lishid!
I've created this plugin to find the connection between two notes in the vault. Check out this discussion on the forum for details and a demo video: https://forum.obsidian.md/t/new-plugin-journey-find-the-story-between-your-notes/12153
Let me know what you think and hope we can get this into the community soon :) 
Thank you so much, 
Alexis
=> Adds Journey Plugin

community-plugins.json
A plugin for text-based GTD in Obsidian.
Features in this initial release:
- Aggregates all outstanding TODOs in your vault and lists them in a single view
- Split out TODOs by type ("Today", "Scheduled", "Inbox" and "Someday/Maybe")
- Schedule a TODO for a specific date by adding a tag #YYYY-DD-MM
- Mark a TODO as Someday/Maybe by adding a tag #someday
- Complete TODOs from the list view
- Quickly jump to the file in which a TODO is found from the list view
=> Add TODO plugin

community-plugins.json
Hi @lishid, 
This is a simple plugin based on this [forum discussion](https://forum.obsidian.md/t/footnote-shortcut/8872). 
3 members of the community have asked me to add it to the community plugins. 
I thought the idea was really good because I've also felt the barrier to footnotes was too high. I've since stopped using them personally.
Let me know what you think :) 
Thank you and have a great weekend. 
Alexis
=> Adds Footnote Shortcut plugin

community-plugins.json
https://github.com/pjeby/hotkey-helper
=> Add hotkey-helper plugin

community-plugins.json
[https://github.com/joethei/obsidian-plantuml/](https://github.com/joethei/obsidian-plantuml/)
=> Add PlantUML Plugin

community-plugins.json
The description should say "merge" instead of "delete"
=> Fix tag-wrangler description

community-plugins.json
Hello!
I created plugin to work with lists like in Workflowy or RoamResearch.
https://github.com/vslinko/obsidian-outliner
=> Add vslinko/obsidian-outliner

community-plugins.json
https://github.com/mgmeyers/obsidian-style-settings
=> Adds obsidian-style-settings plugin

community-css-themes.json
This is a minor update. I noticed that the thumbnail for my theme isn't loading. Seems like it was pointing to the wrong branch!
=> Use main branch for California Coast theme

community-plugins.json
https://github.com/mgmeyers/obsidian-embedded-note-titles
=> Adds obsidian-embedded-note-titles

community-plugins.json
[alx-plugins/cm-chs-patch](https://github.com/alx-plugins/cm-chs-patch)
Related Feature Request: <https://forum.obsidian.md/t/editor-cm5-doesnt-support-word-splitting-in-cjk-languages/15773>
=> Add cm-chs-patch

community-plugins.json
With the release of the [Style Settings](https://github.com/mgmeyers/obsidian-style-settings) plugin, the California Coast settings plugin is now deprecated. This PR removes it from the community-plugin list.
=> Remove California Coast settings plugin

community-plugins.json
The original pull request still used the outdated 'Tabbed View' title, rather than the current 'Obsidian Tabs' title, also, the description was incomplete.
=> Correct Obsidian tabs plugin entry

community-plugins.json
I really enjoyed working with https://github.com/obsidianmd/obsidian-sample-plugin and Obsidian ecosystem in general. Thank you.
https://github.com/kenzan100/beeminder-obsidian-word-count
=> Add Beeminder Word Count Plugin

community-plugins.json
A while ago I had changed the name of the plugin to **Readwise Community** as per request by the Readwise folks. I misseed updating the name here, so that it shows with the proper name in the `Browse` plugin list in Obsidian
https://github.com/renehernandez/obsidian-readwise
=> Change display name for the readwise community plugin

.github/pull_request_template.md
Require plugins to have a license in the LICENSE file to avoid any legal snags / too many abandoned projects being lost to the litigious ether down the line.
Typically the MIT license will be a good choice for most projects who want to be very permissive (which might often be the case for plugins that are unlikely to ever be monetized or independent of Obsidian - I am not a lawyer).
Perhaps a comment containing a link to https://choosealicense.com/ could be added to the template, though I didn't want to add 'noise'.
Per discussion in #plugin-dev channel: https://discord.com/channels/686053708261228577/840286264964022302/854099720505786409
Feel free to close/discard this if this isn't how you want it - I just wanted to make sure it wasn't forgotten!
=> Require licenses

community-plugins.json
I have to rename the plugin to meet Dropbox's branding guidelines, and the app has already surpassed the limit of users for a development app.
https://github.com/ryanpcmcquen/obsidian-dropbox-backups
=> Rename Dropbox Backups plugin.

community-plugins.json
- I removed mentions of my old discord name (rythm)
- I removed the extended-context-menu Plugin since its not needed anymore, for my knowledge no Plugin relies on it
- On Discord I was told that using "Obsidian" in a Plugin Name is more or less bad, since of course its for Obsidian and it messes with the sorting
=> Remove extended-context-menu + Update my Plugin Info

community-css-themes.json
https://github.com/johackim/obsidian-darkyan
=> Add Darkyan theme to community themes

community-plugins.json
https://github.com/NomarCub/obsidian-open-vscode
=> add Open vault in VSCode

community-plugins.json
The plugin got disabled due to a reported data loss issue. The plugin got hardened and a few bugs fixed so I'd like to re-submit it - https://github.com/dvcrn/obsidian-filename-heading-sync/issues/18
=> Re-add obsidian-filename-heading-sync

community-plugins.json
https://github.com/aidenlx/mx-bili-plugin
A plugin that opens a reverse proxy server for [Media Extended](https://github.com/aidenlx/media-extended) to play bilibili video in Obsidian
- ~~`styles.css`~~
=> add mx-bili-plugin

community-css-themes.json
Link to my theme: [nikbrunner/obsidian-deep-work-theme](https://github.com/nikbrunner/obsidian-deep-work-theme)
=> Add Deep Work Theme

community-plugins.json
Link to my plugin: <https://github.com/alx-plugins/alx-folder-note>
=> Add alx-folder-note

community-plugins.json
Link to my plugin: https://github.com/onlyafly/number-headings-obsidian
=> Add number-headings-obsidian to community plugins list

community-plugins.json
I updated the source plugin ID per feedback in https://github.com/motif-software/obsimian/pull/3, but did not also update the ID here to match. This PR makes them consistent.
=> Fix plugin mismatch

community-plugins.json
Link to my plugin: https://github.com/Taitava/obsidian-shellcommands
=> Add Shell commands plugin

community-plugins.json
This plugin adds tooltips on hover for external links. These tooltips display the destination URL.
Link to my plugin: https://github.com/jamiebrynes7/obsidian-hover-external-link
=> Add Hover External Link plugin

community-plugins.json
This plugin provides copy button,linenumber,language name for the markdown code block in preview.
Link to my plugin: [https://github.com/nyable/obsidian-code-block-enhancer](https://github.com/nyable/obsidian-code-block-enhancer)
=> Add Code Block Enhancer Plugin

community-plugins.json
Get links to blocks from the right click menu.
Link to my plugin: https://github.com/mgmeyers/obsidian-copy-block-link
=> Add obsidian-copy-block-link

community-plugins.json
This is a plugin to connect Trello cards to Obsidian notes. It uses the trello rest API along with a new view in Obsidian to retrieve data, display comments, add new comments. Plenty of future work ahead to expand what it can do.
Code review notes:
- It's a fairly large one. I used [rxjs](https://www.learnrxjs.io/) all over the place in it, but that's the only 3rd party library involved.
- Has a dependency on the [MetaEdit](https://github.com/chhoumann/MetaEdit) plugin, but it should fail gracefully.
- Uses rxjs ajax to make requests to the Trello API. Internally this uses standard XMLHttpRequest stuff, it just gets wrapped in some rxjs magic.
- Yes, there's an API key committed in the code. This is intentional - not sure why Trello calls it that, it's really an application ID.
- Things …
=> Add Obsidian Trello plugin

community-plugins.json
Link to my plugin: https://github.com/marcjulianschwarz/obsidian-file-link
=> Add obsidian-file-link plugin

community-plugins.json
Link to my plugin: https://github.com/pjeby/quick-explorer/
- [ x My GitHub release contains all required files
=> Add Quick Explorer plugin

community-plugins.json
This plugin adds the ability to add banners to your notes, through either an image URL or a local image file.
Link to my plugin: https://github.com/noatpad/obsidian-banners
=> Add Banners plugin

community-plugins.json
Link to my plugin: https://github.com/aidenlx/folder-note-core
The core of [alx-folder-note v0.11.0+](https://github.com/aidenlx/alx-folder-note/tree/core), derived from [alx-folder-note](https://github.com/aidenlx/alx-folder-note/), providing API and basic folder note features without ux patches and folder overview
=> Add folder-note-core

community-plugins.json
Periodically fetches and displays top stories from HackerNews.
Link to my plugin: https://github.com/arpitbbhayani/obsidian-hackernews
=> adding Obsidian HackerNews

community-plugins.json
I would like to change the human-readable name of the `obsidian-pocket` plugin, based on user feedback from https://github.com/nybbles/obsidian-pocket/issues/49.
=> Shortening obsidian-pocket name

community-css-themes.json
removing warmth theme from community themes because it needs far more work than i have time for these days.
Link to my theme: https://github.com/chad-bennett/warmth-obsidian-theme
=> remove warmth theme from community themes

community-plugins.json
Link to my plugin: https://github.com/Daeik/obsidian-nomnoml-diagram
=> Add Nomnoml Diagram plugin

community-plugins.json
I have noticed today that one website the plugin makes requests to has a per minute request limit. 
With default settings and normal usage it shouldn't cause problems. However, I have decided to change the implementation, because restricting it effectively so that users cannot go over that limit would limit the plugins' user experience.
I currently don't have the time to make these changes, which is why I'm pulling the plugin for now.
=> remove linked data vocabularies

community-plugins.json
Changed from "obsidian-livesync" to "Self-hosted LiveSync"
And add the note "Community implementation" to description.
=> Name changed, and add description.

plugin-review.md
This pull request proposes some changes to the plugin review guidelines: 
- Turn guidelines into their imperative form where possible. Instead of describing what developers have done in the past, explain what the reader need to do now.
- Tighten up text by remove justifications and explanations. This document shouldn't provide the documentation for the functions and APIs, but to serve as a checklist to make sure their plugin is ready for review.
I've tried to simplify and condense the language as much as I can. Let me know if there's anything I oversimplified too much. Also, let me know if you'd like me to split this into smaller PRs instead.
=> Edit plugin review guidelines

community-plugins.json
There isn't a good way in the obsidian api right now to implement a new text format that has similar behavior to MarkdownSourceView respecting the various editor settings. Lots of custom logic for token parsing is baked into hypermd codemirror mode. example [[foo]] printing to be clickable internal link. As an implementation I originally extended from that view and modify the parts I needed for todo-txt but its constantly breaking as changes go out.
I give up.
=> remove obsidian-todo-txt from community plugins

community-css-themes.json
Link to my theme: https://github.com/hungsu/typomagical-obsidian
=> Add Typomagical to community themes

community-css-themes.json
Not applicable
A recently-added theme currently has its mode list called `compatibleModes` - I've fixed it to `modes`, for consistency with the rest of the file...
Found by running a Python script to parse the themes, which tripped up saying no "modes" value was available.
=> Fix mode named compatibleModes which prevents parsing themes list

community-plugins.json
Adds the 'vscode' keyword to the description of Code Editor Shortcuts to improve discoverability, as suggested in https://github.com/timhor/obsidian-editor-shortcuts/issues/4
=> Update Code Editor Shortcuts description

community-css-themes.json
Link to my theme: https://github.com/crashmoney/obsidian-typewriter
=> Add Typewriter to community themes

community-plugins.json
Link to my plugin: https://github.com/nothingislost/obsidian-codemirror-options
Updating the description to more accurately describe what this plugin does. Once the official Live Preview mode is fully released, I'll update this again to say "Enhance Obsidian's **legacy** desktop edit mode..."
=> Update the CodeMirror Options plugin description

README.md
I added two links to guides on the hub for plugin and theme authors that explain how to make a PR.
=> docs: add links to PR documentation on the hub

community-plugins.json
Link to my plugin: https://github.com/beaushinkle/obsidian-generic-initiative-tracker
=> Add Generic Initiative Tracker for TTRPGs to the Plugin List

community-plugins.json
Hi all! I'm with the [Matter](https://hq.getmatter.app) team. We've received dozens of requests for an Obsidian integration. We can't wait to get this to all of our users. Let me know if there is anything else you need from us.
Link to my plugin: [obsidian-matter](https://github.com/getmatterapp/obsidian-matter)
=> Add Matter to community plugins

community-plugins.json
The reason is https://github.com/tadashi-aikawa/obsidian-various-complements-plugin/issues/51
=> Update a description of `Various Complements`

community-plugins.json
The scope of the plugin is bigger now, hence the changes.
I didn't touch the ID, so current users should not be affected. Once it is merged, I will make a patch release and update the plugin name.
=> update name and description of copy-publish-url

community-plugins.json
Link to my plugin: https://github.com/manic/obsidian-wrap-with-shortcuts
=> Add Wrap with shortcuts

community-plugins.json
https://github.com/mgmeyers/obsidian-indentation-guides
=> Add indentation guides plugin

community-plugins.json
Link to my plugin: https://github.com/frankolson/obsidian-tomorrows-daily-note
=> Add Tomorrow's Daily Note plugin to community list

community-plugins.json
Link to my plugins:
https://github.com/farling42/obsidian-import-foundry
https://github.com/farling42/obsidian-import-json
=> Add Import Foundry and Import JSON plug-ins

community-css-themes.json
I am re-organizing the repo, therefore a change of the location of the promo screenshot. That's it.
=> update link to screenshot

community-plugins.json
Removing Advance Appearance from plugins list
See more detail in Readme — the plugin has become obsolete, and I no longer have time to support it.
https://github.com/kepano/obsidian-advanced-appearance
=> Remove Advanced Appearance

community-plugins.json
Link to my plugin: https://github.com/ben/obsidian-13th-age-statblocks
=> Add 13th-age-statblocks plugin

community-plugins.json
Link to my plugin: https://github.com/Edo78/obsidian-koreader-sync
=> Add obsidian-koreader-sync to community plugins list

README.md
The readme currently states that only the `name` field is used when
searching for plugins.
I noticed that the `author` and `description` fields are also used, so
am updating the readme here to reflect this.
=> Fix plugin search fields in readme

community-plugins.json
Updated url for Multi-Column Markdown to be more consistent with the plugin id naming scheme.
=> Updated Multi-Column Markdown url.

community-plugins.json
[Link to my plugin](https://github.com/thisdotrob/obsidian-relativenumber-plugin)
=> Add obsidian-relativenumber plugin

community-plugins.json
Just a typo in a plugin name...
/CC @jmilldotdev
=> Fix typo in plugin name: Sugest -> Suggest

community-plugins.json
Link to my plugin: https://github.com/farux/obsidian-auto-note-mover
=> Add auto-note-mover plugin

community-plugins.json
Link to my plugin: https://github.com/signynt/insert-heading-link
=> Add insert-heading-link plugin

community-plugins.json
Link to my plugin: [cm-japanese-patch](https://github.com/sonarAIT/cm-japanese-patch)
=> Add "Word Splitting for Japanese in Edit Mode" Plugin

community-css-themes.json
This is a correction to a GitHub URL in the theme 'Sparkling-Wisdom-obsidian-theme-'
=> Remove stray space at end of theme URL - fix to existing theme

community-plugins.json
Link to my plugin: https://github.com/aidenlx/alx-folder-note-folderv
It's a part of existing [alx-folder-note](https://github.com/aidenlx/alx-folder-note) plugin that has been published for quite some time so there is no need to review this plugin in depth. 
The purpose of creating a dedicated plugin is to make the Folder Overview feature optional so that those only need basic feature of alx-folder-note won't have to [waste the loading time](https://github.com/aidenlx/alx-folder-note/issues/57) for all the resources for `folderv` code block
=> add alx-folder-note-folderv

community-plugins.json
There are now two plugins by user @Signynt 
Note the difference in capitalisation of the user name in the two `repo` values...
The Obsidian Hub code wasn't written to detect inconsistencies in the case used for the same user name, and even though the code here isn't wrong, unfortunately we've ended up with two differently-cased author files created in the Hub vault, which has tripped up Mac Hub Contributors (me!) and will also trip up Windows Hub contributors.
See https://github.com/obsidian-community/obsidian-hub/issues/308
> "Prevent files being created that differ only in case of name - and deal with signynt.md/Signynt.md"
This PR tweaks the newer `signynt`  Url to make it consistent with the original `Signynt`, until we can come up with a way to guard against this happening again in …
=> Fix inconsistency in case of username

community-plugins.json
As discussed on Discord: the original owner does not maintain the plugin anymore (didn't react to any kind of outreach either), so we need to change the repo to the functioning fork I created.
Link to my plugin: https://github.com/MichaBrugger/obsidian-footnotes
=> changing the root repo

community-plugins.json
Link to my plugin: https://github.com/munach/obsidian-pdf-annotations
=> add obsidian-pdf-annotation plugin

community-plugins.json
I'd like to deprecate the plugin, since I have made a much better plugin that includes most of this plugin's functionality: [Smarter Markdown Hotkeys](https://github.com/chrisgrieser/obsidian-smarter-md-hotkeys). For HTML tags, there is now the much more customizable [Wrap with Shortcuts Plugin](https://github.com/manic/obsidian-wrap-with-shortcuts). All in all, there isn't really any reason to keep this plugin in the community store.
([Discord Reference](https://discord.com/channels/686053708261228577/716028884885307432/953006639475220490))
=> Remove "Extra Markdown Commands" from Plugin List

community-plugins.json
As stated in #795, I introduced a typo when I made a PR for my plugin markdown shortcuts, so here is the fix.
=> [Fix] Fixed Markdown shortcuts typo

community-plugins.json
This PR updates the description for the Full Calendar plugin, since the old wording made it seem like fullcalendar.io was a third-party service you needed to use rather than a UI library that the plugin was built on top of.
=> Update Full Calendar description

community-plugins.json
Would like to deprecate the plugin because it was implemented in Obsidian 0.13.8.
=> Deprecate "Add Codemirror matchbrackets.js"

community-plugins.json
The Fantasy Calendar plugin is now officially part of the [Fantasy Calendar](https://fantasy-calendar.com/) family.
=> Update Fantasy Calendar repository

community-plugins.json
Previously the plugin is called [Daily notes new tab](https://github.com/reorx/obsidian-daily-notes-new-tab), I just realized that I should use the word [Pane](https://help.obsidian.md/User+interface/Workspace/Panes/Pane+layout) not "Tab", and this plugin has added a lot of new features so I think "opener" could be a better name for it.
The new repo's release starts from [2.0.0](https://github.com/reorx/obsidian-daily-notes-opener/releases/tag/2.0.0).
Link to my plugin: https://github.com/reorx/obsidian-daily-notes-opener
=> Rename "Daily notes new tab" to "Daily notes opener"

community-css-themes.json
I am editing my Community Theme (Willemstad) to include an indication it has a `publish.css` file for Obsidian Publish
Link to my theme: https://github.com/tingmelvin/willemstad-x/
Publish file: https://github.com/tingmelvin/willemstad-x/blob/main/publish.css
=> Add `"publish": true` to the Willemstad theme

community-plugins.json
The entries for
both the [Todoist Link](https://github.com/dennisseidel/obsidian-todoist-link)
and the [Omnisearch](https://github.com/scambier/obsidian-omnisearch) plugins
are pointing to the authors forked version of this repo.
The plugins cannot be viewed in Obsidian as a result.
(I also think that the name for the Todoist plugin as it is in the list currently is missing the most important part cc @dennisseidel)
=> fix two plugins linking the wrong repository

community-css-themes.json
Hello, I'm submitting a new theme called Zenburn. It's a low-contrast "dark mode" theme from vim that I've used for all my tools over the years. I just wanted to see it on Obsidian :)
Link to my theme: https://github.com/danyim/obsidian-zenburn
=> Add Zenburn theme

community-plugins.json
We moved the plugin to an organization to ensure the possibility of
ownership transfer. Clare has taken over as the core maintainer of the project.
In the meantime, installation in Obsidian still works via redirects by GitHub.
Link to my plugin: https://github.com/obsidian-tasks-group/obsidian-tasks
Cc @claremacrae
=> Update link to obsidian tasks plugin

README.md
while not strictly necessary, it's probably useful to give plugin/theme devs some infos on how/where to announce their contribution. 
Questions how to post in `#updates` come up regularly in Discord, for example, and can be centrally answered by this addition to the readme.
=> Infos for publicly announcing plugin/themes

community-plugins.json
This PR removes two of my plugins.
The Library of Congress changed their data format, so the helper plugin doesn’t work anymore. I may adapt the parser at some point, but for now the plugins don’t work for new users.
=> remove two plugins

community-plugins.json
Hi!
Because of the amount of repo linked to `Github Publisher` and my free publish alternative, `Obsidian Mkdocs Publisher`, I created an organization. So, I need, again to change the repo link in the release.
Sorry for inconveniance !
=> changing repo owner of Github Publisher

community-css-themes.json
RuslanGagushin/Tokyo-Night-Obsidian-Theme doesn't exist anymore.
=> Remove deleted theme

community-plugins.json
- Plugin changelogs is not functional anymore, and I don't have the time to maintain that many plugins anyway
- The Macros plugin has many bugs and a really small feature set, I plan to add a more powerful version of it to [Commander](https://github.com/phibr0/obsidian-commander) in the near future.
=> Remove old plugins 

community-plugins.json
This is a plugin update, not a new submission. The automatic PR navigation thing failed last time, so I'd rather do it in this plain way.
=> change plugin name for Copy Image & URL plugin, use reading view terminology

community-plugins.json
Link to my plugin: https://github.com/dpickett/open-related-url
=> add open-related-url plugin

community-plugin-stats.json, community-plugins.json
https://github.com/jon-heard/obsidian-inline-scripts
Link to the old plugin:
https://github.com/jon-heard/obsidian-text-expander-js
=> Plugin name changed - "Text Expander JS" to "Inline Scripts"

community-plugins.json
Link to my plugin: https://github.com/NomarCub/obsidian-hide-sidebars-on-window-resize
=> add Hide Sidebars on Window Resize plugin

community-plugins.json
I changed the repo of my existing plugin (under this account) to the new team account (@tresselteam)
=> Change repo (link) of Tressel Sync for Obsidian plugin

community-plugins.json
The Pikt plugin is no longer maintained.
=> Remove obsidian-pikt plugin

community-plugins.json
@bitwiseops stated in their readme that they can no longer maintain the repo: https://github.com/bitwiseops/obsidian-kobo-highlights-import/blob/master/README.md. I have created a fork and will be improving it and implementing feature requests. 
I don't have @bitwiseops blessings yet, @bitwiseops if you see this PR, could you approve? If not, maintainers, can we set some sort of deadline for the original maintainer to respond so that this plugin does not die? 
Link to my plugin: https://github.com/OGKevin/obsidian-kobo-highlights-import
=> Update Kobo plugin

community-css-themes.json
(I had to re-organize the theme repo due to 0.16, breaking the promo screenshot link)
=> Update Link to Screenshot for SF

community-plugins.json
Link to my plugin: https://github.com/b0o/obsidian-embedded-note-paths/
=> Add b0o/obsidian-embedded-note-paths

community-css-themes.json
Shimmering Focus is now usable in Insider 0.16. 
(For those coming from Discord: A lot of Style Settings are still missing though)
- Screenshot is updated to the new requested format
- `manifest.json` added
- docs consolidated into the README.md for new theme browser
=> remove `legacy` from Shimmering Focus

community-plugins.json
Link to my plugin: https://github.com/Vinzent03/obsidian-git-mobile
The code of this plugin lies in [obsidian-git](https://github.com/denolehov/obsidian-git). Since 1,5 years I'm the maintainer of the plugin. So I'm updating the author field of Obsidian Git.
The codebase works with two different git implementations. I'm removing the native git dependency in the [build process](https://github.com/Vinzent03/obsidian-git-mobile/blob/main/.github/workflows/main.yml) of this plugin. I haven't found a way to package node dependencies in a mobile version, so I have to create a whole new plugin entry.
=> Obsidian Git Mobile

community-css-themes.json
https://github.com/dracula/obsidian
=> Remove legacy status from Dracula Official

community-plugins.json
I want to change the name of my plugin to remove useless text and make it more visible when searching.
=> Changed name of Google Tasks plugin

community-plugins.json
Link to my plugin: https://github.com/Quorafind/Obsidian-Table-Generator
=> Add Table Generator To Plugin Lists

community-plugins.json
Most of the functionality is implemented by the Commander plugin.
And @pjeby has implemented history counts with the native tab title bar buttons in Pane Relief. Since Obsidian version 0.16 isn’t public yet, I think it makes sense to merge this commit once 0.16 goes public.
=> remove page header button plugin

community-plugins.json
Link to my plugin: https://github.com/isaaclyman/novel-word-count-obsidian
I promise not to do this often. Following a number of community requests, the scope of my plugin has increased significantly and the old description doesn't summarize it well any more. I've updated the wording.
=> Update Novel Word Count description

community-css-themes.json
https://github.com/sergey900553/obsidian_githublike_theme
- Screenshot is updated 
- `manifest.json` added
- updated readme
- added `theme.css`
- added LICENSE file
=> Remove legacy status from Dark Moss

community-css-themes.json
Link to my theme:  https://github.com/erykwalder/dayspring-theme
=> Add Dayspring to community themes

community-plugins.json
[Doubleshift](https://github.com/Qwyntex/doubleshift)
=> changed description of my plugin

community-plugins.json
Link to my plugin: https://github.com/zfei/obsidian-url-namer
=> Add URL Namer plugin

community-css-themes.json
Red Graphite has been updated to work with Obsidian 1.0.
https://github.com/seanwcom/Red-Graphite-for-Obsidian
=> Updating Red Graphite

community-plugins.json
Link to my plugin: https://github.com/abcjs-music/obsidian-plugin-abcjs
The plugin has been transferred to abcjs-music organization. The original location https://github.com/TilBlechschmidt/obsidian-plugin-abcjs redirects to the new URL.
=> updating the plugin description and location

community-plugins.json
This is an edit to an existing line in `community-plugins.json`
The change is:
```diff
- "repo": "Quorafind/obsidian-sakana-widget",
+ "repo": "quorafind/obsidian-sakana-widget",
```
This is a workaround for a limitation in the Hub Python code. See https://github.com/obsidian-community/obsidian-hub/issues/308
It makes the capitalisation of `quorafind` consistent throughout the community release files.
/CC @Quorafind for info.
=> Make capitalisation of Quorafind match earlier lower-case uses.

.github/workflows/validate-plugin-entry.yml
This change should allow plugin authors to publish plugins on behalf of their GitHub organization
=> Update validate plugin entry to account for publishing on behalf of orgs

community-css-themes.json
I am submitting an update to my theme, enabling it for v1.0.0 according to [1.0 Theme Migration Guide](https://forum.obsidian.md/t/1-0-theme-migration-guide/42537).
Link to my theme: https://github.com/Slowbad/obsidian-solarized
=> Enable Solarized theme for v1.0.0

community-plugins.json
Link to my plugin: https://github.com/jglev/obsidian-paste-mode
The "Paste to Current Indentation" has been listed as a community plugin for some time, but has grown in functionality over several releases. With this in mind, I would like to rename the plugin to "Paste Mode."
=> Update name of plugin from "Paste to Current Indentation" to "Paste Mode"

community-plugins.json
https://github.com/joleaf/obsidian-dmn-plugin
=> Add dmn-plugin to Community Plugins

community-plugins.json
=> Fix typo in obsidian-structured-plugin

community-css-themes.json
I updated the theme a few days ago to support dark mode, so I added "dark" as a mode for it.
=> Add "dark" as a mode for Wikipedia Theme

community-plugins.json
Link to my plugin: https://github.com/jglev/obsidian-boost-link-suggestions
_(This plugin follows [this thread](https://discord.com/channels/686053708261228577/716028884885307432/1053860523646656563) in Discord.)_
=> Add "Boost Link Suggestions" plugin

community-plugins.json
rename plugin with id `cm-chs-patch` from `Word Splitting for Simplified Chinese in Edit Mode` to `Word Splitting for Simplified Chinese in Edit Mode and Vim Mode`
=> update name of existing plugin `cm-chs-patch`

community-plugins.json
Link to my plugin: https://github.com/ivre/obsidian-ivre-plugin
=> Add plugin: obsidian-ivre-plugin

.github/PULL_REQUEST_TEMPLATE/theme.md
Apparently, the `manifest.json` is required for themes to work, but it isn't listed as such here. see: https://discord.com/channels/686053708261228577/931552763467411487/1069862338162855986
=> Add information that `manifest.json` is required for themes

community-css-themes.json
Link to my theme: https://github.com/caro401/royal-velvet
=> update Royal Velvet theme (add light mode)

community-plugins.json
I changed : 
- The name and description of [Metacopy](https://github.com/Lisandra-dev/obsidian-metacopy/)
- The author of [Obsidian Github Publisher](https://github.com/ObsidianPublisher/obsidian-github-publisher), and the description of the plugin.
Thank you :D!
=> Update metacopy & Github Publisher description

community-css-themes.json
I renamed the theme, in order to not confuse anyone. I somewhat recently gave the user the freedom to choose their own accent color, such that the theme isn't limited to the red accent color anymore.
https://github.com/MajorEnkidu/solitude-obsidian-theme
=> Renamed theme

community-plugins.json
[I added the functionality to the BetterWordCount plugin](url), since it offers much more customizability. As a result, the footnote indicator plugin has been essentially sherlocked by the plugin, so that it can be removed from the community store.
Plugin repo is also already archived.
=> Remove Footnote indicator

community-plugins.json
With the new `eval` URI scheme from the Advanced URI plugin, this plugin's functionality can be achieved in a much more efficient and customizable manner, making this plugin pretty much obsolete: https://github.com/Vinzent03/obsidian-advanced-uri/issues/114
=> Remove Sidebar Toggler from the Community Store

community-plugins.json
I'm updating the description of 3 plugins and change the name of `Advanced Obsidian URI` to remove the unnecessary "Obsidian" phrase.
=> Update plugin descriptions

community-plugins.json
I am updating plugin description for "Double colon conceal" plugin due to latest changes - conceal works in editing view as well now.
Plugin: https://github.com/msrch/obsidian-double-colon-conceal
=> Update description for Double colon conceal plugin

community-css-themes.json
A theme to help people who are migrating from Notion. Could be used together with Make.md plugin or using other plugins like Banner.
[Link to my theme](https://github.com/diegoeis/obsidianotion)
=> Add Obsidianotion theme

community-plugins.json
Link to my plugin: [https://github.com/HyeonseoNam/obsidian-emoji-titler](https://github.com/HyeonseoNam/obsidian-emoji-titler)
=> Add emoji-titler

community-css-themes.json
Link to my theme:  https://github.com/ScottKirvan/GitHubDHC
=> add GitHubDHC theme to community themes list

community-css-themes.json
Link to my theme: https://github.com/lukasbach/obsidian-proper-dark
=> feat: add proper-dark theme

community-plugins.json
Since the new Obsidian release switches from starred notes to bookmarked notes, the plugin description has been adapted to reflect this change.
This is so users looking for plugins interacting with bookmarks will be able to find the plugin.
=> Update description of Grappling Hook

community-plugins.json
Changed github username, and therefore need to update name for Simple note quiz
=> Update name for Simple note quiz

community-plugins.json
I wanted to change the name, description and repository URL for my plugin.
Link to my plugin: https://github.com/scottwillmoore/obsidian-short-links
=> Update information for the short-internal-links-to-headings plugin

community-plugins.json
The following cleanup tasks were performed:
- Add a period at the end of descriptions
- Consistent capitalization for trademarks such as `Obsidian`
- Remove emoji from descriptions
- Fixed spelling and grammar errors
- Reduced redundant "This plugin" preface text
- Indentation inconsistencies
=> Cleanup tasks for plugin descriptions

community-css-themes.json
This inconsistent slash tripped up my theme downloader - I'm hoping the inconsistency can be fixed here, to save me working around it in the code...
See https://github.com/claremacrae/obsidian-repos-downloader/issues/20
I checked there were no other occurrences.
=> Fix inconsistent trailing slash for obsidian-material-flat-theme

community-css-themes.json
Repo URL: https://github.com/arozx/obsidian_tokyo-night-storm
My repo contains all required files.
-    manifest.json
-    theme.css
-    The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
I have indicated which modes (dark, light, or both) are compatible with my theme.
My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my README.md.
=> Add TokyoNight Storm theme

community-plugins.json
Sorry for the confusion, I recently changed my account name and have noticed that this has caused issues with the plugin stat auto-update. Therefore, I am submitting a pull request to update my repository URL to reflect the new account name.
Link to my plugin: https://github.com/ytliu74/obsidian-pseudocode
=> Update repo stat for Pseudocode plugin

community-css-themes.json
A dark obsidian theme that is designed to make it hard for people to read over your shoulder.
[Link to my theme: ](https://github.com/schrunchee/obsidian-covert-theme)
- [✓ ] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [✓ ] `manifest.json`
- [✓ ] `theme.css`
- [✓ ] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [✓ ] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [✓ ] I have added a license in the LICENSE file.
- [ ✓] My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my `README.md`.
=> Add Covert Obsidian Theme

community-plugins.json
Link to my plugin: [mvgrimes/obsidian-todotxt-plugin](https://github.com/mvgrimes/obsidian-todotxt-plugin)
=> Add TodoTxt plugin

community-plugins.json
Here is the my new repo URL:
https://github.com/trey-wallis/obsidian-dashboards
I didn't change the id because I want to retain my download count
=> Rename Notion-Like Tables to Dashboards

community-plugins.json
Link to my plugin: [rkosova/obsidian-markdown-link-space-encoder](https://github.com/rkosova/obsidian-markdown-link-space-encoder)
- [ x]  Linux
- [ x] I have read the tips in https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md and have self-reviewed my plugin to avoid these common pitfalls.
- [ x] My project respects and is compatible …
=> Add Markdown Link Space Encoder plugin

community-css-themes.json
I've changed my GitHub username to Carbonateb, this pr makes my theme (Encore) point to the canonical repository url instead of relying on GitHub's automatic redirect which is less reliable by nature.
=> Community themes: Renamed user Maldonacho to Carbonateb

community-plugins.json
The plugin is currently here located: https://github.com/phibr0/cycle-through-panes
Because I'm now mainly maintaining that plugin, @phibr0 transfers the repo to my account. In addition, I'm renaming it. I haven't accepted the transfer yet, but will do so immediately after this pr is merged to prevent any issues with a missing repo.
=> Rename Cycle Through Panes to Tab Switcher

community-plugins.json
The overall functionality of the plugin has changed since collapse/expand all is part of core now.
=> update Collapse All plugin description

community-plugins.json
PR to remove my plugin.
My plugin was a workaround for an issue which has been fixed in obsidian 1.0.1.
=> remove System Theme plugin

community-plugins.json
The creator of `obsidian-day-planner` showed up after a long break. He noticed that I'd been working on a fork, so he transferred the original repo to me, so that there is only one updated version of the plugin in the list.
This is a tiny change to fix the error when trying to download the plugin from the community plugins list.
Here is a link to the same plugin repo by the new address: https://github.com/ivan-lednev/obsidian-day-planner
=> Update community-plugins.json after repo owner changed

community-plugins.json
Add the alternate day-planner plugin, with some text modifications to disambiguate between the two (where one is adding new features and capabilities, and the other is hewing closer to the original behavior).
@ivan-lednev .. LMK what you think.
Note: They are now separated in the file, but I still have the proposed changes (with agreement below).
Link to my plugin: https://github.com/ebullient/obsidian-day-planner-og
=> Add Day Planner (OG)

community-plugins.json
Link to my plugin: https://github.com/TS-Tobias/obsidian-no-tabs
=> Remove Obsidian No Tabs Plugin

community-plugins.json
Due to a trademark issue I had to rename my Chrome extension from LinkShelf to LinkStowr. This PR updates the name and repo in the Community Plugins list to also reflect the name change. I left the id the same so that existing users can still receive updates.
=> Update LinkShelf to LinkStowr in community-plugins.json

community-plugins.json
Hopefully, the formatting of the other lines is ok. If not I can undo this.
Link to my plugin: https://github.com/FlorianWoelki/obsidian-iconize
=> Rebrand Obsidian Icon Folder to Iconize

plugin-review.md
Google still has the old location `plugin-review.md` advice quite high in search results, so instead of the old location 404'ing, make it point to the new location.
---
I was going to put this in Discord #plugin-dev - and then realised that offering a PR would be kinder... 😄 
> I'm trying to find the Review guidelines for plugins...
> Google took me here, which is a 404:
> <https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md>
> 
> I looked here to see if it linked to them, and couldn't see it:
> <https://docs.obsidian.md/Plugins/Releasing/Submit+your+plugin>
> 
> Oh, found it here - and there are no backlinks to it:
> https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines
> 
> It would be really lovely if the old page could point to the new, instead of …
=> Reinstate plugin-review.md and link to new location

community-plugins.json
This PR is for matching `community-plugins.json` to the updated description in `manifest.json` in my repo.
https://github.com/RyotaUshio/obsidian-math-booster/blob/master/manifest.json
=> Update Math Booster plugin's description

community-plugins.json
I'm removing this plugin from the repository as I don't plan on maintaining it any longer and I'm deprecating this username, because I am constantly tagged in various Doc formats as an invariant which makes it too noisy to keep this account. The plugin has been archived.
=> Remove invariant/obsidian-archivebox-plugin

community-plugins.json
Hello, my fork of the "Remotely Save" plugin was previously called Remotely Secure and merged in this pull request: https://github.com/obsidianmd/obsidian-releases/pull/2523
After [discussion](https://github.com/sboesen/remotely-sync/issues/32) the name "Remotely Sync" better describes its behavior. Specifically: the name "Remotely Secure" doesn't make it obvious what the plugin does, and as I've learned many of our users don't even use encryption which is where the security updates were. Please let me know if I can share any additional details, thank you!
=> Change name & repo of submitted plugin Remotely Secure to Remotely Sync

community-plugins.json
I found a typo in the description of my plugin [Quick Preview](https://github.com/RyotaUshio/obsidian-quick-preview), both in `manifest.json` and `community-plugins.json`.
I've already fixed `manifest.json` in my repository. https://github.com/RyotaUshio/obsidian-quick-preview/blob/main/manifest.json
Thank you!
=> Fix typo in the description of Quick Preview plugin

community-plugins.json
I want to rename [my plugin called "Math Booster"](https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer) to "LaTeX-like Theorem & Equation Referencer" for better clarity and discoverability.
Backgrounds can be found here: https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer/issues/210
Note that the [latest release](https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer/releases/tag/2.2.0) already uses the [new manifest](https://github.com/RyotaUshio/obsidian-latex-theorem-equation-referencer/blob/a28ef21c5df044d5e9c31f274ba76102a88d3749/manifest.json).
=> Rename Math Booster plugin to LaTeX-like Theorem & Equation Referencer

community-plugins.json
I've renamed my github account and updated all my plugin readmes and manifests accordingly. Now doing the same for my previously released plugins here.
=> Rename author and update repo for OfficerHalf plugins

community-plugins.json
rename from "Todo.txt Codeblocks" to "TodoTxt Codeblocks" to make it more searchable
=> rename to "TodoTxt Codeblocks"

community-css-themes.json
Adding the light theme that was implemented.
[Link to my theme](https://github.com/DMeurer/improved-potato)
=> Add light theme option

community-plugins.json
Updated the plugin description to include the term "waypoints" after discovering that many people have searched for the plural of waypoint in the plugin explorer and not found it listed. Note that waypoints refers to the maps of content that you can use to link files in a folder together.
=> Update description for Waypoint plugin

community-css-themes.json
finally a fully black monochrome theme
https://github.com/ZeChArtiahSaher/obsidian-mono-black
=> Add theme: mono black (monochrome, charcoal)

community-plugins.json
see: https://github.com/NomarCub/obsidian-copy-url-in-preview/releases/tag/1.6.0
The PR template didn't work for me, point me to what I need to do, if anyting.
=> remove mention of copy URL functionality, rename plugin and reword description

community-plugins.json
The repo at [verocloud/obsidian-mindmap-nextgen](https://github.com/verocloud/obsidian-mindmap-nextgen) has moved to `james-tindal/obsidian-mindmap-nextgen`
=> Change repo url for Mindmap Nextgen plugin

community-plugins.json
https://github.com/Cutaiar/obsidian-song-links
I recently had to change the name of "Spotify Links" to "Song Links" to make my plugin comply with the Spotify Brand Guidelines. I've kept the id the same as not to break any connections, but the display name mustn't mention "Spotify".
=> Rename Plugin: "Spotify Links" -> "Song Links"

community-plugins.json
Per the Obsidian team's request, I am submitting a new name for my plugin. I have published a new version of my plugin with the name changed everywhere along with some bug fixes.
=> Update community-plugins.json with new name for "jTab" plugin

community-plugins.json
1. The current plugin name can no longer cover existing functions.
2. Prepare for adding more features later.
3. Fits with the existing official website: https://obsidian-life-os.netlify.app/
=> Rename periodic para plugin

community-plugins.json
Most of the plugin's features have been implemented by Obsidian core by now. The few features that are not part of core are available by via other plugins.
A deprecation notice has been there at the plugin's readme for a few months now.
Will archive the repo when this PR is merged.
=> archive "Smarter Markdown Hotkeys"

community-plugins.json
Link to my plugin: https://github.com/Caffa/Obsidian-Current-Folder-Note-Display-Plugin
I have given proper attribution to these other projects in my `README.md`. [X]
=> Add plugin: Current Folder Notes

community-plugins.json
Adding External Links plugin
Link to my plugin: https://github.com/jivimberg/external-links
=> Add plugin: External Links

community-plugins.json
Link to my plugin: https://github.com/twofive-labs/target-word-count
=> Add plugin: Target Word Count

community-plugins.json
=> Add plugin: Alias Picker

community-plugins.json
Link to my plugin: https://github.com/codeonquer/obsidian-sync-config-folder-to-common-folder
=> Add plugin: Sync config folder to common folder

.github/workflows/stale.yml
Not a plugin or theme PR. This upgrades the `stale` action to v9, because the action is [running out of operations](https://github.com/obsidianmd/obsidian-releases/actions/runs/8579626949/job/23514812480) and [v9 explicitly fixes this](https://github.com/actions/stale/releases/tag/v9.0.0)
=> Upgrade stale action to fix running out of operations

community-plugins.json
I'm creating a PR to update UNITADE's manifest information (if it's possible).
Link to my plugin: https://github.com/Falcion/UNITADE.md
=> chore(plugininfo-update): update name, desc and link of plugin UNITADE

community-plugins.json
added canvas2document
Link to my plugin: https://github.com/slnsys/obsidian-canvas2document
- [ x]  Windows
- [ x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [ x] I have read the tips in …
=> Add plugin: Canvas2Document

community-plugins.json
I've created my first Obsidian plugin which works in a development vault and I'd like to submit it to the directory.
Link to my plugin: https://github.com/Fleker/letterboxd-for-obsidian
- [~] `styles.css` _(optional)_
=> Add plugin: Letterboxd Diary RSS Sync

community-plugins.json
Link to my plugin: https://github.com/palfrey/obsidian-random-names
=> Add plugin: Random names

community-plugins.json
https://github.com/trey-wallis/obsidian-note-splitter
=> Add plugin: Note Splitter

community-plugins.json
simple plugin to generate a pseudorandom hash
Link to my plugin: https://github.com/zigahertz/obsidian-generate-hash
=> Add plugin: Generate Hash

community-plugins.json
Link to my plugin: https://github.com/aaronczichon/obsidian-location-plugin
---
Called the id `mapbox-location` instead of `mapbox-location-image` as future version should also include interactive map.
=> Add plugin: Mapbox Location Image

community-plugins.json
Link to my plugin: https://github.com/beardicus/obsidian-draft-indicator-plugin
=> Add plugin: Draft Indicator

community-plugins.json
Link to my plugin: https://github.com/srz2/obsidian-azure-devops-linker
=> Add plugin: Azure DevOps Linker

community-plugins.json
Link to my plugin: https://github.com/RavenHogWarts/obsidian-custom-icons
I've expanded the plugin's capabilities, introducing customization options for folder icons alongside its original document icon customization feature.
The added functionality greatly broadens the plugin's applicability, making "Custom Icons" a more fitting name. It accurately reflects the plugin's enhanced utility in personalizing both documents and folders, offering a unified customization experience.
=> Rebrand Custom Sidebar Icons to Custom Icons

community-plugins.json
this PR updates the link to the repo for obsidian-full-calendar to reflect that it has been moved to obsidian-community.
=> update the repo link for obsidian-full-calendar

community-plugins.json
Link to my plugin: https://github.com/RobTheFiveNine/obsidian-gdscript
=> Add plugin: GDScript Syntax Highlighting

community-plugins.json
Link to my plugin: https://github.com/HaloGamer33/Obsidian-Fuzzy-Note-Creator
=> Add plugin: Fuzzy Note Creator

community-plugins.json
https://github.com/ichichikin/obsidian-plugin-interactivity
=> Add plugin: Interactivity

community-plugins.json
The project was renamed to have a better understanding and difference between the Obsidian team and me, preventing confusion between publisher and publish project.
I hope it's okay!
Thanks.
=> [author]: Change Obsidian GitHub Publisher to Enveloppe

community-plugins.json
Link to my plugin: https://github.com/ycnmhd/obsidian-lineage
=> Add plugin: Lineage

community-plugins.json
Link to my plugin: https://github.com/xhuajin/obsidian-settings-management
=> Add plugin: Settings Management

community-plugins.json
Link to my plugin: https://github.com/IsaiaScope/smart-html-select-plugin.git
=> Add plugin: Smart HTML Select

community-plugins.json
Link to my plugin: https://github.com/xhuajin/obsidian-file-preview
=> Add plugin: File Preview

community-plugins.json
Link to my plugin: https://github.com/mara-li/obsidian-regex-mark
=> Add plugin: Regex Mark

community-plugins.json
Link to my plugin: https://github.com/nancyel/header-counter
=> Add plugin: Header Counter

community-plugins.json
Link to my plugin: https://github.com/aygjiay/obsidian-link-to-verse
=> Add plugin: Link to Verse

community-plugins.json
Link to my plugin: https://github.com/gapmiss/obsidian-vault-name
=> Add plugin: Vault Name

community-plugins.json
https://github.com/jonashaefele/audiopen-obsidian/
=> Add plugin: AudioPen Sync

community-plugins.json
[obsidian-pt-url-helper](https://github.com/kndshein/obsidian-pt-url-helper/tree/0.1.0)
=> Add plugin: Pivotal Tracker URL Helper

community-plugins.json
added plugin
https://github.com/agctute/relative-timestamps
=> Add plugin: Relative Timestamps

community-plugins.json
Link to my plugin: https://github.com/patrickchiang/obsidian-headings-in-explorer
=> Add plugin: Headings in Explorer

community-plugins.json
Link to my plugin: https://github.com/typhoon-kim/obsidian-svelte-syntax-highlighter
=> Add plugin: Svelte Syntax Highlighter

community-css-themes.json
[Material Design](https://material.io) inspired theme that creates [dynamic color](https://codepen.io/Rody-Davis/pen/LYojpXB?editors=1111) palettes based on the current user selected [accent color](https://docs.obsidian.md/Reference/CSS+variables/Foundations/Colors#Accent+color).
Supports light and dark mode.
=> Add theme: Dynamic Color

community-plugins.json
Link to my plugin: https://github.com/drichardson/obsidian-toggle-readable-line-length
=> Add plugin: Toggle Readable line length

community-plugins.json
Adds an entry in the community-plugins.json file for the Definition List plugin.
Link to my plugin: https://github.com/shammond42/definition-list
- [X ] I have tested the plugin on
=> Add plugin: Definition List

community-plugins.json
Link to my plugin: https://github.com/ljcoder2015/obsidian-sheet-plus
=> Add plugin: Sheet Plus

community-plugins.json
Link to my plugin: https://github.com/Voidgrown/obsidian-asciidoc
=> Add plugin: Asciidoc Reader

community-plugins.json
Link to my plugin: https://github.com/zhouhua/obsidian-sticky-headings
=> Add plugin: Another Sticky Headings

community-plugins.json
Syrinscape is a TTRPG tool for ambient sounds. This plugin will allow GMs to control the Syrinscape online player from inside of notes, triggering moods and one-shot sounds.
Link to my plugin: https://github.com/scooper4711/obsidian-syrinscape
=> Add plugin: Syrinscape Online Player

community-plugins.json
new plugin
Obsidian Wechat public Plugin  is a plugin to release article from your Obsidian Vault.
Link to my plugin:  https://github.com/ai-chen2050/obsidian-wechat-public-platform
=> Add plugin: Wechat Public Platform

community-plugins.json
Link to my plugin: https://github.com/stroiman/obsidian-dev-publish
=> Add plugin: Publish to DEV

community-plugins.json
This pull request adds the File Flex plugin, which provides customisable undo functionality for file and folder movements and renames within Obsidian. Users can easily revert changes to their vault structure with a single click and/or hotkey.
Link to my plugin: https://github.com/19msb/obsidian-file-flex
=> Add plugin: File Flex

community-plugins.json
Link to my plugin: https://github.com/kapej42/obsidian-todoist-indicator
-  [x] I have added a license in the LICENSE file.
=> Add plugin: Todoist Indicator

community-plugins.json
Link to my plugin: https://github.com/alberti42/obsidian-import-attachments-plus
=> Add plugin: Import Attachments+

community-plugins.json
Link to my plugin: https://github.com/joycode-hub/datepicker-plugin.git
=> Add plugin: Datepicker

community-plugins.json
The plugin is currently here located: https://github.com/denolehov/obsidian-git
Since I'm maintaining that plugin for 3 years already, @denolehov will transfer the repo to my account. I haven't accepted the transfer yet, but will do so immediately after this pr is merged to prevent any issues with a missing repo.
=> Move obsidian-git plugin to Vinzent03

community-css-themes.json
Link to my theme: https://github.com/WinnerWind/gummy-revived
=> Add theme: Gummy-Revived

community-plugins.json
I re-create pull request again because after merge #3814, my plugin not included for release to community
---
Link to my plugin: https://github.com/hardingadonis/hash-pasted-image
=> Add plugin: Hash Pasted Image

community-plugins.json
Link to my plugin: https://github.com/gfxholo/iconic
=> Add plugin: Iconic

community-plugins.json
Link to my plugin: https://github.com/observerw/obsidian-code-link
=> Add plugin: Code Link

community-plugins.json
Adding the Index Notes plugin
Link to my plugin: https://github.com/adanielnoel/obsidian-index-notes
=> Add plugin: Index Notes

community-css-themes.json
Add light mode support
Link to my theme: https://github.com/GustavoSZ124/Obsidian-Theme-Seamless-View
=> Add light mode support to my theme Seamless View

community-plugins.json
Link to my plugin: https://github.com/zhouhua/obsidian-popkit
=> Add plugin: PopKit

community-plugins.json
Link to my plugin: https://github.com/wrenger/obsidian-languagetool
=> Add plugin: LanguageTool

community-plugins.json
Link to my plugin: https://github.com/jason-lieb/obsidian-browser-interface-plugin
=> Add plugin: Browser Interface

community-plugins.json
=> Add plugin: Chinese Calendar

community-plugins.json
Link to my plugin: https://github.com/alexeiskachykhin/obsidian-image-metadata-plugin
=> Add plugin: Image Metadata

community-plugins.json
Add Lite Gallery plugin
Link to my plugin: https://github.com/jpoles1/obsidian-litegal/
=> Add plugin: Lite Gallery

community-plugins.json
This is being done with the agreement of:
- the original author, Martin Schenck (@schemar)
- co-maintainer Ilyas Landikov (@ilandikov)
Martin is retained as the third author, via `(created by Martin Schenck)`.
(I note that some other multi-owner plugins have used `original by`, but that seems to be for forks of an original, whereas Tasks is still the same plugin, with ownership just transferred to an organisation  in 2022 to permit onward maintenance...)
=> Update Tasks plugin authors

.github/PULL_REQUEST_TEMPLATE/plugin.md
When I (Mark Fowler) did my initial release I didn't realize that that individual files needed to be released, not just included in the source tarball.
I'm suggesting this update to the pull request template to hopefully avoid someone else having the same problem.
=> Improve description of files needed in releases

community-plugins.json
Link to my plugin: [https://github.com/nickrallison/obsidian-note-linker-with-previewer/](https://github.com/nickrallison/obsidian-note-linker-with-previewer/)
=> Add plugin: Note Linker with Previewer

community-plugins.json
Link to my plugin: https://github.com/mlprt/obsidian-paste-as-embed
=> Add plugin: Paste as Embed

community-plugins.json
Heading Toggler is a plugin that allows you to easily toggle heading levels in Markdown documents with shortcuts.
Link to my plugin: <https://github.com/Lord-Turmoil/heading-toggler-obsidian>
> I only have a Windows PC so I'm not able to test it on other OS. But I see no possible incompatibility for it is simple enough.
=> Add plugin: Heading Toggler

community-plugins.json
Link to my plugin: https://github.com/revolter/obsidian-share-via-notepad-tab-plugin
=> Add plugin: Share via Notepad Tab

community-plugins.json
Added my new plugin obsidian-marker which can convert PDFs to rich Markdown, embedding images and recognizing tables, headings and more! Also works on mobile!
Link to my plugin: [obsidian-marker](https://github.com/L3-N0X/obsidian-marker)
=> Add plugin: Marker PDF to MD

community-plugins.json
Link to my plugin: https://github.com/logonoff/obsidian-inline-spoilers
=> Add plugin: Inline spoilers

community-plugins.json
Link to my plugin: https://github.com/technerium/obsidian-vault-size-history
=> Add plugin: Vault Size History

community-plugins.json
Adds a plugin to write what file obsidian is currently looking at to an external file every time this changes
Link to my plugin: https://github.com/2shortplanks/current-file
=> Add plugin: Current File

community-plugins.json
Link to my plugin: https://github.com/tyler-dot-earth/obsidian-blockreffer
=> Add plugin: Blockreffer

community-css-themes.json
Link to my theme: https://github.com/chrisgrieser/shimmering-focus
Switch to use `webp` as image file format. Image filesize is more than halved, while the resolution/quality is the same.
(Might actually recommend themes to use webp screenshots in general, btw?)
=> Update: Shimmering Focus screenshot file

community-plugins.json
Rename Plugin: "Note to MP" -> "NoteToMP"
I found that when searching with the plugin name "Note to MP" there are many other plugins in the search results. Therefore, I want to change the plugin name to "NoteToMP" which should make it easier to find.
=> Rename Plugin: "Note to MP" -> "NoteToMP"

community-plugins.json
Adding KeepSidian Plugin
Reopening PR closed by mistake: https://github.com/obsidianmd/obsidian-releases/pull/3929
Link to my plugin: https://github.com/lc0rp/KeepSidian
- [-] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
[X] I have given proper attribution to these other projects in my `README.md`.
=> Add plugin: KeepSidian

community-plugins.json
Link to my plugin: https://github.com/muckmuck96/obsidian-file-share
=> Add plugin: File Share

community-plugins.json
Link to my plugin: https://github.com/alangrainger/obsidian-lazy-plugins
This plugin is similar to `obsidian-plugin-groups` in the store, however [that plugin is no longer under development](https://github.com/Mocca101/obsidian-plugin-groups/issues/41#issuecomment-1907752889), as confirmed by the plugin owner.
This plugin is also significantly more simple, and should be compatible with Obsidian long into the future.
It has [some good feedback on Reddit](https://www.reddit.com/r/ObsidianMD/comments/1ekea52/install_this_plugin_loader_to_make_your_obsidian/) already.
.
=> Add plugin: Lazy Plugin Loader

community-plugins.json
Link to my plugin: https://github.com/Opisek/obsidian-battery-indicator
=> Add plugin: Battery Indicator

community-plugins.json
Adding virustotal-enrich.
Link to my plugin: https://github.com/ytisf/virustotal-enrich
=> Add plugin: Virus Total Enrichment

community-plugins.json
The plugin was originally developed to enable users to use Google Bard in Obsidian. Google Bard has now been replaced with gemini and a completely different api, so the plugin has also been completely reworked to adapt to those changes.
This includes also a name change: from "Talk with Bard" to "Gemini AI Assistant"
Would it be possible to make the changes so that the plugin is updated in the obsidan community plugins, or should I create and submit a new plugin alltogether?
=> Update Chat with bard plugin

community-plugins.json
Link to my plugin: https://github.com/chasebank87/import-github-readme
=> Add plugin: Import GitHub Readme

community-plugins.json
My plugin now also supports all sorts of other wikis and even though the plugin name suggest it only works with the Wikipedia I at least wanted to tweak the description a bit to communicate that it now also supports more.
=> Change wikipedia search description

community-plugins.json
Add Draw Steel Elements Plugin
Link to my plugin: https://github.com/scottTomaszewski/draw-steel-elements
=> Add plugin: Draw Steel Elements

community-plugins.json
Link to my plugin: https://github.com/justanotherjurastudent/highlight-active-folder-section
=> Add plugin: Highlight active folder section

community-plugins.json
Link to my plugin: https://github.com/ckep1/obsidian-AutoPause
=> Add plugin: AutoPause

community-plugins.json
Link to my plugin: https://github.com/isdmg/obsidian-remove-unused-block-ids
=> Add plugin: Remove Unused Block IDs

community-plugins.json
Added kocheck/obsidian-figma-viewer plugin to community plugins.
Link to my plugin: [kocheck/obsidian-figma-viewer](https://github.com/kocheck/obsidian-figma-viewer)
=> Add plugin: Figma Embed

community-plugins.json
Link to my plugin: https://github.com/Signynt/obsidian-editing-mode-hotkey
=> Add plugin: Editing Mode Hotkey

community-plugins.json
This plugin for [Obsidian](https://obsidian.md/) minimizes the application window to the dock or taskbar when all open panes are closed. This behavior is particularly standard on macOS and can now be optionally applied across all platforms.
Link to my plugin: https://github.com/alberti42/obsidian-minimize-on-close
=> Add plugin: Minimize on Close

community-plugins.json
Link to my plugin: https://github.com/AnAngryRaven/obsidian-open-sidebar-on-hover
=> Add plugin: Open Sidebar on Hover

community-plugins.json
Link to my plugin: https://github.com/namikaze-40p/obsidian-command-tracker
=> Add plugin: Command Tracker

community-plugins.json
Link to my plugin: [josmarcristello/Obsidian-Find-Orphaned-Images](https://github.com/josmarcristello/Obsidian-Find-Orphaned-Images)
=> Add plugin: Find Orphaned Images

community-plugins.json
Link to my plugin: https://github.com/likemuuxi/obsidian-modal-opener
=> Add plugin: Modal Opener

community-plugins.json
rename / rebrand `Pexels-Banner` to `Pixel-Banner`
old repo: https://github.com/jparkerweb/pexels-banner
rename repo: https://github.com/jparkerweb/pixel-banner
---
As I now support more than just the "Pexels" API it is fitting to update the Plugin name to be more generic.
Thank you :)
=> Update plugin: Pexels Banner

community-css-themes.json
Oozy Theme Repository no longer exists.
=> Remove Oozy Theme

community-plugins.json
Hello, 
I created the findoc plugin a while ago, 
I am cleaning up my github organizations and moving everything to my main account "studiowebux".
So this PR is only renaming the repo url.
Can I move my repo before your approval ? 
Thanks you !
=> Update: Move obsidian-findoc repo to studiowebux github organization

community-plugins.json
Add Japanese Novel Ruby plugin
Link to my plugin: https://github.com/k-quels/japanese-novel-ruby
=> Add plugin: Japanese Novel Ruby

community-plugins.json
Link to my plugin: https://github.com/dzruyk/obsidian-asciidoc
=> Add plugin: Asciidoctor editor

community-plugins.json
Link to my plugin:  https://github.com/NilsLeo/obsidian-youtube-iframe-timestamps
=> Add plugin: Youtube Iframe Timestamps

community-plugins.json
Link to my plugin: https://github.com/gitcpy/obsidian-diagram-popup
=> [Update]: rename mermaid popup to diagram popup

community-plugins.json
The UNITADE plugin has received a massive update and its current description is no longer up to date, the description now includes elements of the old one and explains the new functionality in brief.
Link to my plugin: https://github.com/Falcion/UNITADE.md
=> Description change: update UNITADE's plugin description because of it's update

community-plugins.json
I'm transitioning and it would be nice to be able to have my name change be reflected for the plugin I have named under my old name.
=> Name Change : AndreasSasDev to AnnaSasDev

community-plugins.json
https://github.com/msgk239/obsidian-copy-image-text
- [ x ]  Windows
- [ x ] `main.js`
- [ x ] `manifest.json`
- [ x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ x ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [ x ] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [ x ] I have added a license …
=> Add plugin: 复制图文 (Copy Image Text)

community-plugins.json
Add plugin "vault-full-statistics" and formatting file.
Link to my plugin: https://github.com/jtprogru/obsidian-vault-full-statistics-plugin/
=> Add plugin: Vault Full Statistics

community-plugins.json
Link to my plugin: https://github.com/Telehakke/jisage-japanese-indentation
=> Add plugin: Jisage -Japanese Indentation-

community-plugins.json
Link to my plugin: [obsidian-open-with-nldates](https://github.com/charliecm/obsidian-open-with-nldates)
=> Add plugin: Open with Natural Language Dates

community-plugins.json
Link to my plugin: https://github.com/BogdanCodreanu/obsidian-moc-link-helper
- **Plugin is desktop only**
=> Add plugin: MOC Link Helper

community-plugins.json
Description from the original repository:
> Obsidian SVG Styler is a simple plugin designed to help you easily modify the style properties of SVG images directly within the editor. With this plugin, you can customize properties like color, border, opacity, and more. Supported drawable tags include: `path`, `line`, `rect`, `circle`, `ellipse`, and `polygon`.
[arg1998/obsidian-svg-styler](https://github.com/arg1998/obsidian-svg-styler)
=> Add plugin: SVG Style Editor

community-plugins.json
Add obsidian-gemini plugin.
Link to my plugin: https://github.com/allenhutchison/obsidian-gemini
=> Add plugin: Gemini Scribe

community-plugins.json
Added File Manager plugin.
Link to my plugin: https://github.com/jfsicilia/obsidian-file-manager
=> Add plugin: File Manager

community-plugins.json
Link to my plugin:  [https://github.com/felipetappata/obsidian-link-preview](https://github.com/felipetappata/obsidian-link-preview)
=> Add plugin: Link Preview

community-plugins.json
Link to my plugin: https://github.com/GitGorman/weekly-goal-tracker/tree/master
=> Add plugin: Weekly Goal Tracker

community-plugins.json
Link to my plugin: https://github.com/Masterb1234/obsidian-post-webhook/ 
- [ v] I have tested the plugin on
- [ v]  Windows
- [ v]  macOS
- [ v]  Linux
- [ v]  Android _(if applicable)_
- [ v]  iOS _(if applicable)_
- [ v] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
- [v ] `main.js`
- [v] `manifest.json`
- [ v] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [v ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [v ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ v] I have read the developer policies at …
=> Add plugin: Post Webhook

community-plugins.json
Link to my plugin: https://github.com/SteveOverSea/obsidian-folder-links
=> Add plugin: Folder Links

community-plugins.json
Link to my plugin: [https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink](https://github.com/Hoshino-Yumetsuki/obsidian-plugin-abbrlink)
=> Add plugin: Abbrlink

community-plugins.json
Link to my plugin: [https://github.com/friebetill/obsidian-share-as-zip](https://github.com/friebetill/obsidian-share-as-zip)
=> Add plugin: Share as ZIP

community-css-themes.json
This PR updates the location of the cover image used in the theme from `assets/cover.png` to `cover.png`
=> Update Cover Image Path in Theme Files

community-plugins.json
Add Cypher Plugin - Icon-Based Text Transformation for Obsidian
This pull request adds the **Cypher Text Plugin** to the Obsidian community plugins repository. The plugin allows users to toggle between normal text and icon-based cyphered text, providing a fun way to obscure or visually enhance their notes.
**Repo URL**: [Cypher Text Plugin Repository](https://github.com/aths7/cypher)
**Link to Plugin**: [Obsidian Plugin Directory](https://github.com/aths7/cypher)
---
- **Platform Testing**:
- **GitHub Release Contents**:
- **Versioning and IDs**:
- **README**:
- **Developer Policies**:
- **Guidelines and Common Pitfalls**:
- **Licensing**:
=> Add plugin: Cypher

community-plugins.json
Update description to better reflects plugins capabilities and allow to find it easier.
https://github.com/xRyul/obsidian-image-converter
=> Update Image Converter description in community-plugins.json

community-plugins.json
Link to my plugin: https://github.com/pahkey/obsidian-wikidocs-plugin
=> Add plugin: WikiDocs

community-plugins.json
Add link formatter plugin
Link to my plugin: https://github.com/dilantha/link-formatter
=> Add plugin: Link Formatter

community-plugins.json
Link to my plugin: https://github.com/Mithadon/obsidian-color-folders-files
=> Add plugin: Color Folders and Files

community-plugins.json
Link to my plugin: https://github.com/jacoblearned/obsidian-template-by-note-name
=> Add plugin: Template by Note Name

community-plugins.json
Link to my plugin: [ArhiChief/obsidian-note-from-form](https://github.com/ArhiChief/obsidian-note-from-form)
=> Add plugin: Note From Form

community-plugins.json
https://github.com/Mikodin/obsidian-scribe
=> Add plugin: Scribe

community-plugins.json
Hey, I just updated my plugin but I realized that it's not being updated in the community plugins tab due to my GitHub username being different.
Here's the old PR for reference, you are free to do a new check of course. I've filled out the form below accurately.
https://github.com/obsidianmd/obsidian-releases/pull/2447
Link to my plugin: https://github.com/0x-DLN/obsidian-table-checkboxes
=> Updated github username

community-css-themes.json
Add the Emerald-Echo theme
Link to my theme:  https://codeberg.org/MalcolmMielle/Emerald-Echo
(Also mirrored on Github: https://github.com/MalcolmMielle/Emerald-Echo but wondering if it's possible to only use Codeberg instead)
=> Add theme: Emerald Echo

community-plugins.json
Link to my plugin: https://github.com/mnaoumov/obsidian-insert-multiple-attachments
=> Add plugin: Insert Multiple Attachments

community-plugins.json
Link to my plugin: [vpcano/obsidian-smart-link-alias](https://github.com/vpcano/obsidian-smart-link-alias)
=> Add plugin: Smart Link Alias

community-plugins.json
The plugin now does way more than the name says, so it is not as discoverable by the users.
From what I understood, I have to keep the plugin id, even if it doesn't match the rebranded plugin name.
=> Rebrand `Fix Require Modules` plugin to `CodeScript Toolkit`

community-plugins.json
Link to my plugin: https://github.com/skye-z/ons
=> Add plugin: BetaX NAS Sync

community-plugins.json
https://github.com/oylbin/obsidian-external-file-embed-and-link
=> Add plugin: External File Embed and Link

community-plugins.json
There was a Typo in the repo name:
obisdian-fast-text-color
i corrected the name and need to update the link to 
obsidian-fast-text-color
=> Change typo in repo name for obsidian-fast-text-color

community-css-themes.json
Link to the theme: 
https://github.com/technerium/obsidian-ukiyo
I kept the theme name and version in sync with the original to ensure the change is transparent for users. Please let me know if anything needs to be adjusted in that regard.
=> Add theme: Ukiyo

community-plugins.json
Link to my plugin: https://github.com/frankolson/obsidian-bujo-bullets
=> Add plugin: BuJo Bullets

community-plugins.json
Link to my plugin: https://github.com/theopavlove/obsidian-dynamic-outline
=> Add plugin: Dynamic Outline

community-plugins.json
Link to my plugin: https://github.com/Diego-Viero/Syncthing-status-icon-Obsidian-plugin
=> Add plugin: Syncthing status icon

community-plugins.json
Link to my plugin: https://github.com/t5k6/obsidian-koreader-highlights
=> Add plugin: KoReader Highlight Importer

community-plugins.json
Link to my plugin:https://github.com/woodchen-ink/obsidian-publish-to-discourse
=> Add plugin: Publish to Discourse

community-plugins.json
Adds [clojure-plugin-host](https://github.com/farcaller/obsidian-clojure-plugin-host/releases/tag/0.1.0)
Link to my plugin: https://github.com/farcaller/obsidian-clojure-plugin-host
=> Add plugin: Clojure Plugin Host

community-plugins.json
Link to my plugin: https://github.com/pycalc-plugin/obsidian
=> Add plugin: pycalc

community-plugins.json
Link to my plugin: https://github.com/mnaoumov/obsidian-frontmatter-markdown-links
=> Add plugin: Frontmatter Markdown Links

community-css-themes.json
Link to my theme: https://github.com/iwa/Sei
=> Add theme: Sei

community-plugins.json
Link to my plugin: https://github.com/rca-umb/anchor-link-display-text
=> Add plugin: Anchor Link Display Text

community-plugins.json
Link to my plugin: https://github.com/Talal-A/obsidian-paperless
=> Add plugin: Paperless

community-plugins.json
> # I am submitting a new Community Plugin
> ## Repo URL
> Link to my plugin:
> https://github.com/Lemon695/obsidian-missing-link-file-creator
> 
> ## Release Checklist
> * [x]  I have tested the plugin on
>   
>   * [ ]   Windows
>   * [x]   macOS
>   * [ ]   Linux
>   * [ ]   Android _(if applicable)_
>   * [x]   iOS _(if applicable)_
> * [x]  My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
>   
>   * [x]  `main.js`
>   * [x]  `styles.css` _(optional)_
> * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
> * [x]  该 `id` in my `manifest.json` matches the `id` 在 `community-plugins.json` …
=> Add plugin: Missing Link File Creator

community-css-themes.json
As I have developed a new theme called "Vortex," I am officially removing the "Luminex" theme from the Obsidian community themes. Since Luminex is no longer supported and has been superseded by "Vortex," this update ensures that the community repository stays current and organized with the most up-to-date themes. Thank you for your understanding!
=> Remove Luminex Theme from Obsidian Community Themes

community-plugins.json
My profile url and name has changed, so I would like to keep the plugin info in this repository valid and up to date
=> Update author name for Canvas Link Optimizer plugin

community-plugins.json
Link to my plugin: https://github.com/dnlbauer/obsidian-dataview-autocompletion
=> Add plugin: Dataview Autocompletion

community-plugins.json
Link to my plugin: https://github.com/rama1997/Image-Preview-On-Icon-Hover
=> Add plugin: Image Preview on Icon Hover

community-css-themes.json
https://github.com/AfonsoMiranda02/Obsidian-MinimalRed
=> Add theme: Minimal Red

community-plugins.json
Link to my plugin: https://github.com/talwrii/plugin-repl
- [ N/A] `styles.css` _(optional)_
=> Add plugin: Plugin REPL

community-plugins.json
Link to my plugin: https://github.com/mbramani/obsidian-yt-video-summarizer
=> Add plugin: YouTube Video Summarizer

community-plugins.json
Link to my plugin: https://github.com/ZukTol/obsidian-data-files-editor
=> Add plugin: Data Files Editor

community-plugins.json
- Workspaces Plus has moved from `nothingislost/obsidian-workspaces-plus` to `jsmorabito/obsidian-workspaces-plus`
https://github.com/jsmorabito/obsidian-workspaces-plus
=> Repo change: Update workspaces-plus repository location

community-plugins.json
Link to my plugin: https://github.com/VaguelyElectric/obsidian-explorer-colors
=> Add plugin: Explorer Colors

community-plugins.json
Link to my plugin: https://github.com/makebit/obsidian-readeck-importer
=> Add plugin: Readeck Importer

community-css-themes.json
Add old world theme to obsidian
Link to my theme: https://github.com/double-tilde/old-world-obsidian
=> Add theme: Old World

community-plugins.json
Add feedly-annotations plugin
https://github.com/Fleker/feedly-for-obsidian/
=> Add plugin: Feedly Annotations Sync

community-plugins.json
Link to my plugin: https://github.com/alythobani/obsidian-callout-copy-buttons/
=> Add plugin: Callout Copy Buttons

community-plugins.json
Link to my plugin: https://github.com/Kay607/obsidian-pathlinker
=> Add plugin: External File Linker

community-plugins.json
Link to my plugin: https://github.com/tbergeron/obsidian-fold-properties-by-default
=> Add plugin: Fold Properties By Default

community-plugins.json
Link to my plugin: [https://github.com/wakywayne/obsidian-hotstrings](https://github.com/wakywayne/obsidian-hotstrings)
=> Add plugin: Hotstrings

community-plugins.json
=> Add plugin: Attachments MD Indexer

community-plugins.json
Link to my plugin: https://github.com/alberto98fx/idle-monitor-obsidian
=> Add plugin: Idle Monitor

community-plugins.json
Link to my plugin: Link to my plugin: https://github.com/xthecapx/cv-generator
=> Add plugin: Thecap cv generator

community-plugins.json
https://github.com/Nick-de-Bruin/obsidian-extended-file-support
=> Add plugin: Extended File Support

community-plugins.json
Link to my plugin: https://github.com/louanfontenele/obsidian-vault-file-renamer
I have given proper attribution to these other projects in my README.md.
=> Add plugin: Vault File Renamer

community-plugins.json
Link to my plugin: https://github.com/bomian98/obsidian-hide-commands-in-menu
=> Add plugin: Hide Commands in Menu

community-plugins.json
Link to my plugin: https://github.com/XuQuan-nikkkki/FolderFile-Splitter-Plugin
=> Add plugin: FolderFile Splitter

community-plugins.json
Link to my plugin: https://github.com/sechan100/daily-routine-2
=> Add plugin: Daily Routine

community-plugins.json
Link to my plugin: https://github.com/brokensandals/obsidian-paste-quote-plugin
=> Add plugin: Paste Quote

community-plugins.json
Link to my plugin: https://github.com/infiolab/infio-copilot
=> Add plugin: Infio Copilot

community-plugins.json
https://github.com/lextoumbourou/obsidian-title-as-link-text
=> Add plugin: Title As Link Text

community-plugins.json
Link to my plugin: https://github.com/Quorafind/Obsidian-Task-Genius/tree/master
Original name is Obsidian-Task-Progress-Bar
I want to rename it because it contains features that are not much progress-bar related after refactoring
=> Rename plugin: Obsidian-Task-Progress-Bar to Obsidian-Task-Genius

community-plugins.json
Link to my plugin: https://github.com/situ2001/obsidian-editor-group-arrangement
=> Add plugin: Tab Group Arrangement

community-plugins.json
tidit adds timestamps to your document as you type — when you want it, how you want it, where you want it. 
https://github.com/codingthings-com/tidit-obsidian
Link to my plugin: https://github.com/codingthings-com/tidit-obsidian
- [ x ] I have tested the plugin on
- [ x ]  macOS
- [ x ]  Linux
- [ x ]  iOS _(if applicable)_
- [ x ] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
- [ x ] `main.js`
- [ x ] `manifest.json`
- [ x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ x ] My README.md describes the plugin's purpose and …
=> Add plugin: tidit

community-plugins.json
Link to my plugin: https://github.com/InfoFlow/Obsidian-InfoFlow
It seems that while submitting plugin from an org there's no option to allow maintainer to edit my PR
=> Add plugin: InfoFlow

community-plugins.json
Extracts a URL from the frontmatter of notes and displays an associated favicon image next to the note title in the file tree. Supports standard URLs and base64-encoded images.
-  [X]  Windows
=> Add plugin: Note Favicon

community-plugins.json
Link to my plugin: https://github.com/luisbs/obsidian-attachments-cache
=> Add plugin: Attachments Cache

community-plugins.json
Link to my plugin: https://github.com/rscopic/obsidian-vault-nickname
=> Add plugin: Vault Nickname

community-plugins.json
Link to my plugin: https://github.com/SmallZombie/link-opening-restore
=> Add plugin: Link Opening Restore

community-plugins.json
https://github.com/0x1DA9430/obsidian-img2html
=> Add plugin: Image to HTML

community-plugins.json
Link to my plugin: https://github.com/mnaoumov/obsidian-backlink-full-path
=> Add plugin: Backlink Full Path

community-plugins.json
Link to my plugin: https://github.com/trevortylerlee/yesterdays-note
=> Add plugin: Yesterday's note

community-plugins.json
Link to my plugin: https://github.com/d7sd6u/obsidian-auto-folder-note-paste
=> Add plugin: Auto Folder Note Paste

community-css-themes.json
https://github.com/LennZone/obsidian-enhanced-file-explorer-tree
=> Add theme: Enhanced file explorer tree

community-plugins.json
Link to my plugin: https://github.com/Hacker-C/obsidian-open-in-github-plugin
=> Add plugin: Open in GitHub

community-plugins.json
added duplicate-line plugin entry
Link to my plugin: https://github.com/msztolcman/obsidian-duplicate-line
=> Add plugin: Duplicate line

community-plugins.json
include "VSCode" in the description of the open-vscode plugin so it shows up inside Obsidian when searched
=> include "VSCode" in the description of the open-vscode plugin

community-css-themes.json
Changed my username on github, thus needed to update the repo link and author name for my theme
Link to my theme: https://github.com/ThePharaohArt/Obsidian-CyberGlow
-  [x]  `manifest.json`
-  [x] `theme.css`
-  [x]  The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
-  [x] I have indicated which modes (dark, light, or both) are compatible with my theme.
-  [x]  I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
-  [x]  I have added a license in the LICENSE file.
-  [x]  My project respects and is compatible with the original license of any code from other themes that I'm using. I have given proper attribution to these other themes in my `README.md`.
=> Update for CyberGlow Link and Author

community-plugins.json
Link to my plugin: https://github.com/Kh4f/obsidian-manual-sorting
=> Update plugin description & repo url

community-plugins.json
adjust description of image context menus plugin to new and cut functionality as of new update: https://github.com/NomarCub/obsidian-copy-url-in-preview/releases/tag/1.10.0
=> adjust description of image context menus plugin

community-plugins.json
Removes the relay-md plugin from community plugins as it has been consolidated into Relay by System 3.
- The relay-md repository is now private
- https://forum.obsidian.md/t/request-to-remove-relay-md-plugin-now-consolidated-with-relay-by-system-3/99149
=> Remove relay-md plugin (consolidated into Relay by System 3)

community-plugins-removed.json
Adding relay-md entry to removed plugins list with reason "Replaced by Relay by System 3". https://forum.obsidian.md/t/request-to-remove-relay-md-plugin-now-consolidated-with-relay-by-system-3/99149
=> Add relay-md to removed plugins list

community-plugins.json
Link to my plugin: https://github.com/wenlzhang/obsidian-folder-navigator
=> Add plugin: Folder Navigator

community-plugins.json
Link to my plugin: https://github.com/Moyf/easy-copy
=> Add plugin: Easy Copy

community-plugins.json
Link to my plugin: https://github.com/jesse-r-s-hines/obsidian-open-tab-settings
=> Add plugin: Open Tab Settings

community-plugins.json
Link to my plugin: https://github.com/lorens-osman-dev/double-row-toolbar
=> Add plugin: Double row toolbar

community-plugins.json
Link to my plugin: https://github.com/bwya77/obsidian-quick-peek-sidebar
=> Add plugin: Quick Peek Sidebar

community-plugins.json
Link to my plugin: https://github.com/njko39/obsidian-reference-link-plugin
=> Add plugin: Reference Link Render

community-plugins.json
Link to my plugin: https://github.com/broekema41/obsidian-vcf-contacts/
=> Add plugin: VCF Contacts

community-plugins.json
Link to my plugin: [repo](https://github.com/EurFelux/obsidian-another-name-plugin)
=> Add plugin: Another Name

community-plugins.json
logos-refs allows for incorporating Logos (a powerful bible reference software) into your obsidian workflow and notes.
Link to my plugin: https://github.com/joey-kilgore/logos-refs
=> Add plugin: logos-refs

community-plugins.json
Adding the custom commands plugin
https://github.com/Staaaaaaaaaan/obsidian-custom-commands
- [x ] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
=> Add plugin: Custom Commands

community-plugins.json
Add `backlink-settings` to community-plugins.json
Link to my plugin: https://github.com/calvinwyoung/obsidian-backlink-settings
=> Add plugin: Backlink Settings

community-plugins.json
https://github.com/nykkolin/obsidian-convert-base64-to-png
=> Add plugin: Convert Base64 to PNG

community-plugins.json
Enhances the File Explorer by adding a marker to all the File Explorer items that are currently open in the workspace.
https://github.com/gasparschott/obsidian-mark-open-files
=> Add plugin: Mark Open Files

community-plugins.json
Link to my plugin: https://github.com/dylanarmstrong/obsidian-prettier-plugin
=> Add plugin: Format Automatically with Prettier

community-plugins.json
Link to my plugin: https://github.com/marc-f/obsidian-file-name-styler
=> Add plugin: FileName Styler

community-plugins.json
Added YouTrack Fetcher plugin.
Link to my plugin: https://github.com/forketyfork/obsidian-youtrack-fetcher/
=> Add plugin: YouTrack Fetcher

community-plugins.json
Link to my plugin: https://github.com/Mara-Li/obsidian-simple-colored-folder
=> Add plugin: Simple Colored Folder

community-plugins.json
Add Simple Password Plugin
Link to my plugin: https://github.com/ShadiestGoat/obsidian-simple-password
=> Add plugin: Simple Password

community-plugins.json
Link to my plugin: https://github.com/Kovah/obsidian-wakatime
=> Add plugin: Wakatime / Wakapi

community-plugins.json
Link to my plugin: https://github.com/rivea0/obsidian-match-syntax
=> Add plugin: MatchSyntax

community-plugins.json
https://github.com/rouvenjahnke/markwhen-file-sync
- [ x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
- [ x] My project respects and is compatible with the original license of any code from other plugins that I'm using.
=> Add plugin: Markwhen File Sync

community-plugins.json
Link to my plugin: https://github.com/OverFitted/obsidian-japanese-helper
=> Add plugin: Japanese note taking helper

community-plugins.json
https://github.com/hoomersinpsom/simple-tab-indent
=> Add plugin: Simple Tab Indent

community-plugins.json
We're transitioning Media Extended from MIT to a closed-source license with the upcoming v4 release, which is currently in beta testing. As per Obsidian Developer Policies, we're requesting a review from the Obsidian team prior to our first official release under the new license structure.
- The plugin will be moving from MIT to a closed-source license model
- We have invited @joethei to the private codebase repository for review
- Further technical details and implementation specifics will be discussed in the private repository
We're available to answer any questions or address concerns about this license transition. We understand this requires case-by-case review per your policies and appreciate your time evaluating our submission.
Intro about the codebase of obsidian plugin could be …
=> Media Extended v4 License Change & Review Request

community-plugins.json
Link to my plugin: https://github.com/QuintSmart/obsidian-course-module-loader
=> Add plugin: Course Module Loader

community-plugins.json
Link to my plugin: https://github.com/Netajam/obsidian_note_uid_generator
=> Add plugin: Note UID Generator

community-plugins.json
adding Folder Filelist entry
Link to my plugin: https://github.com/band/obsidian-folder-filelist
=> Add plugin: Folder Filelist

community-plugins.json
The plugin now does more than the name says, so it is not as discoverable by the users.
From what I understood, I have to keep the plugin id, even if it doesn't match the rebranded plugin name.
=> Rebrand `Refresh Preview` plugin to `Refresh Any View`

community-plugins.json
[rioskit/obsidian-todo-txt-mode: Obsidian plugin for todo.txt file format support](https://github.com/rioskit/obsidian-todo-txt-mode)
=> Add plugin: Todo.txt Mode

community-plugins.json
https://github.com/TadoTheMiner/obsidian-open-random-broken-link
=> Add plugin: Random broken link

community-plugins.json
Link to my plugin: https://github.com/AMC-Albert/obsidian-copy-absolute-path
=> Add plugin: Copy Absolute Path

community-plugins.json
Link to my plugin: https://github.com/LeonLuttenberger/obsidian-kindle-highlight-import
=> Add plugin: Kindle Highlights Import

community-plugins.json
Link to my plugin: https://github.com/vlwkaos/obsidian-smart-excluded
=> Add plugin: Smart Excluded

community-plugins.json
=> Add plugin: Yandex Wiki Integration

community-plugins.json
Link to my plugin: https://github.com/zmeeeeeva/obsidian-plugin-metadata-link-classes
=> Add plugin: Frontmatter Metadata Link Classes

community-plugins.json
Opens .url files in the internal webview.
=> Add plugin: .url WebView Opener

community-plugins-removed.json, community-plugins.json
This removes the "Privacy Glasses" plugin, as the Obsidian Hub GitHub Actions logs have been reporting the repo as missing.
...as mentioned in https://discord.com/channels/686053708261228577/840286264964022302/1394576939230040104
Both of these give "404":
https://github.com/jillalberts/
https://github.com/jillalberts/privacy-glasses
In `community-plugins-removed.json`, I gave `"reason": "Account deleted"` - but in fact it could have just been made private, I have no way of knowing.
=> Remove "Privacy Glasses" plugin - account URL is giving 404

community-plugins.json
Add plugin: Related Notes by Tag
related-notes-by-tag
Link to my plugin: https://github.com/chrishoward-projects/related-notes-by-tag
=> Add plugin: Related Notes by Tag

community-plugins.json
[Link to my plugin
](https://github.com/k0src/Obsidian-Auto-Close-Tags-Plugin)
- x] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed my plugin to avoid these common pitfalls.
=> Add plugin: Auto Close Tags

community-plugins.json
=> Typo in languagetool plugin description

community-plugins.json
Link to my plugin: [awfrok/obsidian-plugin-bibtex-entry-view](https://github.com/awfrok/obsidian-plugin-bibtex-entry-view)
=> Add plugin: Bibtex Entry View

community-plugins.json
Added extension for saving X (Twitter) post data to new notes
Link to my plugin: [tanaka-mambinge/x-post-saver](https://github.com/tanaka-mambinge/x-post-saver)
=> Add plugin: X Post Saver

community-plugins.json
Link to my plugin: https://github.com/ckelsoe/obsidian-shell-path-copy
=> Add plugin: Shell Path Copy

community-plugins.json
Link to my plugin: https://github.com/CubieProg/Obsidian-Yandex-Tracker-Issue
=> Add plugin: Yandex Tracker Issue

community-plugins.json
Link to my plugin: https://github.com/mbedded/obsidian-paste-file-link
---
Remarks:
The guidelines says, that `this.app.vault.getFiles().find(..)` should not be used. The idea behind my plugin is, that I can paste a file name (note) so a file-link is created. I've tested the method `this.app.vault.getFileByPath()` but when I'm looking for "my note" it does not find "folder/my note" for example.
In my workflow I use F2 to select the filename, press CTRL+C to copy it, switch to another note and paste the name. The selection with F2 does not contain the full path of the file. That's why I use `getFiles().find(..)`instead. If there is a way for improvement, I'm happy to update my plugin.
I'm not sure how big the impact …
=> Add plugin: Paste as file link

community-plugins.json
Link to my plugin: https://github.com/Lauloque/Obsidian-Keyboard-Formatter
=> Add plugin: Keyboard Formatter

community-plugins.json
Adds `datacore` as a publically available plugin - though I will note this is very much a power users tool still!
Link to my plugin: https://github.com/blacksmithgu/datacore
=> Add plugin: Datacore

.github/workflows/validate-plugin-entry.yml
Commit af462b6a23a41baa41d431521e4f4b897ee2c897 has introduced a typo in the github action / bot that checks the validity of the PR against the plugin template.
=> Fix typo in plugin validation action
