- community-css-themes.json
Link to my theme: https://github.com/Avesend/obsidian-lumines
> Add theme: Lumines

- community-css-themes.json
Link to my theme: https://github.com/Erallie/colored-candy
> Add theme: Colored Candy

- community-css-themes.json
Link to my theme: https://github.com/Spekulucius/obsidian-adrenaline
> Add theme: Adrenaline

- community-css-themes.json
**Repo URL:**  
Link to my theme: [https://github.com/omsandippatil/OISTNB](https://github.com//omsandippatil/OISTNB)
- `manifest.json`
- `theme.css`
- The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
> Add theme: OISTNB

- community-plugins.json
Link to my plugin: https://github.com/cool-RR/backtick-text-selector
.
> Add plugin: Backtick text selector

- community-plugins.json
Update the desc of plugin tars to include new features.
> Update the desc of plugin tars to include new features

- community-css-themes.json
Link to my theme: https://github.com/b3h3m0th/black-obsidian-theme
> Add theme: Black

- community-plugins.json
Updated description to more accurately reflect the current capabilities of the plugin.
> Update Quiz Generator plugin description

- community-plugins.json
Link to my plugin: https://github.com/la/obsidian-daily-note-collector
> Add plugin: Daily Note Collector

- community-plugins.json
Link to my plugin: https://github.com/abcamus/obsidian-quick-card
> Add plugin: Quick Cards

- community-plugins.json
Link to my plugin: https://github.com/barkstone2/obsidian-to-blog
> Add plugin: Vault to blog

- community-plugins.json
~~I'm submitting two plugins. I hope that's okay, but I can break them apart into two PRs if necessary.~~
Link to my plugin: https://github.com/nicholas-wilcox/tailwind-snippet-obsidian-plugin
> Add plugin: Tailwind Snippet

- community-plugins.json
https://github.com/Yohh/obsidian-simple-sketch
> Add plugin: simple-sketch

- community-plugins.json
Link to my plugin: https://github.com/nicholas-wilcox/pug-templates-obsidian-plugin
> Add plugin: Pug Templates

- community-css-themes.json
Link to my theme: https://github.com/FaisalTamanoJr/Refined-Default
> Add theme: Refined Default

- community-css-themes.json
Link to my theme: https://github.com/tu2-atmanand/RoseRed-ObsidianTheme
> Add theme: Rose Red

- community-css-themes.json
Link to my theme: https://github.com/Elhary/Obsidian-Minimal-Edge
> Add theme: Minimal Edge

- community-plugins.json
Link to my plugin: https://github.com/jordaeday/canvas-task-importer
> Add plugin: Canvas LMS Task Importer

- community-plugins.json
Link to my plugin: https://github.com/ferenk/obsidian-tokenz
> Add plugin: Tokenz

- community-plugins.json
Link to my plugin: https://github.com/Erallie/diarian
> Add plugin: Diarian

- community-plugins.json
Link to my plugin: https://github.com/Superkikim/nexus-ai-chat-importer
> Add plugin: Nexus AI Chat Importer

- community-plugins.json
> Add plugin: Auto Periodic Notes

- community-plugins.json
Link to my plugin: [Onto Tracker repo](https://github.com/jdchart/onto-tracker)
> Add plugin: Onto Tracker

- community-plugins.json
Link to my plugin: https://github.com/Ordeeper/obsidian-journaling-plugin
> Add plugin: Journaling

- community-plugins.json
Link to my plugin: https://github.com/Mara-Li/obsidian-edit-shorcut
> Add plugin: Edit mode switch

- community-plugins.json
Link to my plugin: https://github.com/marijnbent/obsidian-print
> Add plugin: Print

- community-plugins.json
Link to my plugin: https://github.com/morgen-so/morgen-obsidian
- [-]  Windows
- [-]  Linux
> Add plugin: Morgen Tasks

- community-plugins.json
Link to my plugin: https://github.com/Talal-A/obsidian-immich
> Add plugin: Immich

- community-plugins.json
https://github.com/kpaede/Verovio-Music-Renderer/
https://github.com/kpaede/Verovio-Music-Renderer/releases/tag/1.0.1
Info: The plugin accesses a soundfont file on Github for playback (just like similar midi playback plugins)
> Add plugin: Verovio Music Renderer

- community-plugins.json
Link to my plugin: https://github.com/wakeyi-git/obsidian-card-navigator-plugin
> Add plugin: Card Navigator

- community-plugins.json
Link to my plugin: https://github.com/anareaty/callout-menu
> Add plugin: Callout menu

- community-plugins.json
Link to my plugin: https://github.com/situ2001/obsidian-enhanced-image
> Add plugin: Enhanced Image

- community-plugins.json
> Add plugin: Poker Range

- community-plugins.json
Link to my plugin: https://github.com/zachmueller/spaced-everything
> Add plugin: Spaced everything

- community-plugins.json
Link to my plugin: https://github.com/jparkerweb/pexels-banner
> Add plugin: Pexels Banner

- community-plugins.json
Link to my plugin: https://github.com/jparkerweb/rich-foot
> Add plugin: Rich Foot

- community-plugins.json
Link to my plugin: https://github.com/amiaslee/obsidian-pintora
> Add plugin: Pintora

- community-plugins.json
- [X ] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
> Add plugin: Alignment Tracker

- community-plugins.json
Link to my plugin:  
https://github.com/Stanley-Wang910/obsidian-code-language-completer
My project respects and is compatible with the original license of any code from other plugins that I'm using.  
> Add plugin: Code Language Completer

- community-plugins.json
> Add plugin: Guitar Chord

- community-plugins.json
Link to my plugin: https://github.com/pteridin/obsidian_symlink_plugin
> Add plugin: Symlink Creator

- community-plugins.json
Link to my plugin: https://github.com/n810K/obsidian-collapse-linked-mentions
> Add plugin: Collapse Linked Mentions

- community-plugins.json
> Add plugin: Diagram Zoom Drag

- community-plugins.json
Link to my plugin: https://github.com/Ssentiago/obsidian-xmind-viewer
> Add plugin: XMind Viewer

- community-plugins.json
Link to my plugin: https://github.com/Nomekuma/auto-strikethrough-task-obsidian-pluggin
> Add plugin: Auto Strikethrough Tasks

- community-plugins.json
Link to my plugin: https://github.com/WiNE-iNEFF/obsidian-colorizelt
> Add plugin: Colorizelt

- community-plugins.json
Link to my plugin: https://github.com/drewmcdonald/obsidian-magic-mic
> Add plugin: Magic Mic

- community-plugins.json
Link to my plugin: https://github.com/kdnk/obsidian-hierarchy
> Add plugin: Hierarchy

- community-plugins.json
Link to my plugin: https://github.com/jackvonhouse/custom-node-size
> Add plugin: Custom Node Size

- community-plugins.json
A plugin to show mermaid diagrams in a draggable and zoomable popup
> Add plugin: Mermaid Popup

- community-plugins.json
Link to my plugin: https://github.com/imfenghuang/obsidian-magic-move
I have given proper attribution to these other projects in my README.md.
> Add plugin: Immersive Translate

- community-plugins.json
Link to my plugin: https://github.com/jdrbrn/obsidian-scripture-indexer
> Add plugin: Scripture Indexer

- community-css-themes.json
Link to my theme: https://github.com/darthdemono/AMOLED-Serenity
- `manifest.json`
- `theme.css`
- The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
> Add theme: AMOLED Serenity

- community-css-themes.json
https://github.com/golam71/obsidian-hackthebox
https://github.com/golam71/obsidian-hackthebox
> Add theme: Hackthebox

- community-css-themes.json
Link to my theme: https://github.com/Oczko24/Obsidian-transparent
> Add theme: Transparent

- community-css-themes.json
https://github.com/LeslyeCream/Lagom-Obsidian-Theme
> Add theme: Lagom

- community-css-themes.json
Link to my theme: https://github.com/LorenzoPegorari/SimplyColorful
> Add theme: Simply Colorful

- community-css-themes.json
Link to my theme: https://github.com/Sunhaloo/OneNice
> Add theme: OneNice

- community-css-themes.json
Link to my theme: https://github.com/ElsaTam/obsidian-fancy-a-story
> Add theme: Fancy-a-Story

- community-css-themes.json
Link to my theme: https://github.com/ofalvai/flexoki-warm/tree/1.0.0
> Add theme: Flexoki Warm

- community-plugins.json
Link to my plugin: https://github.com/CodeListening/obsidian-bookxnote
> Add plugin: BookXNote Sync

- community-plugins.json
Add link-navigation plugin
https://github.com/xRyul/link-navigation
> Add plugin: Link Navigation

- community-plugins.json
Link to my plugin: https://github.com/MrAnyx/obsidian-ffmpeg-converter
> Add plugin: FFmpeg Converter

- community-plugins.json
Link to my plugin: https://github.com/bruce-pain/crackboard-obsidian
> Add plugin: Crackboard

- community-plugins.json
> Add plugin: Quick Notes

- community-plugins.json
Link to my plugin: https://github.com/dsebastien/obsidian-typefully
> Add plugin: Typefully

- community-plugins.json
Add infranodus-graph-view plugin
Link to my plugin: https://github.com/noduslabs/infranodus-obsidian-plugin
> Add plugin: InfraNodus AI Graph View

- community-plugins.json
Link to my plugin: https://github.com/DvorakDwarf/scrambling-title-animations
> Add plugin: Scrambling Title Animations

- community-plugins.json
I only changed the description to adhere to the rules.
Link to my plugin: https://github.com/marijnbent/obsidian-print
> Update plugin description: Print

- community-css-themes.json
Both the account and repository are gone.
> Remove DarkNebula theme

- community-plugins.json
Updating the plugin description to mention its color functionality, matching what's in [`manifest.json`](https://github.com/gfxholo/iconic/blob/main/manifest.json#L6).
> Update plugin: Iconic

- community-plugins.json
Link to my plugin: https://github.com/likemuuxi/obsidian-modal-opener
Update the plug-in description to mention file creation, matching what is in [manifest.json](https://github.com/likemuuxi/obsidian-modal-opener/blob/main/manifest.json).
> Update plugin: Modal Opener

- community-plugins.json
Link to my plugin: https://github.com/tavva/flow-release
(Note that the source code is not public. I have invited joethei to the source repo.)
> Add plugin: Flow

- community-plugins.json
Plugin name: Copy Section
Link to my plugin: https://github.com/skztr/obsidian-plugin-section-copy
> Add plugin: Copy Section

- community-plugins.json
https://github.com/yingjialong/obsidian-CloudStorage
> Add plugin: Cloud Storage

- community-plugins.json
Link to my plugin: https://github.com/seyf1elislam/obsidian-LocalMediaEmbedder-plugin
> Add plugin: Local Media Embedder

- community-plugins.json
Link to my plugin: https://github.com/GnoxNahte/obsidian-tab-panels
> Add plugin: Tab Panels

- community-plugins.json
Link to my plugin: https://github.com/justanotherjurastudent/Jura-Links
> Add plugin: Jura Links

- community-plugins.json
Link to my plugin: https://github.com/leschuster/obsidian-advanced-copy
> Add plugin: Advanced Copy

- community-plugins.json
Link to my plugin: https://github.com/ahts4962/nav-link-header
> Add plugin: Nav Link Header

- community-plugins.json
Link to my plugin: https://github.com/patrickchiang/obsidian-replace-all
> Add plugin: Replace All

- community-plugins.json
Link to my plugin: https://github.com/GoBeromsu/Metadata-Auto-Classifier
> Add plugin: Metadata Auto Classifier

- community-plugins.json
Link to my plugin: https://github.com/watsonbox/obsidian-strava-sync
> Add plugin: Strava Sync

- community-plugins.json
> Add plugin: Another Simple Todoist Sync

- community-plugins.json
This is a new PR after #3164 has been closed.
https://github.com/kon-foo/Obsidian-Translate-Inline/t
> Add plugin: Translate Inline

- community-plugins.json
> Add plugin: random-retrieval

- community-plugins.json
> Add plugin: Occura

- community-plugins.json
Link to my plugin: https://github.com/alythobani/obsidian-callout-toggles
> Add plugin: Callout Toggles

- community-css-themes.json
Link to my theme: https://github.com/xero/evangelion.obsidian/
i developed this for the ipad version of the app. ive tested it on macos and Android as well. would love to get it into more people's vaults so we can make it better.
- full disclosure: i use `!important` quite a bit, this theme is a full ui remix
> Add theme: evangelion

- community-css-themes.json
Link to my theme:  https://github.com/juanchiparra/obsidian-borealis
> Add theme: Borealis

- community-css-themes.json
Link to my theme: https://github.com/DKLiberty/Red-Shadow/
> Add theme: Red-Shadow

- community-css-themes.json
Link to my theme: https://github.com/abhimangs/Obsidian-Luminex
> Add theme: Luminex

- community-plugins.json
https://github.com/alythobani/obsidian-callout-toggles
> Description change: Callout Toggles plugin

- community-plugins.json
https://github.com/different-ai/file-organizer-200
> Description change: File Organizer 2000

- community-css-themes.json
Link to my theme: https://github.com/artorias305/obsidian-shadeflow
> Add theme: Shadeflow

- community-plugins.json
Link to my plugin: https://github.com/itsonlyjames/obsidian-fold-properties
> Add plugin: Fold Properties

- community-plugins.json
> Add plugin: downloadPDF

- community-plugins.json
Link to my plugin: https://github.com/rasmusachr/pdf2images
> Add plugin: PDF2Image

- community-plugins.json
Link to my plugin: https://github.com/glowingjade/obsidian-smart-composer
> Add plugin: Smart Composer

- community-plugins.json
Link to my plugin: https://github.com/tabibyte/session-notes
> Add plugin: Session Notes

- community-plugins.json
Link to my plugin: https://github.com/SashaKryzh/obsidian-vault-review
> Add plugin: Vault Review

- community-plugins.json
This plugin is used for code indentation beautification.
Link to my plugin: https://github.com/wiop93256/Simple-Code-Formmater
> Add plugin: Simple Code Formatter

- community-plugins.json
Link to my plugin: https://github.com/jasonmotylinski/hierarchical-backlinks
> Add plugin: Hierarchical Backlinks

- community-plugins.json
Link to my plugin: https://github.com/exmemo-ai/obsidian-exmemo-client
> Add plugin: ExMemo Client

- community-plugins.json
Link to my plugin: https://github.com/lengff123/cursor-bridge
> Add plugin: Cursor Bridge

- community-plugins.json
> Add plugin: Nav Weight

- community-plugins.json
Link to my plugin: https://github.com/konfuzz/arweave-uploader-plugin
> Add plugin: Arweave Uploader

- community-plugins.json
Link to my plugin: https://github.com/Lio5n/peekaboo
> Add plugin: Peekaboo

- community-plugins.json
> Add plugin: Blue Star

- community-plugins.json
Link to my plugin: https://catacgc.github.io/obsidian-tree-search/#/
> Add plugin: Tree Search

- community-plugins.json
Link to my plugin: https://github.com/sissilab/obsidian-hexo-toolkit
> Add plugin: Hexo Toolkit

- community-plugins.json
Link to my plugin: https://github.com/Unearthed-App/unearthed-obsidian
> Add plugin: Unearthed (Kindle Sync)

- community-plugins.json
Link to my plugin: https://github.com/nyable/obsidian-text-finder
> Add plugin: Text Finder

- community-plugins.json
Link to my plugin: https://github.com/wanabeunique/obsidian-workout-tracker
> Add plugin: Workout Tracker

- community-plugins.json
> Add plugin: Superstition

- community-plugins.json
Link to my plugin: https://github.com/Synaptic-Labs-AI/NeuroVox
> Add plugin: NeuroVox

- community-plugins.json
Link to my plugin: https://github.com/jsifalda/obsidian-todos-sort
> Add plugin: Todos sort

- community-plugins.json
Link to my plugin: https://github.com/Telehakke/masking-type
> Add plugin: Masking Type

- community-plugins.json
Link to my plugin: https://github.com/johansan/obsidian-featured-image
> Add plugin: Featured Image

- community-plugins.json
Link to my plugin: https://github.com/bartkessels/daily-note-calendar
> Add plugin: Daily notes calendar

- community-plugins.json
Link to my plugin: [https://github.com/travisvn/obsidian-edge-tts](https://github.com/travisvn/obsidian-edge-tts)
> Add plugin: Edge TTS

- community-plugins.json
> Add plugin: Textgrams

- community-plugins.json
Link to my plugin: https://github.com/yesjinu/brain-dump-mode/tree/master
> Add plugin: Brain Dump Mode

- community-plugins.json
Link to my plugin: https://github.com/recklyss/markdown-timeline
> Add plugin: Markdown Timeline

- community-plugins.json
Added Danitiate/check-and-delete plugin
Link to my plugin: https://github.com/Danitiate/check-and-delete
> Add plugin: Check and Delete

- community-plugins.json
https://github.com/heseber/perplexity-converter
> Add plugin: Perplexity Converter

- community-plugins.json
> Add plugin: Typezen

- community-plugins.json
https://github.com/acgabbert/IOC-Lens
> Add plugin: IOC Lens

- community-css-themes.json
Added Orange theme
https://github.com/afrangi/Obsidian-Theme-Orange
> Add theme: Orange

- community-css-themes.json
Link to my theme: https://github.com/pinei/obsidian-consolas-theme
> Add theme: Consolas

- community-css-themes.json
Link to my theme: https://github.com/incantatem2/Obsidian-neutral-academia
> Add theme: Neutral Academia

- community-plugins.json
Link to my plugin: [https://github.com/jamespeachh/three-noun-prompts](https://github.com/jamespeachh/three-noun-prompts)
> Add plugin: Three Noun Prompts

- community-plugins.json
> Add plugin: Bottom to Top

- community-plugins.json
> # I am submitting a new Community Plugin
> ## Repo URL
> Link to my plugin:
> https://github.com/Lemon695/obsidian-recently-added-files
> 
> ## Release Checklist
> * [x]  I have tested the plugin on
>   
>   * [ ]   Windows
>   * [x]   macOS
>   * [ ]   Linux
>   * [ ]   Android _(if applicable)_
>   * [x]   iOS _(if applicable)_
> * [x]  My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
>   
>   * [x]  `main.js`
>   * [x]  `styles.css` _(optional)_
> * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
> * [x]  该 `id` in my `manifest.json` matches the `id` 在 `community-plugins.json` file.
> * …
> Add plugin: Recently Added Files

- community-plugins.json
https://github.com/Hosstell/image-tools-obsidian-plugin
> Add plugin: Image Tools

- community-plugins.json
Link to my plugin: https://github.com/CSLukkun/ob_daily_summary
- [] I have tested the plugin on
> Add plugin: Daily Summary

- community-plugins.json
Link to my plugin: https://github.com/jamiefdhurst/obsidian-auto-tasks
> Add plugin: Auto Tasks

- community-plugins.json
Link to my plugin: [task-director](https://github.com/cybertramp/obsidian-task-director)
> Add plugin: Task Director

- community-plugins.json
Link to my plugin: https://github.com/Yaob1990/obsidian-history-today
> Add plugin: History Today

- community-plugins.json
Link to my plugin: https://github.com/seth10/beautiful-obsidian-contacts/tree/1.1.0
> Add plugin: Beautiful Contact Cards

- community-plugins.json
[https://github.com/henryco/BlazeJump-Obsidian](https://github.com/henryco/BlazeJump-Obsidian)
> Add plugin: BlazeJump

- community-plugins.json
Link to my plugin: https://github.com/Fleker/trakt-for-obsidian
> Add plugin: Trakt.tv Sync

- community-plugins.json
Link to my plugin: https://github.com/philphilphil/obsidian-standardform
> Add plugin: StandardForm

- community-plugins.json
Link to my plugin: [https://github.com/linqing24/obsidian-simple-focus](https://github.com/linqing24/obsidian-simple-focus)
> Add plugin: Simple Focus

- community-plugins.json
Link to my plugin: https://github.com/cfe84/obsidian-pw
> Add plugin: Proletarian Wizard Task Manager

- community-plugins.json
Link to my plugin: [https://github.com/RichardX366/Obsidian-Google-Drive](https://github.com/RichardX366/Obsidian-Google-Drive)
> Add plugin: Google Drive Sync

- community-plugins.json
Link to my plugin: https://github.com/carlrobert/double-switch
> Add plugin: Auto switch themes between dark/light mode

- community-plugins.json
Link to my plugin: https://github.com/eharris128/obsidian-bluesky
> Add plugin: Bluesky

- community-plugins.json
> Add plugin: AI bot

- community-plugins.json
Link to my plugin: https://github.com/SpeedaRJ/obsidian_folder_tabulation/
> Add plugin: Folder Tabulation

- community-plugins.json
Link to my plugin: https://github.com/sedationh/obsidian-instant-above-divider
> Add plugin: Instant Above Divider

- community-plugins.json
Link to my plugin: https://github.com/dangehub/obsidian-blur-mode
> Add plugin: Blur Mode

- community-plugins.json
Link to my plugin: https://github.com/iLiftALot/insta-toc
> Add plugin: Insta TOC

- community-plugins.json
Created new plugin password-audit
Link to my plugin: https://github.com/prashanthpulisetti/password-audit
> Add plugin: Password Audit

- community-css-themes.json
Link to my theme: https://github.com/harmtemolder/obsidian-ink
> Add theme: Ink

- community-css-themes.json
Link to my theme: https://github.com/lorens-osman-dev/Glass-Robo
> Add theme: Glass Robo

- community-css-themes.json
Link to my theme: https://github.com/incantatem2/Obsidian-mulled-wine
> Add theme: Mulled Wine

- community-plugins.json
Link to my plugin: https://github.com/Chrstn67/obsidian-plugin-obsnippets
> Add plugin: Snippetsaurus

- community-plugins.json
Link to my plugin: https://github.com/elliotxx/obsidian-simple-todo
> Add plugin: Simple Todo

- community-plugins.json
Link to my plugin: https://github.com/clairefro/obsidian-plugin-chronos
**I have not tested on mobile yet but am confident it should work, since my only dependency (`vis-timeline`) is mobile compatible**
> Add plugin: Chronos Timeline

- community-plugins.json
Link to my plugin: [https://github.com/gutentag2012/obsidian-plugin-clear-todos](https://github.com/gutentag2012/obsidian-plugin-clear-todos)
> Add plugin: Clear Todos

- community-plugins.json
https://github.com/IvanKalmar/obsidian-simple-quiz
> Add plugin: Simple Quiz

- community-plugins.json
Link to my plugin: https://github.com/mofukuru/auto_file_organizer.git
> Add plugin: Auto File Organizer

- community-plugins.json
Link to my plugin: https://github.com/Fleker/setlist-for-obsidian
> Add plugin: Setlist.fm Sync

- community-plugins.json
Added mass-create plugin.
Link to my plugin: https://github.com/vellikhor/mass-create
> Add plugin: Mass Create

- community-plugins.json
Link to my plugin: https://github.com/ofalvai/obsidian-llm-workspace
> Add plugin: LLM workspace

- community-plugins.json
Link to my plugin: https://github.com/wenlzhang/obsidian-todoist-context-bridge
> Add plugin: Todoist Context Bridge

- community-plugins.json
Link to my plugin: https://github.com/Erallie/discord-timestamps
> Add plugin: Discord Timestamps

- community-plugins.json
https://github.com/mokkiebear/heatmap-tracker/tree/1.0.0
> Add plugin: Heatmap Tracker

- community-plugins.json
Updated the description of the plugin, please kindly merge in. Thanks!
The plugin: https://github.com/kctekn/obsidian-TagsRoutes
> Update descripton of plugin: tags-routes

- community-css-themes.json
Link to my theme: [git@github.com:sspaeti/obsidian_kanagawa_paper.git](https://github.com/sspaeti/obsidian_kanagawa_paper)
> Add theme: Kanagawa Paper

- community-plugins.json
Repo URL
Link to my plugin: https://github.com/crayhuang/Obsidian-Hugo-Sync
Release Checklist
I have tested the plugin on
Windows
macOS
Linux
Android (if applicable)
iOS (if applicable)
My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
main.js
manifest.json
styles.css (optional)
GitHub release name matches the exact version number specified in my manifest.json (Note: Use the exact version number, don't include a prefix v)
The id in my manifest.json matches the id in the community-plugins.json file.
My README.md describes the plugin's purpose and provides clear usage instructions.
I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
I have …
> Add plugin: Sync to Hugo

- community-plugins.json
Link to my plugin: https://github.com/magitools/magiedit-obsidian
> Add plugin: Magiedit

- community-plugins.json
Link to my plugin: https://github.com/lizard-heart/obsidian-tab-limit
> Add plugin: Tab Limiter

- community-plugins.json
Link to my plugin: https://github.com/damonsk/obsidian-wardley-maps
> Add plugin: Wardley Maps

- community-plugins.json
Link to my plugin: https://github.com/Cold-dragon7/Obsidian-Class-Relation-Visualization
> Add plugin: Class Relation Visualization

- community-plugins.json
Link to my plugin: https://github.com/vrtmrz/usher
> Add plugin: Usher

- community-plugins.json
> Add plugin: create folder notes with dropdown

- community-css-themes.json
Link to my theme: https://github.com/IxBlazarxI/Obsidian-Theme-OverCast
- [ x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [ x] `theme.css`
- [ x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [ x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [ x] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [x ] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [x ] I have added a license in the LICENSE file.
- [x ] My project respects and is compatible with the …
> Add theme: OverCast

- community-plugins.json
Link to my plugin: https://github.com/ChasKane/gay-toolbar
- [-] I have tested the plugin on
> Add plugin: Gay Toolbar

- community-plugins.json
Link to my plugin: [https://github.com/freddyouellette/obsidian-insert-new-line-plugin](https://github.com/freddyouellette/obsidian-insert-new-line-plugin)
> Add plugin: Insert New Line

- community-plugins.json
Link to my plugin: https://github.com/br4in/calloutX
> Add plugin: CalloutX

- community-plugins.json
Link to my plugin: https://github.com/lei-ctyh/obsidian-sync-cnblog
> Add plugin: Sync Cnblog

- community-plugins.json
> Add plugin: ExMemo Tools

- community-plugins.json
Link to my plugin: https://github.com/Eccys/obsidian-prayer-times/tree/master
> Add plugin: Fetch Prayer Times

- community-plugins.json
Link to my plugin: [https://github.com/astradev123/obsidian-focus-time](https://github.com/astradev123/obsidian-focus-time)
> Add plugin: Focus Time

- community-plugins.json
> Add plugin: ExMemo Assistant

- community-plugins.json
> Add plugin: FastForwardLink

- community-plugins.json
Link to my plugin: https://github.com/ruszabarov/obsidian-unit-converter
> Add plugin: Unit Converter

- community-plugins.json
Link to my plugin: https://github.com/al3xw/force-read-mode
> Add plugin: Force Read Mode

- community-plugins.json
Link to my plugin: https://github.com/mscott99/latex-exporter
> Add plugin: Latex Exporter

- community-plugins.json
> Add plugin: AmpliFlow Page Publisher

- community-plugins.json
Link to my plugin: https://github.com/olillin/obsidian-kale-graph
> Add plugin: Kale Graph

- community-plugins.json
Link to my plugin: [https://github.com/haierkeys/obsidian-custom-image-auto-uploader](https://github.com/haierkeys/obsidian-custom-image-auto-uploader)
> Add plugin: Custom Image Auto Uploader

- community-plugins.json
> Add plugin: WonderBox

- community-plugins.json
> Add plugin: kkh

- community-plugins.json
Link to my plugin: https://github.com/dukex/obsidian-import-todoist
> Add plugin: Import Todoist tasks

- community-plugins.json
> Add plugin: Link Maintainer

- community-plugins.json
Changed repo link because I changed my github username from `holxsam` to `szamsolo`.
> Change repo link

- community-plugins.json
Link to my plugin: https://github.com/wenlzhang/obsidian-todoist-context-bridge
> Update Todoist Context Bridge description

- community-css-themes.json
Link to my theme: https://github.com/raspberri05/simple-color
> Add theme: Simple Color

- community-css-themes.json
Link to my theme: https://github.com/Daiki48/sakurajima.obsidian
> Add theme: Sakurajima

- community-css-themes.json
Link to my theme: https://github.com/aaaaalexis/obsidian-cupertino
> Add theme: Cupertino

- community-plugins.json
Link to my plugin: https://github.com/kalvn/obsidian-export-to-html
> Add plugin: Export to HTML

- community-plugins.json
Link to my plugin: https://github.com/LincZero/obsidian-node-flow
> Add plugin: NodeFlow

- community-plugins.json
Link to my plugin: [send-note](https://github.com/jvsteiner/send-note/)
> Add plugin: Send Note

- community-plugins.json
Link to my plugin: https://github.com/paulpaterson/obsidian-project-tasks
> Add plugin: Project Tasks

- community-plugins.json
Link to my plugin: https://github.com/chaintng/cursor-position-on-title-enter
> Add plugin: Cursor Position on Title Enter

- community-plugins.json
also fixed poorly-formatted (unsightly indents) entries in community-plugins.json
Link to my plugin: https://github.com/brianpetro/smart-context-obsidian
> Add plugin: Smart Context

- community-plugins.json
Link to my plugin: https://github.com/Binaris00/Theme-Controller
> Add plugin: Theme Controller

- community-css-themes.json
Link to my theme: https://github.com/benjaminezequiel/playground-theme
> Add theme: Playground

- community-plugins.json
Link to my plugin: https://github.com/dsebastien/obsidian-replicate
> Add plugin: Replicate

- community-plugins.json
Link to my plugin: https://github.com/kbwo/obsidian-click-hint
> Add plugin: Click Hint

- community-plugins.json
Link to my plugin: https://github.com/SeardnaSchmid/copy-recursive-content
> Add plugin: Structured Copy: Files & Folders

- community-plugins.json
Link to my plugin: https://github.com/Binxly/Atomizer
> Add plugin: Atomizer

- community-plugins.json
> Add plugin: Jira Issue managing

- community-plugins.json
Link to my plugin: https://github.com/KarmaToast40340/photopea-editor
> Add plugin: Photopea Editor

- community-plugins.json
Link to my plugin: https://github.com/4Source/open-editors-obsidian-plugin
> Add plugin: Open Editors

- community-plugins.json
Just adding my rl name to all plugins I created.
> Update author name for plugins by @pseudometa

- community-plugins.json
https://github.com/jannusgoe/obsidian-ankisync
> Add plugin: AI-AnkiSync

- community-plugins.json
Link to my plugin: https://github.com/slow-groovin/simple-disguise
> Add plugin: Simple Disguise

- community-plugins.json
Link to my plugin: https://github.com/ShermanTsang/obsidian-local-any-files
- [ x ] I have tested the plugin on
- [ x ]  Windows
- [ x ]  Linux
- [ x ] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
- [ x ] `main.js`
- [ x ] `manifest.json`
- [ x ] `styles.css` _(optional)_
- [ x ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [ x ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [ x ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [ x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my …
> Add plugin: Local Any Files

- community-plugins.json
Link to my plugin:https://github.com/webceoboy/moredraw-obsidian
> Add plugin: MoreDraw

- community-plugins.json
Link to my plugin: https://github.com/jhofker/obsidian-hoarder/
> Add plugin: Hoarder Sync

- community-plugins.json
Link to my plugin: https://github.com/bobostudio/obsidian-imgur-plugin
> Add plugin: Tencent COS for Imgur

- community-plugins.json
Link to my plugin: https://github.com/mikevetkin/obsidian-tengwar
> Add plugin: Tengwar

- community-plugins.json
> Add plugin: Circuit Sketcher

- community-plugins.json
Added the plugin Christmas to the list
Link to my plugin: [https://github.com/Matse2005/Obsidian-Christma](https://github.com/Matse2005/Obsidian-Christmas)
> Add plugin: Christmas

- community-plugins.json
Link to my plugin:https://github.com/Hwenyi/obsidian-type-chinese-like-english
> Add plugin: Type Chinese Like English

- community-plugins.json
Link to my plugin: https://github.com/mnaoumov/obsidian-external-rename-handler
> Add plugin: External Rename Handler

- community-plugins.json
Link to my plugin: https://github.com/TheLoneWanderer4/obsidian-uuid-title
> Add plugin: New Filename

- community-plugins.json
Link to my plugin: https://github.com/jancbeck/obsidian-note-annotations/releases/tag/1.0.0
> Add plugin: Note Annotations

- community-plugins.json
Link to my plugin: https://github.com/soundslikeinfo/obsidian-clipper-catalog
> Add plugin: Clipper Catalog

- community-plugins.json
Link to my plugin: https://github.com/Telehakke/hanko
> Add plugin: Hanko

- community-plugins.json
Link to my plugin: https://github.com/forrest1398/obsidian-easyTest-plugin/tree/1.0.0
> Add plugin: Easy Test

- community-plugins.json
Link to my plugin: https://github.com/benjaminezequiel/keep-the-rhythm
> Add plugin: Keep the Rhythm

- community-plugins.json
add obsidian-boardgame-plugin
Link to my plugin: https://github.com/Marlon154/boardgame-search
> Add plugin: Boardgame Search

- community-plugins.json
Sentinel is a plugin for Obsidian that allows you to update properties or run commands based on document visibility changes.
Link to my plugin: https://github.com/gsarig/obsidian-sentinel
> Add plugin: Sentinel

- community-plugins.json
Link to my plugin: https://github.com/MihailKovachev/shaahmaat-md
> Add plugin: ShaahMaat-md

- community-css-themes.json
Link to my theme: https://github.com/laughmaker/Zen
> Add theme: Zen

- community-css-themes.json
Link to my theme: https://github.com/Inc44/OLED.Black
> Add theme: OLED.Black

- community-plugins.json
Link to my plugin: [https://github.com/buzzguy/friend-tracker](https://github.com/buzzguy/friend-tracker)
- [] Windows
> Add plugin: Friend Tracker

- community-plugins.json
> Add plugin: Backgroundset

- community-plugins.json
Link to my plugin: https://github.com/MichaelFW-ui/obsidian-mahgen-plugin
> Add plugin: Mahgen Renderer

- community-plugins.json
Link to my plugin: https://github.com/kamil-rudnicki/obsidian-recent-notes/
> Add plugin: Recent Notes

- community-plugins.json
https://github.com/furst/cooksync-obsidian
> Add plugin: Cooksync

- community-plugins.json
- [ X My README.md describes the plugin's purpose and provides clear usage instructions.
> Add plugin: Goal Tracker

- community-plugins.json
https://github.com/different-ai/file-organizer-200
> Name change: File Organizer -> Note Companion AI

- community-css-themes.json
Link to my theme: https://github.com/babidisrc/obsidian-sunbather
> Add theme: Sunbather

- community-plugins.json
> # I am submitting a new Community Plugin
> ## Repo URL
> Link to my plugin:
> https://github.com/Lemon695/obsidian-plugin-update-locker
> 
> ## Release Checklist
> * [x]  I have tested the plugin on
>   
>   * [ ]   Windows
>   * [x]   macOS
>   * [ ]   Linux
>   * [ ]   Android _(if applicable)_
>   * [ ]   iOS _(if applicable)_
> * [x]  My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
>   
>   * [x]  `main.js`
>   * [x]  `styles.css` _(optional)_
> * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
> * [x]  该 `id` in my `manifest.json` matches the `id` 在 `community-plugins.json` file.
> * …
> Add plugin: Plugin Update Locker

- community-plugins.json
Link to my plugin: https://github.com/kikijiki/obsidian-habit-tracker
> Add plugin: Kikijiki Habit Tracker

- community-plugins.json
Link to my plugin: https://github.com/laantorchaweb/clone-vault/
> Add plugin: Clone Vault

- community-plugins.json
Link to my plugin: https://github.com/LuigiCerone/obsidian-whatsapp-backup-importer
> Add plugin: WhatsApp backup importer

- community-plugins.json
Link to my plugin: https://github.com/Mara-Li/obsidian-context-menu-hider
It is a fork of https://github.com/kzhovn/obsidian-customizable-menu, with removing part handled by Obsidain Commander and reworked the settings. It can import the settings from kzhovn's plugin.
> Add plugin: Context Command Hider

- community-css-themes.json
Link to my theme: https://github.com/rose-pine/obsidian
Note: There are already rose pine themes in here I believe, but none (from what I can see) actually have all the versions in one, as there is the dark and light mode in one of the themes, and then the 'moon' variant in another. This just is a fork of the moon variant with some changes that allow all themes and more customisation (the original of that one also has maintainer perms on this repo). Not sure what the thumbnail should be so it is just a small crop of part of the theme for now, more than willing to change it. The readme in the repo will also be adjusted if this PR goes through to have accurate instructions on using it, since some will change after the PR happens.
- [X ] My repo contains all required files (please *do not* …
> Add theme: Rose Pine

- community-plugins.json
Link to my plugin: https://github.com/Elhary/Obsidian-NetClip
> Add plugin: NetClip

- community-plugins.json
Link to my plugin: https://github.com/JoaoEmanuell/obsidian-whatsapp-export-note
> Add plugin: WhatsApp export note

- community-plugins.json
(https://github.com/FBarrca/obsidian-inlineAI)
> Add plugin: InlineAI

- community-plugins.json
Link to my plugin: https://github.com/scottTomaszewski/obsidian-tag-tactician
> Add plugin: Tag Tactician

- community-plugins.json
Link to my plugin: https://github.com/mnaoumov/obsidian-new-note-fixer
> Add plugin: New Note Fixer

- community-plugins.json
Link to my plugin: https://github.com/jacksteamdev/obsidian-mcp-tools
> Add plugin: MCP Tools

- community-plugins.json
Link to my plugin: https://github.com/pfrankov/obsidian-ai-providers
> Add plugin: AI Providers

- community-plugins.json
https://github.com/LostPaul/obsidian-folder-overview
> Add plugin: Folder overview

- community-plugins.json
https://github.com/Falcion/Whisperer.md
> Add plugin: WHISPERER.md

- community-plugins.json
Link to my plugin: https://github.com/RobertttBS/obsidian-enhanced-canvas.git
> Add plugin: Enhanced Canvas

- community-css-themes.json
Link to my theme:  https://github.com/vran-dev/obsidian-composer
> Add theme: Composer

- community-css-themes.json
Link to my theme: https://github.com/HarmfulBreeze/obsidian-material-3-theme
> Add theme: Material 3

- community-plugins.json
> Add plugin: Varinote

- community-plugins.json
Link to my plugin:  https://github.com/ashwin271/obsidian-vector-search
> Add plugin: Vector Search

- community-plugins.json
Link to my plugin: https://github.com/Wishmater/obsidian-plugin-duplicate-detector
> Add plugin: Duplicate Detector

- community-plugins.json
> Add plugin: Lancaster University Week Format

- community-plugins.json
https://github.com/finnromaneessen/obsidian-sankey
> Add plugin: Sankey

- community-plugins.json
https://github.com/elpamplina/mastodon-threading
> Add plugin: Mastodon Threading

- community-plugins.json
Link to my plugin: https://github.com/pavlokobyliatskyi/obsidian-memodack-plugin
> Add plugin: Memodack

- community-plugins.json
Link to my plugin: [hish-math/obsidian-ai-hub](https://github.com/hish-math/obsidian-ai-hub)
> Add plugin: AI integration Hub

- community-plugins.json
Link to my plugin: https://github.com/glasp-co/obsidian-glasp-plugin 
> Add plugin: Glasp

- community-plugins.json
> Add plugin: Confluence Converter

- community-plugins.json
> Add plugin: CAO

- community-plugins.json
Link to my plugin: https://github.com/emac/obsidian-minote-plugin
> Add plugin: Minote Sync

- community-plugins.json
Link to my plugin: https://github.com/Mr-1311/obsidian-age-encrypt
> Add plugin: Age Encrypt

- community-plugins.json
Link to my plugin: https://github.com/kevinkickback/Combo-Colors
update
> Add plugin: Combo Colors

- community-plugins.json
Link to my plugin: https://github.com/bwya77/autofit-tabs
> Add plugin: Autofit Tabs

- community-plugins.json
Link to my plugin: https://github.com/duchangkim/organized-daily-notes
> Add plugin: Organized daily notes

- community-plugins.json
Link to my plugin: https://github.com/Deedone/obsidian-runsh
> Add plugin: Runsh

- community-plugins.json
> Add plugin: Papyrus

- community-plugins.json
Link to my plugin: https://github.com/xavwe/obsidian-nerdfont-icon-picker
I have given proper attribution to these other projects in my README.md.
> Add plugin: NerdFont Icon Picker

- community-plugins.json
Link to my plugin: https://github.com/Appleec/e-obsidian-upload-plugin
> Add plugin: EUpload

- community-plugins.json
Link to my plugin: https://github.com/Sporarum/every-day-calendar
> Add plugin: Every Day Calendar

- community-plugins.json
> Add plugin: Inkporter

- community-css-themes.json
Commit of Serif Theme
Link to my theme: https://github.com/GodlyMan-bit/Serif
> Add theme: Serif

- community-plugins.json
Link to my plugin: https://github.com/cypar/obsidian-media-link-to-html
- [√ ] I have tested the plugin on
- [ √]  macOS
- [ √] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
- [√ ] `main.js`
- [ √] `manifest.json`
- [ √] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [√ ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [√ ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [√ ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [√ ] I have read the …
> Add plugin: Media Link to HTML

- community-plugins.json
https://github.com/alifa98/obsidian-emoji-picker
> Add plugin: Emoji Picker

- community-plugins.json
Link to my plugin: https://github.com/aaaaalexis/obsidian-pseudo-mica
> Add plugin: Pseudo Mica

- community-plugins.json
Link to my plugin: https://github.com/h-sphere/sql-seal-charts
- []  Windows
> Add plugin: SQLSeal Charts

- community-plugins.json
> Add plugin: hello nemesis

- community-plugins.json
Link to my plugin: https://github.com/sorinmircea/obsidian-forms-plugin
> Add plugin: Forms

- community-plugins.json
Link to my plugin: https://github.com/dominikmayer/obsidian-note-id
> Add plugin: Note ID

- community-plugins.json
Link to my plugin: https://github.com/kdnk/obsidian-automatic-linker
> Add plugin: Automatic Linker

- community-plugins.json
Link to my plugin: https://github.com/jose-elias-alvarez/obsidian-on-this-day
> Add plugin: On This Day

- community-plugins.json
Link to my plugin: https://github.com/land0r/obsidian-flowchart-plugin
> Add plugin: Flowcharts

- community-plugins.json
Link to my plugin:[Saktawdi/obsidian-last-position](https://github.com/Saktawdi/obsidian-last-position)
> Add plugin: Last Position

- community-plugins.json
Link to my plugin: https://github.com/anareaty/html-checkboxes
> Add plugin: HTML checkboxes

- community-plugins.json
Link to my plugin: https://github.com/groldsf/obsidian_check_plugin
> Add plugin: Checkbox Sync

- community-plugins.json
Updating plugin description only
> Update plugin description: Cooksync

- community-plugins.json
Link to my plugin: https://github.com/jkom4/obsidian-pdf-writer
> Add plugin: PDF Writer

- community-plugins.json
Link to my plugin: https://github.com/Cormac-C/obsidian-paste-plugin
> Add plugin: PDF Paste

- community-plugins.json
adding llm-tagger
Link to my plugin: https://github.com/djayatillake/obsidian-llm-tagger
> Add plugin: LLM Tagger

- community-plugins.json
> Add plugin: YourPulse - Your Writing Activity Visualised

- community-css-themes.json
Request for theme to be added to plugins list.
Link to my theme: https://github.com/Halftroll0/Sad-Machine-Druid
> Add theme: Sad Machine Druid

- community-css-themes.json
I am submitting a new Community Theme
Repo URL
Link to my theme: https://github.com/bladeacer/flexcyon
> Add theme: flexcyon

- community-plugins.json
> Add plugin: Rsync

- community-plugins.json
Link to my plugin: https://github.com/kotaindah55/extended-markdown-syntax
> Add plugin: Extended Markdown Syntax

- community-plugins.json
Link to my plugin: https://github.com/Mara-Li/obsidian-my-thesaurus
> Add plugin: My Thesaurus

- community-plugins.json
Link to my plugin: https://github.com/Devon22/obsidian-mediaviewer
> Add plugin: Media Viewer

- community-plugins.json
Link to my plugin: https://github.com/Devon22/obsidian-gridexplorer
> Add plugin: GridExplorer

- community-plugins.json
https://github.com/nemariia/task-mover
> Add plugin: Task Mover

- community-plugins.json
Link to my plugin: https://github.com/fgubler/obsidian-cursor-position-history/
> Add plugin: Cursor Position History

- community-plugins.json
Link to my plugin: https://github.com/travisvn/obsidian-vision-recall
> Add plugin: Vision Recall

- community-plugins.json
Link to my plugin: [https://github.com/thewordisbird/vaultsync](https://github.com/thewordisbird/vaultsync)
> Add plugin: VaultSync

- community-plugins.json
Link to my plugin:https://github.com/liqms/obsidian-content-cards
> Add plugin: Content Cards

- community-plugins.json
A new plugin added.
Link to my plugin: https://github.com/michalekmatej/obsidian.md-ascii-tree-generator
> Add plugin: ASCII Tree Generator

- community-css-themes.json
https://github.com/outsidetext/lesswrong-obsidian
> Add theme: LessWrong

- community-css-themes.json
Link to my theme:  https://github.com/en3sis/vercel-obsidian/
> Add theme: Vercel Geist

- community-css-themes.json
Link to my theme: https://github.com/incantatem2/Obsidian-aged-whisky
> Add theme: aged whisky

- community-plugins.json
Link to my plugin: https://github.com/metagov/koi-obsidian-plugin
> Add plugin: KOI Sync

- community-plugins.json
Description:
Repo URL
Link to my plugin: https://github.com/niehu2018/obsidian-ai-tagger-universe
Release Checklist
> Add plugin: AI Tagger Universe

- community-plugins.json
https://github.com/sleepingraven/obsidian-chat-clips
> Add plugin: Chat clips

- community-css-themes.json
Link to my theme: [https://github.com/LostViking09/obsidian-fastppuccin](https://github.com/LostViking09/obsidian-fastppuccin)
> Add theme: FastPpuccin

- community-plugins.json
Link to my plugin: https://github.com/leoleelxh/obsidian-memos-ai-sync/
> Add plugin: Memos AI Sync

- community-plugins.json
[https://github.com/garethng/obsidian-blog-generator](https://github.com/garethng/obsidian-blog-generator)
> Add plugin: Blog AI Generator

- community-plugins.json
Link to my plugin: https://github.com/ai-learning-tools/obsidian-spaced-repetition-ai
> Add plugin: Spaced Repetition AI

- community-plugins.json
Link to my plugin: https://github.com/MoxAlehin/TierList
> Add plugin: Tier List

- community-plugins.json
Link to my plugin: https://github.com/markahesketh/write-good-obsidian
> Add plugin: Write Good

- community-plugins.json
Link to my plugin: https://github.com/LukasKorotaj/Scroll-With-j-k-in-Obsidian
> Add plugin: Reading View j/k Scroll

- community-plugins.json
Link to my plugin: https://github.com/seantiz/obsidian_egv_plugin
- [x ]  macOS
- [x ] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
- [x ] `styles.css` _(optional)_
- [x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these …
> Add plugin: Export Graph View

- community-plugins.json
Link to my plugin: https://github.com/marcueberall/obsidian-harn-weather
> Add plugin: Hârn Weather Generator

- community-plugins.json
> Change description for Attachments MD Indexer

- community-plugins.json
Link to my plugin: https://github.com/talau/obsidian-previous-daily-note
> Add plugin: Previous Daily Note

- community-plugins.json
Link to my plugin: https://github.com/stfrigerio/sqliteDB
> Add plugin: SQLite DB

- community-plugins.json
Link to my plugin: https://github.com/Feng6611/Obsidian-File-Ignore
> Add plugin: File Ignore

- community-plugins.json
Link to my plugin: https://github.com/zhouhua/obsidian-waveform-player
> Add plugin: Waveform Player

- community-plugins.json
Link to my plugin: https://github.com/LucasJi/jade-publisher
> Add plugin: Jade Publisher

- community-plugins.json
Link to my plugin: https://github.com/janisringli/bible-sidecar-obsidian-plugin/tree/main
> Add plugin: Bible sidecar

- community-plugins.json
Link to my plugin: https://github.com/0melette/copy-local-graph-paths
> Add plugin: Copy Local Graph Paths

- community-plugins.json
Link to my plugin: https://github.com/Andre-Diamond/note-metrics
> Add plugin: Daily Note Metrics

- community-plugins.json
Link to my plugin: https://github.com/tynanpurdy/musical-text
> Add plugin: Musical Text

- community-plugins.json
Link to my plugin: https://github.com/dk949/obsidian-mode-manager
> Add plugin: Mode manager

- community-plugins.json
Link to my plugin: https://github.com/XZSt4nce/note-placeholder
> Add plugin: Note Placeholder

- community-plugins.json
> Add plugin: URI Converter

- community-plugins.json
Link to my plugin: https://github.com/lhinxue/obsidian-inline-code-copy-plugin
> Add plugin: Inline Code Copy

- community-plugins.json
Link to my plugin: https://github.com/yingflower/obsidian-stu-repo-helper
> Add plugin: Student Repo

- community-plugins.json
https://github.com/AriTheElk/obsidian-image-picker
> Add plugin: Image Picker

- community-plugins.json
> Add plugin: CSV All-in-One

- community-plugins.json
Link to my plugin: https://github.com/weph/obsidian-bookshelf
> Add plugin: Bookshelf

- community-plugins.json
Link to my plugin: https://github.com/alimoeeny/obsidian-dropbox-photo-grid
> Add plugin: Dropbox Photo Grid

- community-plugins.json
> Add plugin: Idealogs Annotator

- community-plugins.json
An [Obsidian](https://obsidian.md/) plugin to capture and manage academic papers
Link to my plugin: https://github.com/ras0q/obsidian-paper-clipper
> Add plugin: Paper Clipper

- community-css-themes.json
> Change the author: Lumines

- community-plugins.json
Link to my plugin: https://github.com/vaibzzz123/multiple-daily-notes/
> Add plugin: Multiple Daily Notes

- community-plugins.json
Link to my plugin: https://github.com/pedrogdn/obsidian-time-bullet-plugin
> Add plugin: Time Bullet

- community-plugins.json
Link to my plugin:https://github.com/busyoGG/SmoothCursor
> Add plugin: Smooth Cursor

- community-plugins.json
Link to my plugin: https://github.com/12-VidE/annotate-audio
> Add plugin: Annotate Audio

- community-plugins.json
Link to my plugin: https://github.com/wenlzhang/obsidian-file-title-updater
> Add plugin: File Title Updater

- community-plugins.json
Link to my plugin: https://github.com/BambusControl/obsidian-chronotyper
> Add plugin: Chronotyper

- community-plugins.json
https://github.com/onikun94/line_to_obsidian
> Add plugin: LINE Notes Sync

- community-plugins.json
Link to my plugin: https://github.com/Asrieal/HoverReveal
> Add plugin: Hover Reveal

- community-plugins.json
Link to my plugin: https://github.com/Ghost04718/Daily-News-Briefing
> Add plugin: Daily News Briefing

- community-plugins.json
Link to my plugin: https://github.com/LeCheenaX/WordFlow-Tracker/
> Add plugin: Wordflow Tracker

- community-plugins.json
https://github.com/al0cam/AutoMover
> Add plugin: AutoMover

- community-plugins.json
Link to my plugin: https://github.com/wenlzhang/obsidian-canvas-format-brush
> Add plugin: Canvas Format Brush

- community-css-themes.json
Link to my theme: https://github.com/MrParalloid/obsidian-things/tree/main
> Add theme: Things 3

- community-plugins.json
Link to my plugin: https://github.com/MarsBatya/tg-emoji-search
> Add plugin: TG Emoji Search

- community-plugins.json
Add docmarionum1/obsidian-pinned-daily-notes
Link to my plugin: https://github.com/docmarionum1/obsidian-pinned-daily-notes
> Add plugin: Pinned Daily Notes

- community-plugins.json
Link to my plugin: https://github.com/uglyboy-tl/obsidian-ink-player
> Add plugin: Ink Player

- community-plugins.json
Link to my plugin: https://github.com/dragonish/obsidian-heading-decorator
> Add plugin: Heading Decorator

- community-plugins.json
Link to my plugin: https://github.com/cactuzhead/Advanced-Progress-Bars
> Add plugin: Advanced Progress Bars

- community-plugins.json
An Obsidian plugin that uses AI to generate and track research questions based on your notes.
Link to my plugin: https://github.com/narthur/research-quest
> Add plugin: Research Quest

- community-plugins.json
Link to my plugin: https://github.com/brianpetro/smart-chatgpt-obsidian
- [ x]  macOS
- [x ] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
- [x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's …
> Add plugin: Smart ChatGPT

- community-plugins.json
Link to my plugin: https://github.com/silvanocerza/obsidian-github-sync
> Add plugin: GitHub Gitless Sync

- community-plugins.json
https://github.com/22-2/wheel-tab-switcher
> Add plugin: Wheel Tab Switcher

- community-plugins.json
Link to my plugin: https://github.com/bwya77/collapsible-code-blocks
> Add plugin: Collapsible Code Blocks

- community-plugins.json
Link to my plugin: https://github.com/SpaceshipCaptain/CmdSearch
> Add plugin: CmdSearch

- community-plugins.json
Link to my plugin: https://github.com/sstallion/obsidian-command-line
- [x I have tested the plugin on
> Add plugin: Command Line

- community-plugins.json
Link to my plugin: https://github.com/davidjconnolly/obsidian-ai-helper
> Add plugin: AI Helper

- community-plugins.json
Link to my plugin: https://github.com/shumadrid/obsidian-git-changelog
> Add plugin: Git Changelog

- community-plugins.json
Link to my plugin: [https://github.com/stefandanzl/webviewer-bookmarks](https://github.com/stefandanzl/webviewer-bookmarks)
- [] Windows
- [] Android _(if applicable)_
- [] `styles.css` _(optional)_
> Add plugin: Xiaohongshu Importer

- community-plugins.json
Link to my plugin: https://github.com/danferns/obsidian-wordcraft
> Add plugin: WordCraft

- community-plugins.json
https://github.com/davidingerslev/outlook-meeting-notes
> Add plugin: Outlook Meeting Notes

- community-plugins.json
Link to my plugin: https://github.com/ethanolivertroy/obsidian-markitdown
- [X ] I have tested the plugin on
- [X ]  Windows
- [X ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
> Add plugin: Markitdown File Converter

- community-plugins.json
Link to my plugin: https://github.com/CalfMoon/node-factor
> Add plugin: Node Factor

- community-plugins.json
Link to my plugin: [https://github.com/Andrii256/ops_obsidian_smart-day-night-switcher](https://github.com/Andrii256/ops_obsidian_smart-day-night-switcher)
> Add plugin: Smart DayNight switcher

- community-plugins.json
https://github.com/ankit-kapur/obsidian-kanban-status-updater-plugin
> Add plugin: Kanban Status Updater

- community-css-themes.json
https://github.com/ninetyfive666/Planetary
> Add theme: Planetary

- community-plugins.json
Link to my plugin: https://github.com/semanticdata/obsidian-pomodoro
> Add plugin: PomoBar

- community-plugins.json
Link to my plugin: https://github.com/Shanshuimei/obsidian-generate-timeline
> Add plugin: Generate Timeline

- community-plugins.json
Link to my plugin: https://github.com/CatMuse/HiNote
> Add plugin: HiNote

- community-plugins.json
Link to my plugin: https://github.com/markusmo3/obsidian-private-mode
> Add plugin: Private Mode

- community-plugins.json
Link to my plugin: https://github.com/flyingnobita/obsidian-github-stars
> Add plugin: GitHub Stars

- community-plugins.json
Link to my plugin: https://github.com/artemkorsakov/project-euler-stats
> Add plugin: Project Euler Stats

- community-plugins.json
Link to my plugin: https://github.com/lukas-cap/simple-file-info
> Add plugin: Simple File Info

- community-plugins.json
https://github.com/gasparschott/smooth-navigator
- [ X] I have tested the plugin on
- [X ]  macOS
- [X ] `main.js`
- [X ] `manifest.json`
- [X ] `styles.css` _(optional)_
- [X ] GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
- [X ] The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
- [X ] My README.md describes the plugin's purpose and provides clear usage instructions.
- [X ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my plugins's adherence to these policies.
- [X ] I have read the tips in https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines and have self-reviewed …
> Add plugin: Smooth Navigator

- community-plugins.json
> Add plugin: GitHub Tracker

- community-plugins.json
Link to my plugin: https://github.com/screendotgarden/screengarden-obsidian
> update screen.garden description

- community-plugins.json
Link to my plugin: https://github.com/leschuster/obsidian-advanced-copy
> Update Advanced Copy description

- community-plugins.json
Add wewrite plugin
Link to my plugin: https://github.com/learnerchen-forever/wewrite
> Add plugin: WeWrite

- community-plugins.json
Link to my plugin: https://github.com/Mossy1022/Smart-Connections-Vault-Visualizer
- [x ]  macOS
- [x ] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
- [x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my …
> Add plugin: Smart Vault Visualizer

- community-plugins.json
Link to my plugin: https://github.com/noy4/browser-history
> Add plugin: Browser History

- community-plugins.json
Link to my plugin: https://github.com/mrboxtobox/obsidian-related-notes
> Add plugin: Related Notes

- community-plugins.json
Link to my plugin: https://github.com/zhouhua/obsidian-white-noise
> Add plugin: White Noise

- community-plugins.json
Link to my plugin: https://github.com/Alamion/obsidian-jira-sync
> Add plugin: Jira Issue Manager

- community-css-themes.json
Link to my theme: https://github.com/LennZone/Neumorphism
> Add theme: Neumorphism

- community-css-themes.json
Link to my theme: https://github.com/incantatem2/Obsidian-cocoa
> Add theme: cocoa

- community-css-themes.json
Link to my theme: https://github.com/incantatem2/Obsidian-parfait
> Add theme: parfait

- community-css-themes.json
Added theme "Camena"
Link to my theme: https://github.com/splendidissimemendax/Camena
> Add theme: Camena

- community-css-themes.json
Link to my theme: https://github.com/MrParalloid/pomme-notes/
> Add theme: Pomme Notes

- community-css-themes.json
> Add theme: Dust

- community-css-themes.json
Link to my theme: https://github.com/incantatem2/Obsidian-deep-submerge
> Add theme: deep submerge

- community-css-themes.json
https://github.com/manuelcoca/obsidian-mono-high-contrast-theme
> Add theme: Mono High Contrast

- community-css-themes.json
Link to my theme: https://github.com/aidanastridge/Publisher
> Add theme: Publisher

- community-plugins.json
Link to my plugin: https://github.com/webtechaccess/obsidian-heatmap-calendar
> Add plugin: Codeless Heatmap Calendar

- community-plugins.json
https://github.com/benstuart0/on-this-day-i-obsidian
> Add plugin: On This Day I

- community-plugins.json
Link to my plugin: https://github.com/eharris128/Obsidian-LLM-Plugin
> Add plugin: Large Language Models

- community-plugins.json
Link to my plugin: https://github.com/d7sd6u/obsidian-hide-index-files
> Add plugin: Hide Index Files

- community-plugins.json
Link to my plugin: https://github.com/d7sd6u/obsidian-crosslink-advanced
> Add plugin: Crosslink Advanced

- community-plugins.json
Link to my plugin: https://github.com/dalecgu/obsidian-sticky-notes
> Add plugin: Digital Sticky Notes

- community-plugins.json
Link to my plugin:  
https://github.com/liufree/obsidian-querydash
> Add plugin: QueryDash

- community-plugins.json
Start a quick Markdown-based quiz on your current note. Simple, straightforward, and fully integrated into Obsidian — similar to flashcards in Anki or Quizlet!
Link to my plugin: https://github.com/Lutu-gl/Obsidian-Minimal-Quiz
> Add plugin: Minimal Quiz

- community-plugins.json
Link to my plugin: https://github.com/takitsuba/obsidian-auto-bullet
> Add plugin: Auto Bullet

- community-plugins.json
Link to my plugin: [mts7/obsidian-word-frequency](https://github.com/mts7/obsidian-word-frequency)
> Add plugin: Word Frequency

- community-plugins.json
Add my new "Interactive Ratings" plugin to the list.
Link to my plugin: https://github.com/peritus/obsidian-interactive-ratings
> Add plugin: Interactive Ratings

- community-plugins.json
Link to my plugin: https://github.com/OLCUBO/obsidian-cubox
> Add plugin: Cubox

- community-plugins.json
Link to my plugin: <https://github.com/stracker-phil/obsidian-mention-things>
> Add plugin: Mention Things

- community-plugins.json
Link to my plugin: https://github.com/vannamhh/progress-tracker
> Add plugin: ProgressTracker

- community-plugins.json
Link to my plugin: https://github.com/aqeja/ClipperMaster-for-Obsidian
> Add plugin: ClipperMaster

- community-plugins.json
Add the paste-reformatter plugin.
> Add plugin: Paste Reformatter

- community-plugins.json
Link to my plugin: https://github.com/LIUBINfighter/obsidian-csv-lite
> Add plugin: CSV Lite

- community-plugins.json
Link to my plugin: https://github.com/mnaoumov/obsidian-advanced-debug-mode
> Add plugin: Advanced Debug Mode

- community-plugins.json
Link to my plugin: https://github.com/Felvesthe/Note-Locker
> Add plugin: Note Locker

- community-plugins.json
Link to my plugin: https://github.com/ahmetildirim/obsidian-inscribe
> Add plugin: Inscribe

- community-plugins.json
Link to my plugin: https://github.com/playmean/obsidian-event-highlight-plugin
> Add plugin: Event Highlight

- community-plugins.json
Link to my plugin: https://github.com/litegral/auto-daily-note
> Add plugin: Auto Daily Note

- community-plugins.json
Link to my plugin: https://github.com/chrisgrieser/obsidian-proofreader
> Add plugin: Proofreader

- community-plugins.json
Link to my plugin: https://github.com/dominikmayer/obsidian-reader-mode
> Add plugin: Reader Mode

- community-plugins.json
Link to my plugin: https://github.com/mildeveloper/obsidian-date-range-expander
> Add plugin: Date Range Expander

- community-plugins.json
Link to my plugin: https://github.com/mnaoumov/obsidian-advanced-note-composer
> Add plugin: Advanced Note Composer

- community-plugins.json
https://github.com/msakowski/obsidian-library-linker
> Add plugin: JW Library Linker

- community-plugins.json
Link to my plugin: https://github.com/dee158/obsidian-rainbow-folders-fixer
> Add plugin: Rainbow Folders Fixer

- community-plugins.json
Link to my plugin: https://github.com/sky150/obsidian-image-embedder
> Add plugin: Image Embedder

- community-plugins.json
Link to my plugin: https://github.com/Ai-Jani/about-blank
> Add plugin: About Blank

- community-plugins.json
Link to my plugin: https://github.com/d-eniz/jupymd
> Add plugin: JupyMD

- community-plugins.json
Link to my plugin: https://github.com/d7sd6u/obsidian-reveal-folded
> Add plugin: Reveal Folded

- community-plugins.json
Link to my plugin: https://github.com/DontBlameMe99/Tick-Tones
> Add plugin: Tick Tones

- community-plugins.json
Link to my plugin: https://github.com/janispritzkau/obsidian-model-viewer
> Add plugin: Model Viewer

- community-plugins.json
Link to my plugin: https://github.com/adamfletcher/obsidian-sentence-rhythm
> Add plugin: Sentence Rhythm

- community-css-themes.json
https://github.com/dubefab/obsidian-TerraFlow
- [x ] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [x ] `theme.css`
- [ x] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [x ] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [ x] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [x ] I have added a license in the LICENSE file.
- [x ] My project respects and is compatible …
> Add theme: TerraFlow

- community-css-themes.json
Link to my theme:  https://github.com/ThePharaohArt/Obsidian-RetroOS98
> Add theme: RetroOS 98

- community-css-themes.json
Link to my theme: https://github.com/theaayushpatel/quillcode
> Add theme: Quillcode

- community-css-themes.json
Link to my theme: https://github.com/GodlyMan-bit/SoliDeoGloria
> Add theme: Soli Deo Gloria

- community-css-themes.json
https://github.com/pr0methevs/Hojicha
> Add theme: Hojicha

- community-plugins.json
Link to my plugin: https://github.com/clockblocker/filler-de
> Add plugin: Textfresser

- community-plugins.json
Link to my plugin: https://github.com/Maclean-D/obsidian-limitless-lifelogs
- [ X] My project respects and is compatible with the original license of any code from other plugins that I'm using.
> Add plugin: Limitless Lifelogs

- community-plugins.json
Link to my plugin: https://github.com/Kovah/obsidian-rainbow-colored-sidebar
> Add plugin: Rainbow-Colored Sidebar

- community-plugins.json
Link to my plugin: https://github.com/MartinDampier/draw-steel-retainer/tree/1.0.4
> Add plugin: Draw Steel Retainer

- community-plugins.json
https://github.com/Prodigist/ReactiveNotes
https://github.com/Prodigist/ReactiveNotes/releases/tag/1.0.0
> Add plugin: Reactive Notes

- community-plugins.json
Link to my plugin: https://github.com/LuigiCerone/obsidian-water-tracker
> Add plugin: Water Tracker

- community-plugins.json
Link to my plugin: https://github.com/obsidian-memodack-plugin/obsidian-memodack-plugin
> Update plugin: Memodack

- community-plugins.json
Link to my plugin: https://github.com/willem-schlieter/lawlist
> Add plugin: LawList: Custom List Styles

- community-plugins.json
Removing the duplicate plugin entry in community-plugins.json
> removing duplicate plugin

- community-plugins.json
Link to my plugin: https://github.com/devonthesofa/obsidian-note-status
> Add plugin: Note Status

- community-plugins.json
Link to my plugin: https://github.com/Sophokles187/data-cards
- [ x]  macOS
- [ x]  Linux
- [ x]  Android _(if applicable)_
- [ x] My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
- [x ] I have read the developer policies at …
> Add plugin: DataCards

- community-plugins.json
Link to my plugin: https://github.com/gapmiss/inline-callouts
> Add plugin: Inline Callouts

- community-plugins.json
https://github.com/tazihad/obsidian-easy-keep-view
> Add plugin: Easy Keep View

- community-css-themes.json
Link to my theme: https://github.com/Spekulucius/obsidian-marathon
> Add theme: Marathon

- community-css-themes.json
Link to my theme: [https://github.com/kmranrg/obsidian-handwriting-theme](https://github.com/kmranrg/obsidian-handwriting-theme)
> Add theme: Handwriting (Kalam)

- community-css-themes.json
https://github.com/omarrashad/obsidian-vesper
> Add theme: Vesper

- community-plugins.json
Link to my plugin: https://github.com/DontBlameMe99/Tick-Tones
> Modify plugin description: Tick Tones

- community-plugins.json
Link to my plugin: https://github.com/tu2-atmanand/obsidian-notes-explorer
> Add plugin: Notes Explorer

- community-plugins.json
Link to my plugin: https://github.com/JinmuGo/obsidian-markdown-flip
> Add plugin: Markdown Flip

- community-plugins.json
Link to my plugin: https://github.com/formax68/memoChron
- [-] I have tested the plugin on
> Add plugin: MemoChron

- community-plugins.json
> Add plugin: Paste Image Rename and Convert

- community-plugins.json
Link to my plugin: https://github.com/chararch/obsidian-enhanced-publisher
> Add plugin: Enhanced Publisher

- community-plugins.json
Link to my plugin: https://github.com/lowitea/obsidian-tasks-cleaner
> Add plugin: Tasks Cleaner

- community-plugins.json
Link to my plugin: https://github.com/rplatonovs/obsidian-jira-links-shortener
> Add plugin: JIRA links shortener

- community-plugins.json
https://github.com/adamfletcher/obsidian-cut-the-fluff
> Add plugin: Cut The Fluff

- community-css-themes.json
Link to my theme: [https://github.com/SourTarte/Powered-By-Lancer](url)
> Add theme: Powered by Lancer

- community-plugins.json
Link to my plugin: https://github.com/Jalad25/vertical-timeline-list
> Add plugin: Vertical Timeline List

- community-plugins.json
Link to my plugin: https://github.com/JasperSurmont/obsidian-comments
> Add plugin: Comments

- community-plugins.json
I have submitted this plugin previously (#4788), but didn't get around to addressing a requested change at the time, so the submission was closed.
Link to my plugin: https://github.com/Signynt/virtual-footer
> Add plugin: Virtual Footer

- community-plugins.json
Link to my plugin: https://github.com/JinmuGo/obsidian-theme-by-folder
> Add plugin: Theme by Folder

- community-plugins.json
Link to my plugin: https://github.com/kazhuravlev/obsidian-github
> Add plugin: GitHub Integration

- community-plugins.json
> File ignore Update Description

- community-css-themes.json
new theme Terminal2K
[](https://github.com/isax785/Terminal2K)
- [ x] My repo contains all required files (please *do not* add them to this `obsidian-releases` repo).
- [x ] `theme.css`
- [x ] The screenshot file (16:9 aspect ratio, recommended size is 512px by 288px for fast loading).
- [ x] I have indicated which modes (dark, light, or both) are compatible with my theme.
- [x ] I have read the developer policies at https://docs.obsidian.md/Developer+policies, and have assessed my theme's adherence to these policies.
- [x ] I have read the tips in https://docs.obsidian.md/Themes/App+themes/Theme+guidelines and have self-reviewed my theme to avoid these common pitfalls.
- [ x] My project respects …
> Add theme: Terminal2K

- community-plugins.json
Link to my plugin: https://github.com/callumalpass/obsidian-biblib
> Add plugin: BibLib

- community-css-themes.json
Link to my theme: https://github.com/mvahaste/meridian
> Add theme: Meridian

- community-css-themes.json
https://github.com/bladeacer/flexcyon
> Update Theme Entry: community-css-themes.json

- community-plugins.json
Link to my plugin: https://github.com/64MM4-KN1F3/regex-line-filter
> Add plugin: Regex Line Filter

- community-plugins.json
Link to my plugin: https://github.com/heavenlygaze/obsidian-todo-highlighter
> Add plugin: TODO Highlighter

- community-plugins.json
> Add plugin: Hadith Lookup

- community-plugins.json
Link to my plugin: https://github.com/bzimor/obsidian_hledger
> Add plugin: Hledger Notes

- community-plugins.json
> # I am submitting a new Community Plugin
> ## Repo URL
> Link to my plugin: https://github.com/Chen2226/obsidian-typecho
> 
> ## Release Checklist
> * [x]  I have tested the plugin on
>   
>   * [x]   Windows
>   * [ ]   macOS
>   * [ ]   Linux
>   * [ ]   Android _(if applicable)_
>   * [ ]   iOS _(if applicable)_
> * [x]  My GitHub release contains all required files (as individual files, not just in the source.zip / source.tar.gz)
>   
>   * [x]  `main.js`
>   * [x]  `styles.css` _(optional)_
> * [x]  GitHub release name matches the exact version number specified in my manifest.json (_**Note:** Use the exact version number, don't include a prefix `v`_)
> * [x]  The `id` in my `manifest.json` matches the `id` in the `community-plugins.json` file.
> * [x]  My …
> Add plugin: Typecho

- community-plugins.json
> Add plugin: Zen Space

- community-plugins.json
Link to my plugin: https://github.com/easternkite/Pasterly
> Add plugin: Pasterly

- community-plugins.json
Link to my plugin:https://github.com/Yeban8090/mp-preview
> Add plugin: MP Preview

- community-plugins.json
Link to my plugin: https://github.com/taskrobin/Obsidian-Plugin/
> Add plugin: Sync Emails

- community-plugins.json
Link to my plugin: https://github.com/ericmwalk/obsidian-statuslol/tree/main
> Add plugin: Status.lol Publisher

- community-plugins.json
Link to my plugin: [https://github.com/NoHeartPen/obsidian-monokakido-copilot-plugin](https://github.com/NoHeartPen/obsidian-monokakido-copilot-plugin)
> Add plugin: Monokakido Copilot

- community-plugins.json
Link to my plugin: https://github.com/remememe/Live-Wallpaper
> Add plugin: Live Background

- community-plugins.json
Link to my plugin: https://github.com/Rodolfo-Terriquez/images-to-notes
> Add plugin: Images to Notes

- community-plugins.json
Link to my plugin: https://github.com/especialkim/markdown-hijacker/
> Add plugin: Markdown Hijacker

- community-plugins.json
Link to my plugin: https://github.com/uppinote20/obsidian-auto-note-importer
> Add plugin: Auto Note Importer

- community-css-themes.json
> New author: Lumines

- community-css-themes.json
> Add theme: Duality

- community-plugins.json
> Update Plugin: update plugin description

- community-plugins.json
Link to my plugin: https://github.com/dainakai/obsidian-yaml-table
> Add plugin: YAML Table

- community-plugins.json
Link to my plugin:https://github.com/Yeban8090/book-smith
> Add plugin: Book Smith

- community-plugins.json
https://github.com/zigholding/obsidian-notesync-plugin
> Add plugin: Note Sync

- community-css-themes.json
Link to my theme: https://github.com/incantatem2/Obsidian-dashboard
> Add theme: dashboard

- community-plugins.json
Link to my plugin: https://github.com/Moyf/yearly-glance
> Add plugin: Yearly Glance

- community-plugins.json
add plugin
Link to my plugin: https://github.com/artemDvoryadkin/obsidian-vim-marker-sharpener
> Add plugin: Vim Marker Sharpener

- community-plugins.json
Link to my plugin: https://github.com/TheJusticeMan/pure-chat-llm
> Add plugin: Pure Chat LLM

- community-plugins.json
Link to my plugin: https://github.com/insile/OpenWords
> Add plugin: OpenWords

- community-plugins.json
Link to my plugin: https://github.com/zarstensen/obsidian-latex-math
> Add plugin: LaTeX Math

- community-plugins.json
Link to my plugin: https://github.com/shane-lamb/obsidian-llm-docs
> Add plugin: LLM docs

- community-plugins.json
Link to my plugin: https://github.com/JimJamBimBam/obsidian-log-keeper/tree/1.3.0
> Add plugin: Log Keeper

- community-plugins.json
> Add plugin: Streams

- community-plugins.json
Link to my plugin: https://github.com/ShadiestGoat/obsidian-layout-manager
> Add plugin: Layout Manager

- community-css-themes.json
Link to my theme: https://github.com/JabariD/obsidian-radiance
> Add theme: Radiance

- community-css-themes.json
Link to my theme: https://github.com/kyffa/Iridium
> Add theme: Iridium

- community-plugins.json
Link to my plugin: nitishkhurana/obsidian-move-files-plugin
> Add plugin: Move Files

- community-plugins.json
Link to my plugin: https://github.com/limpido/obsidian-tree-diagram
> Add plugin: Tree Diagram

- community-plugins.json
Added text autocomplete plugin
Link to my plugin: https://github.com/c-degni/text-autocomplete
> Add plugin: Text Autocomplete

- community-plugins.json
Link to my plugin: https://github.com/eatcodeplay/obsidian-simple-banner
> Add plugin: Simple Banner

- community-plugins.json
Link to my plugin: https://github.com/saberzero1/quartz-syncer
> Add plugin: Quartz Syncer

- community-plugins.json
Link to my plugin: https://github.com/maigamo/daily-task-auto-generator
`main.js`
> Update plugin: Daily Task Auto Generator

- community-plugins.json
Link to my plugin: [https://github.com/lazerfit/korean-book-search-plugin/tree/1.0.0](https://github.com/lazerfit/korean-book-search-plugin/tree/1.0.0)
> Add plugin: Korean Book Search

- community-plugins.json
Link to my plugin: https://github.com/camadkins/obsidian-canvas-connect
> Add plugin: Canvas Connect

- community-plugins.json
https://github.com/Grayvox/obsidian-character-sheets
> Add plugin: Character Sheets

- community-plugins.json
Link to my plugin: https://github.com/okawak/discord_message_sender
> Add plugin: Discord Message Sender

- community-plugins.json
Link to my plugin: https://github.com/Alecell/auto-replacer
> Add plugin: Auto Replacer

- community-plugins.json
Link to my plugin: https://github.com/sidkhuntia/obsdian-headings-helper
> Add plugin: Heading Helper

- community-plugins.json
https://github.com/omeyenburg/obsidian-scrolling
> Add plugin: Scrolling

- community-css-themes.json
Link to my theme: https://github.com/bellebasso/Minimalists-Paradise
> Update community-css-themes.json Minimalist's Paradise repo changes

- community-css-themes.json
Link to my theme: https://github.com/cheycron/flat-cap-obsidian
> Add theme: FlatCap

- community-css-themes.json
Link to my theme:  https://github.com/Vlad3Design/Mushin
> Add theme: Mushin

- community-css-themes.json
- community-plugins.json
> Add plugin: Eccirian Encrypt

- community-plugins.json
> Add plugin: Coalesce

- community-plugins.json
Link to my plugin:https://github.com/penyt/replace-pencil
> Add plugin: Replace Pencil

- community-plugins.json
Link to my plugin: https://github.com/Mara-Li/obsidian-alpha-bullet
> Add plugin: Alpha Bullet

- community-plugins.json
Link to my plugin: https://github.com/kvh03/obsidian-scratchpad
> Add plugin: Scratchpad

- community-plugins.json
Link to my plugin: https://github.com/mousebomb/obsidian-diary-ics
> Add plugin: Diary ICS

- community-plugins.json
Link to my plugin: https://github.com/AMC-Albert/obsidian-sidecars
> Add plugin: Sidecars

- community-plugins.json
Link to my plugin: https://github.com/michaelmassoni/obsidian-soc-toolkit
> Add plugin: SOC Toolkit

- community-plugins.json
Link to my plugin: https://github.com/zachatrocity/md-cal-gen
> Add plugin: Markdown Calendar Generator

- community-css-themes.json
Link to my theme: https://github.com/Riffaells/Robsi
> Add theme: Robsi

- community-plugins.json
> Add plugin: Timeline Canvas Creator

- community-plugins.json
> Add plugin: Simple Anki Sync

- community-plugins.json
Link to my plugin: https://github.com/Rerurate514/insert_ArknightsURL_banners
> Add plugin: Insert Arknights URL Banner

- community-plugins.json
Link to my plugin: https://github.com/linem-davton/obsidian-better-mindmap
> Add plugin: Better Mind Map

- community-plugins.json
Link to my plugin: [obsidian-blueprint-renderer](https://github.com/goderyu/obsidian-blueprint-renderer)
> Add plugin: Blueprint Renderer

- community-css-themes.json
Link to my theme: https://github.com/norderan/RedShift-obsidian-theme
> Add theme: RedShift: OLED Blue Light Filter

- community-plugins.json
Link to my plugin: https://github.com/mali-i/obsidian-Deepseek-ai-assistant-plugin
> Add plugin: deepseek-ai-assistant

- community-plugins.json
Link to my plugin: https://github.com/forketyfork/obsidian-food-tracker
> Add plugin: Food Tracker

- community-plugins.json
Link to my plugin: https://github.com/TiagoJacinto/obsidian-object-oriented-thinking
> Add plugin: Object Oriented Thinking

- community-plugins.json
Link to my plugin: https://github.com/wenlzhang/obsidian-send-to-canvas
> Add plugin: Send to Canvas

- community-plugins.json
Add t4-task-tree-time-totaler.
> Add plugin: T4: Task Tree Time Totaler

- community-plugins.json
Link to my plugin: https://github.com/SamW7140/obsidian-storyteller-suite
> Add plugin: Storyteller Suite

- community-plugins.json
Link to my plugin: [Simple Columns](https://github.com/Josie1902/Simple-Columns)
> Add plugin: Simple Columns

- community-plugins.json
Link to my plugin: https://github.com/SpencerF718/obsidian-random-wikipedia
> Add plugin: Random Wikipedia Article

- community-plugins.json
Link to my plugin: https://github.com/LonoxX/obsidian-github-issues
> Add plugin: Github Issues

- community-plugins.json
> Add plugin: Sonkil

- community-plugins.json
https://github.com/Marvive/Citation-Callouts
> Add plugin: Citation Callouts

- community-plugins.json
Link to my plugin: https://github.com/Koishiiko/obsidian-webdav-image-uploader
> Add plugin: WebDAV Image Uploader

- community-plugins.json
Link to my plugin: https://github.com/ai-bytedance/obsidian-cloud-sync
> Add plugin: Cloud sync

- community-plugins.json
> Add plugin: Checkbox Autochecker

- community-plugins.json
> Add plugin: Pixel Pets

- community-plugins.json
Link to my plugin: https://github.com/asibilia/obsidian-quick-emoji
> Add plugin: Quick Emoji

- community-plugins.json
The plugin now supports mobile devices as of v0.8.0, so updating the description to reflect this capability.
Link to my plugin: https://github.com/joybro/obsidian-similar-notes
> Update plugin description: Similar Notes

- community-css-themes.json
Link to my theme: https://github.com/aaaaalexis/obsidian-baseline
> Add theme: Baseline

- community-plugins.json
Link to my plugin: https://github.com/gabosgab/ObsidianPrivateAI
> Add plugin: Private AI

- community-plugins.json
Link to my plugin: https://github.com/davidvkimball/obsidian-custom-slides
> Add plugin: Custom Slides

- community-css-themes.json
https://github.com/konnta0/obsidian-noctis-theme
> Add theme: Noctis

- community-plugins.json
Link to my plugin: https://github.com/mariomui/scroll-to-nav-top
> Add plugin: Scrolls To Nav Top

- community-plugins.json
Link to my plugin: [https://github.com/jjwheatley/mini-rag](https://github.com/jjwheatley/mini-rag)
> Add plugin: Mini-RAG

- community-plugins.json
Link to my plugin: https://github.com/chernodub/obsidian-llm-shortcut
> Add plugin: LLM Shortcut

- community-plugins.json
Link to my plugin: [Linked Note Exporter](https://github.com/the-c0d3r/obsidian-linked-note-exporter)
> Add plugin: Linked Note Exporter

- community-plugins.json
Link to my plugin: https://github.com/bao-tg/kindle-vocab
> Add plugin: Kindle Vocab

- community-css-themes.json
https://github.com/vupdivup/obsidian-everforest-spruce
> Add theme: Everforest Spruce

- community-css-themes.json
Link to my theme: https://github.com/NoahBoos/obsidian-theme-rift
> Update "Rift" by adding "light" aspect.

- community-plugins.json
Drag To Scroll (drag-to-scroll)
https://github.com/constsz/obsidian-drag-to-scroll
https://github.com/constsz/obsidian-drag-to-scroll/releases/tag/1.0.1
(not used any code from other projects)
> Add plugin: Drag To Scroll

- community-css-themes.json
Link to my theme: https://github.com/Gonzalo-D-Sales/obsidian-velocity
> Add theme: Velocity

- community-plugins.json
Link to my plugin: https://github.com/ras0q/obsidian-litecite
> Add plugin: LiteCite

- community-plugins.json
Link to my plugin: https://github.com/Yuichi-Aragi/Version-Control
> Add plugin: Version Control

- community-plugins.json
Link to my plugin: https://github.com/kuzzh/obsidian-startpage
> Add plugin: Startpage

- community-plugins.json
Link to my plugin: https://github.com/thelivingphilosophy/zettelkasten-branch-tracker
> Add plugin: Zettelkasten Branch Tracker

- community-plugins.json
Link to my plugin: https://github.com/csteamengine/notesmith
> Add plugin: NoteSmith

- community-plugins.json
[https://github.com/JavierRibaldelRio/accounting-journal-ledger](https://github.com/JavierRibaldelRio/accounting-journal-ledger)
> Add plugin: Accounting Journal and Ledger

- community-plugins.json
Link to my plugin: https://github.com/Shaharyar-developer/remote-fetch
> Add plugin: Remote Fetch

- community-plugins.json
Link to my plugin:[obsidian-xiangqi](https://github.com/west-shell/obsidian-xiangqi)
> Add plugin: Chinese chess

- community-css-themes.json
Link to my theme: https://github.com/rastgame/obsidian-Noctilux
> Add theme: Noctilux

- community-plugins.json
- [] My README.md describes the plugin's purpose and provides clear usage instructions.
> Add plugin: Move Cursor On Startup

- community-plugins.json
This renames me to my new name janTatesa
> chore: rename TadoTheMiner to janTatesa

- README.md
- community-plugins.json
Link to my plugin: https://github.com/leafney/obsidian-xmind-linker
> Add plugin: XMind Linker

- community-css-themes.json
Link to my theme: https://github.com/tyronejosee/tyrone-neon
> Add theme: Tyrone Neon

- community-css-themes.json
Link to my theme: https://github.com/bastiangx/poimandres.obsidian
> Add theme: Poimandres Extended

- community-css-themes.json
A modern theme inspired by AnyType
Link to my theme: https://github.com/Bluemoondragon07/obsidian-future
> Add theme: Future
